### ISSUE TITLE
[Bug] Crypt.ee loading time increases after opening your first document in a session.

### ISSUE THREAD

**Issue by elevatorz89** [cryptee/web-client#102]
**Describe the bug**
When opening Crypt.ee for the first time on a session, you can load any document regardless of size with ease. However, once you open that first document, subsequent ones take forever to load, even at a similar length. It gets stuck on the "Decrypting..." screen, even to the point of freezing the page. (The browser spits out an error saying "A page is slowing down your browser. What would you like to do? [Stop it] [Wait] [X]")

This appears to be amplified on the PWA versions of the app, and in documents exceeding ~15-20k characters.

**To Reproduce**
1. Open any document, it doesn't matter which one.
2. Open up a second document, preferably a long one. Shorter ones will load fine.
3. Observe the long loading time.
4. If you're lucky, the document **_might_** load in anyway.

**Expected behavior**
Both documents (The initial one, and the subsequent one afterwards) should be loading at about the same rate.

**Screenshots**
![image](https://user-images.githubusercontent.com/53919102/109004839-440fbd00-7677-11eb-9aa2-0451beaa7065.png)

(Screen looks pretty identical for brave, just with its equivalent "page unresponsive" error)

**System Information (please complete the following information):**
 - Device: Custom Built Desktop PC
 - OS: Windows 10
 - Browser: Firefox 87.0b2, Brave 1.20.108 for PWA version
 - Browser Extensions / Add-ons / Content/Ad-Blockers: Ublock Origin, Bitwarden, Dark Reader, Sponsor Block, One Tab, Save to Notion, BTRoblox
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole] **No.**
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network] **Nope.**

**Additional context**

**Comment by johnozbay** [comment]
Hey there! 👋🏻

Thank you so much for filing this. 

This is quite interesting, because we're seeing literally the opposite of what you're describing. 
Things actually get faster as you open more documents thanks to server-side and service-worker client side caching. 
Here's what I mean, see the file sizes & loading times for comparison. : 

## Brave 1.20.108 / Mac OS X [tested minutes ago]
![image](https://user-images.githubusercontent.com/611338/109016629-05055a00-76bf-11eb-85c1-281ad5cc9fdf.png)

## Same but on Windows (albeit with better network, tested just now)
![image](https://user-images.githubusercontent.com/611338/109018261-9fb26880-76c0-11eb-9697-f503a4aad031.png)

So I can confidently say this isn't a network problem, if anything it's an encryption / decryption / available memory / processing speed problem. Needless to say depending on the amount of CPU / Memory you have available, this speed / smoothness and your experience may vary. 

---

Two things to factor in here. 

1) We actually check the number of processing threads / cores available to the browser using `navigator.hardwareConcurrency`

https://github.com/cryptee/web-client/blob/b5b9494b733603509703191d8ec3e4bff527b1f6/source/js/global.js#L1086

2) And  check whether if we can utilize service workers or not. 

And depending on 1 & 2, i.e. whether if Cryptee can use more threads or not, and whether if it can use service workers or not, we make a determination as to whether if we should use the native crypto provided by the browser, or use a non-native one in a service worker to not block / freeze the UI when we can. 
 
https://github.com/cryptee/web-client/blob/b5b9494b733603509703191d8ec3e4bff527b1f6/source/js/global.js#L1106

The reason why I said "_if we can_" is because there are hundreds of anti-fingerprinting / 'privacy' plugins out there that block service workers altogether to prevent tracking using them, causing encryption / decryption to be done on the main thread (or using native crypto on devices without hardware acceleration = so still on the main thread), resulting in piss poor crypto performance and frozen user interfaces.

---

Judging by the fact that it's a custom built PC, there are a bunch of extensions, and you're using Firefox Beta, I can semi-confidently say what you're experiencing is likely due to one or a combination of these : 

a) your computer reporting the number of cores wrong to the browser 
b) your browser reading the number of cores / utilizing them fully
c) your browser's configuration not allowing service workers
d) your extensions not allowing service workers
e) computer not having / supporting hardware accelerated cryptography
f) browser configuration not allowing to read whether if your device has native crypto or not to prevent tracking 

etc etc. 

I can say this more or less confidently, mainly because we test with real devices, have a testing lab of now ~50 different devices running 2 - 3 browsers, don't use simulators, and make sure the results are more or less similar. 

Often the issues we can't test against are live-network conditions (i.e. you're on a train, it goes into a tunnel, connection drops out mid way etc) and for those we try to test as much as we can locally and manually on things like ferries between Estonia and Finland where we lose connection exactly mid-way. You should see how hilarious we look like on the boat while traveling with a bag full of mobile devices 😅

---

If you can show some sort of exact recipe that causes this even on devices with reasonably enough processing power / memory /  extensions / service workers / anti-fingerprinting etc disabled, I'll be happy to jump on this first thing in the morning and get it fixed ASAP. But until then, I'm afraid I think this is a device-specific issue you're experiencing. 

Hoping this makes sense, and I hope I could explain the reasons why it's quite difficult to know the root cause is if it's not network specific.

Thanks a lot for this tho! I'll be looking forward to hearing from you, so we can get this fixed asap! ✌🏻

**Comment by elevatorz89** [comment]
The weird thing is that this was still an issue on V2, but I wasn't using cryptee as actively back then. (at the time it was more of an "archival bay" in terms of my use case.)

Okay. I've taken a look at my task manager, and despite working with old equipment, it still has enough resources in terms of CPU and RAM usage. Disabling extensions (including Ublock) didn't do anything. I went ahead and tried things out on my mobile phone, and the problem appears to be amplified still.

I've even tried other devices. There seems to be hardly any difference in speed, and these other devices were made in the last 3-5 years.

There is, however one thing that all of the documents giving me trouble have in common; they are all atleast 20,000 characters in length. Waiting out the exorbitant loading time once and reloading the document on a new session does lower the time, but not by much...

I can't comment on other networks since I won't have any access to them until the end of the week.

**Comment by jebbster88** [comment]
To add to this, I've just been testing the following.

Create two notes, "Long Test 1" and "Long Test 2", containing their own pasted content from https://lipsum.com/ (set to 30,000 bytes and pasted twice to give ~60000 characters)

If I then launch cryptee fresh, in either the same session, or a totally different browser or device, the following happens.
1. The first doc I open from recent, opens immediately
2. Opening the second doc can take up to a minute, definitely never less than 15 seconds. (During which time "decrypting" is flashing)

Tested on.
1. Linux Firefox (loads of extensions)
2. Linux Chrome (guest profile, no extensions)
3. Android Chrome PWA

Same result on all 3 (although firefox was the only one that briefly popped up the "long running script" message).

Is there some kind of browser session memory/local storage limit that could be causing this?

Edit: Android device is a OnePlus 8T. Linux device processor info below. Both devices have disk encryption, unsure if that is a significant factor.

![image](https://user-images.githubusercontent.com/8920215/110307163-8382c580-7ff6-11eb-8659-764dc876d660.png)

**Comment by ghost** [comment]
>Create two notes, "Long Test 1" and "Long Test 2", containing their own pasted content from https://lipsum.com/ (set to 30,000 bytes and pasted twice to give ~60000 characters)

>  The first doc I open from recent, opens immediately
    Opening the second doc can take up to a minute, definitely never less than 15 seconds.

This is weird... I just tested this on my devices.
I generated two long text files with around 500.000 chars. Both of them loaded after around 2 seconds.

**PC**
Hardware:
- Windows 10
- AMD Ryzen 5 2600X

Software:
- VPN
- Chrome 89.0.4389.82
- Firefox 86.0 (uBlock, privacytweaks)
- NextDNS

**Smartphone**
Hardware: 
- iPhone 11 Pro

Software:
- Safari 
- NextDNS

**Comment by jebbster88** [comment]
I just tried using Edge on a windows machine and got the same slowness.

@SteffB44 - were your docs one long wall of text, or separated as paragraphs?

**Comment by jebbster88** [comment]
The attached contains two cryptee notes (password: password123) with which I can reproduce the "1st opens ok, 2nd opens slow" steps.

[twofiles.zip](https://github.com/cryptee/web-client/files/6100943/twofiles.zip)

Do these two work ok for you?

**Comment by johnozbay** [comment]
I think an incredibly important element here is the available RAM / CPU resources. 

And when I say available memory, this isn't just your device's memory per-se, but also the amount of free memory your browser allows & allocates for each tab / window / website / domain to use. This amount changes from device to device, browser to browser, and to make things harder to estimate, ad-blockers / extensions etc can chew through available memory & resources quite quickly as well, since they can inject JS into pages. (i.e. [evernote's webclipper used to famously leak memory](https://discussion.evernote.com/forums/topic/102409-memory-leak-in-web-clipper-with-gmail/) – search the web for : "evernote web clipper memory" to get a sense of what I'm talking about)

So in the interest of having accurate test results, I encourage doing these tests on freshly installed browsers with no extensions / configurations etc. Otherwise, i.e. [Firefox has preferences for things like "Use Hardware Acceleration" or "Content Process Limit"](https://support.mozilla.org/en-US/kb/performance-settings) all of which could affect these tests' results. Especially if you've been using these browsers for a long time, have changed the configurations here and there then forgot about it.

The reason I'm suspecting this might be a memory availability issue is because when you have one document already open = in the memory of your device, if you try to open another document, in a way, you're downloading, decrypting, decoding and purging the old one from the memory, and putting the new one in memory. Depending on the amount of memory available this could happen quickly or slowly.

We do extensive testing on both our own hardware and on browserstack for older devices / exotic combinations, and we can't seem to reproduce this problem on any one of the devices or on browserstack.

If you can figure out what the root cause is though (even if it's a 3rd party extension etc), I'd be more than happy to take a look and fix it in any way I can ASAP. 👍🏻

**Comment by ghost** [comment]
Ok it got even weirder - now I have the same problem - even with a lot smaller documents. 
For me, it's the **third** note that takes a long time to load - and every time the firebox popup shows up.
I can switch between two large notes as much and as fast as I want, and they load nearly instantly. 

>  were your docs one long wall of text, or separated as paragraphs?

When it still worked, both worked fine. But I only tried it with two notes, the third one is what's causing trouble for me.

> The attached contains two cryptee notes (password: password123) with which I can reproduce the "1st opens ok, 2nd opens slow" steps.

I think something went wrong with those files because those are .json files. The cryptee format is .ecd 🤔

EDIT: This occurs in Firefox.

**Comment by johnozbay** [comment]
Oh and mandatory warning – needless to say – 

When opening / importing unknown Cryptee files from others on the internet, please proceed with caution, since there could always be a brand new attack vector we haven't looked into  / experienced before, that could harm your account / steal credentials etc.

**Comment by elevatorz89** [comment]
> I think something went wrong with those files because those are .json files. The cryptee format is .ecd

I'd like to interject and say that my problem actually does include .ecd files. 
Markdown files take forever to convert if they're lengthy, anyway.

I recently upgraded my pc, and my cable company sent out a new modem for an unrelated issue, so I will test again later to write out network problems from the equation.

**Comment by jebbster88** [comment]
> I think something went wrong with those files because those are .json files. The cryptee format is .ecd thinking

That's the file extension firefox defaulted to when selecting "Encrypted Cryptee Document" not sure why. I assume they're compatible, but yes @johnozbay makes a good point. The reason I wanted you to test with those files was just to see if the format of the document was similar (paragraphs/titles), in case the markup somehow came into play, so I've included a screenshot of that below.

![image](https://user-images.githubusercontent.com/8920215/110318173-13c80700-8005-11eb-819e-f6828fb88ce1.png)
![image](https://user-images.githubusercontent.com/8920215/110318206-1f1b3280-8005-11eb-8539-36ba5dce9434.png)

**Comment by johnozbay** [comment]
@jebbster88 It's super strange that your export resulted in a JSON format – that sounds like a whole separate bug right there. 

ECD uses a json structure on the inside, but your file should have been something like   `file.ecd`  (Encrypted Cryptee Document)    or  `file.uecd` (Unencrypted Cryptee Document) 

I wonder if this happens because your browser ignores the save-as name, (which ends with .ecd) and instead tries to sniff the filetype from the mime-type. ECD uses `application/json` – so this could be a strange separate bug. If possible could you please try this out and if you can reproduce what caused the filename issue file a separate issue for this ?

---

So I ran the exact same 60,000+ chars test from loremipsum, and made GIFs. 
(Lower frame-rate gif to easily upload to github, but timing is actual)

**Here's how it looks in latest Chrome 89 OSX**

![load-tests](https://user-images.githubusercontent.com/611338/110319142-21868800-8017-11eb-8b80-959fae12fbc4.gif)

**Here's how it looks in Firefox 86 OSX** 

![ff-load-test](https://user-images.githubusercontent.com/611338/110319611-d0c35f00-8017-11eb-9eb9-26e85d505af1.gif)

**Here it is on latest Chrome 89 WIN 10**

![chrome-89-win-test](https://user-images.githubusercontent.com/611338/110321381-44ff0200-801a-11eb-8e94-fb017ecaf2f2.gif)

**Here it is in latest Firefox 86 WIN 10** 

![ff-86-win-test](https://user-images.githubusercontent.com/611338/110320897-a1155680-8019-11eb-8dd5-a7cdb6d080cb.gif)

---

All tested on the same network, using ethernet to eliminate connectivity factors & variables. 
All tested on fresh browsers to eliminate configuration factors & variables. 
All tested using the same account & same 3 files with 60,000+ chars to eliminate file-specific factors & variables.  
All tested on Mac & Win machines with near-identical specs & intel processors.
All tested on machines that have 5 more tabs open in the background in another window with : reddit, protonmail, github, wikipedia, twitter to push the browser to its limits to factor out browser running out of memory etc type factors & variables. 

---

So I think we'll need to investigate memory availability, extensions, number of tabs open in the background, network etc. to get to the bottom of this.

**Comment by elevatorz89** [comment]
I have finished retesting, and nothing much has changed.

I emulated the test done earlier in the thread, and it indeed works properly. I think the problem is large files that are **_different_**, and not identical. After opening a document that isn't related to the three identical test documents, it starts acting up again.

**Comment by jebbster88** [comment]
I may be totally wrong, but from this performance trace in chrome, it appears the delay is after the decryption process (I believe that happens in "downloadDocumentOrFile". It looks to me like the bulk of the delay is happening within quill.js calls.

@johnozbay I can provide you with the saved profile from chrome directly if you want it

![image](https://user-images.githubusercontent.com/8920215/110327639-1f6dfa80-8012-11eb-9c1e-75a49923d98e.png)

![image](https://user-images.githubusercontent.com/8920215/110327820-62c86900-8012-11eb-885a-6e44b5c1b264.png)

**Comment by johnozbay** [comment]
Wow okay this was super useful  @jebbster88!! 🙏🏻   
I now have a really good idea about what's going on and I think you're on the money, this is coming all the way down from quill.js.

When you go from largeDocA to largeDocB, and set the contents of the editor, the editor generates a single diff and emits a massive 'text-changed' event with the changes. (long story short, this is necessary for detecting changes to trigger auto-save etc, but also for things like _unreleased_ collaborative editing features. ahem.
  
Looks like this 'diff' is super expensive. Especially when changing from one doc to another. 

However, if you go from largeDocA -> "", this diff seems easier to compute.
So right now our editor works like largeDocA -> largeDocB. (and this results in a lot of stuff to diff)

I'm going to try an experimental version that uses largeDocA -> "" -> largeDocB.
As silly as this may sound like, I think this 'diff' is the issue at hand here. 
Luckily it's an easy fix.

And holy shit if this is the case, and this works, free storage on the house for everyone on this thread 🎉 
What a weirdly specific yet critical discovery this has been! Thanks all! Will run tests right now – and ping back shortly.

**Comment by elevatorz89** [comment]
I _knew_ I was onto something. Can't believe it took me a year to actually report this incredibly annoying bug.

Honestly I'm very surprised nobody else has had these issues, especially when people actually use this service for journalling.

**Comment by johnozbay** [comment]
Same here, equally surprised. 

Odd thing is – internally, we use this flow all the time with massive documents. Like we handle all our legal / accounting / development todo-tracking etc inside Cryptee. As meta as this may sound like we actually use Cryptee to run the company, so we often bump into these issues before they even see the daylight. Strangely enough we haven't run into this either. (even in our automated tests etc, which all use 20+mb documents for testing) 

The bug does make a lot of logical sense though – building a test to confirm this is indeed the cause, stay tuned! ✨

**Comment by jebbster88** [comment]
@johnozbay i noticed in your demo gifs above, the text appears to be the same in all 3 docs. Could that be why it was quicker? Simple diff when they're identical.

**Comment by elevatorz89** [comment]
> 
> 
> @johnozbay i noticed in your demo gifs above, the text appears to be the same in all 3 docs. Could that be why it was quicker? Simple diff when they're identical.

Yeah, I did a similar test earlier, and got the same results. I guess it's some caching, perhaps?

**Comment by johnozbay** [comment]
Can confirm. This diff is the problem. Tested with completely different 10mb documents and now we can spot this. 

> I'm going to try an experimental version that uses largeDocA -> "" -> largeDocB.

And this seems to fix it! It's a one liner fix – so I'm going to push this to beta now for us to test. Hang in there folks! If you can confirm this works, I'll push this out to live in about 30 minutes!

**Comment by johnozbay** [comment]
Oh – and to clarify – 
The documents we loaded were lorem ipsums generated using the same generator. 
To spot if this is a network problem, decryption problem, DOM replacement problem, or a diff problem I tried all scenarios.
So the 3 documents in the GIFs had the same very long text. But since they're different documents, they all had to be downloaded, decrypted, and dom replaced. = eliminated the first three possibilities. Leaving "diff" as the main suspect.

**Comment by johnozbay** [comment]
The beta is out now : beta.crypt.ee 🎉

After logging in / updating, please go to your accounts settings (/account) and check that the version is indeed : `260d5e2` on the top right corner. Then try opening up the same documents and see if it works now ⚡️

**Comment by elevatorz89** [comment]
Holy crap, it works! It's almost instantaneous now.

**Comment by johnozbay** [comment]
🤯  Yaaaass! Party time! 🎉
The most insane one-line fix of all time. 

We're still finishing up the automated tests. 
As soon as they're ready and all tests pass I'm going to push this to live. 
Shouldn't take us longer than 30 minutes or so ⚡️

**Comment by elevatorz89** [comment]
> free storage on the house for everyone on this thread

I don't want to be _that guy_ but I'm curious about what this entails.

**Comment by johnozbay** [comment]
Hey there folks! 

All our tests seemed to show this is now fixed, automated tests passed, and being the excitable human I am, we pushed this live just now. If you haven't seen / checked out the beta yet – you can now check out the live version instead 🎉

> I don't want to be that guy but I'm curious about what this entails.

@PreciselyPixels it means I get to press a button & you guys get a surprisingly large amount of free storage forever on the house.

@PreciselyPixels @jebbster88 @SteffB44 – whenever you can, shoot your usernames / emails to `support {at} crypt [dot] ee` and I'll push the " 🎁   " button! hahaha 

I owe you three a lot for your patience and help with this! Deeply appreciate it all! 🙏🏻

**Comment by johnozbay** [comment]
I've just got confirmation from @jebbster88 and @PreciselyPixels!  
Looking forward to your email @SteffB44 ✌🏻  

Thanks again folks! You rock ⚡️
