### ISSUE TITLE
Folder browser loses context

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#106]
**Describe the bug**
As soon as you go to the recent documents list, the folder browser context is lost and the folders button will only return to the root folder, whether the sidebar is open or closed. It should be possible to return to my place in the folder browser after looking at the recent documents list.

When the sidebar is closed with the folders view active and inside of a subfolder, the meaning of the folders button changes to "current folder". I think it should do the same thing when the recent documents list is opened.

**System Information (please complete the following information):**
 - Device: Macbook pro
 - OS: MacOS Mojave 10.14.6
 - Browser: Firefox 85.0.2
 - Browser Extensions / Add-ons / Content/Ad-Blockers: lots but I doubt they're related to this.

**Comment by johnozbay** [comment]
Thanks for filing this! ✌🏻
This is intentional and not a bug, although I see how it could cause confusion. 

It has to do with the way our 'move' function works. 
Basically, when you're moving something, the floater shows up at the bottom of the screen, and starts watching your current 'view' (are you in folders [root], are you in a sub-folder [root/folder1] etc) and once you click "move" it moves the stuff you've selected to the current 'view'. 
 
Once you click on Recents, your view becomes "recents", and you're navigated to [root]. 
There are three reasons we did this. 

1) For backwards compatibility. Home documents (leftover from v2) don't have folders, so they exist only in "recents" (so technically 'root')

2) We're working on bringing support for documents that won't exist in any folder, but exist directly in 'root', so your documents won't need to exist in folders. As to why we're working on this ->

3) We're working on a super special new feature I don't want to disclose yet, but it'll take Cryptee Docs to a whole new level 😅  We have to migrate all users to new v3 before we could launch this – so it's taking us a bit more time. 

So I'm afraid as confusing as it may be at the very moment, it's going to get a little less confusing soon I promise 🤓
