### ISSUE TITLE
[Feature Request] the sort icon in folder view may show the sorting mode

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#109]
**Is your feature request related to a problem? Please describe.**
It is a bit confusing that in the folder list the "sort items" icon remains the same independent of the sorting mode

**Describe the solution you'd like**
The sort items icon shall reflect the current sorting mode, eg.:
- ascending by name: a->z
- descending by name: z->a
- ascending by date: 2000->2099
- etc. etc.

**Additional context**
n/a

**Comment by johnozbay** [comment]
Hey there! 

Thanks a lot for filing this! 

What happened here is that in V2 lots of people got confused about the button's states and what it shows. Basically, the question is : 

Should the button's icon show the current sorting order? 
OR should it show the sort action you'll take once you press it?

For example, if you think about the delete button of a file, it has a trash icon, meaning that it shows the action you'll take if you press it. 

But with sort, it's a bit weird, because you also want to know how your files are sorted right now. 
So if it shows : 
A - Z ↓

Does this mean what you're looking at right now is A-Z sorted ascending OR 
what you're looking at right now is actually A-Z descending ( AZ↑), and if you press the button it'll be AZ↓) 

I hope this makes sense 😅 

It's surprisingly difficult to design sort buttons apparently. So I'm now making it like the Photos sorter. It will have a popup, 
and show you how things are sorted right now, and all the other ways you can sort. 

In the interest of pushing v3 out quicker, I made it a toggle switch, and very soon it will be a dropdown / pop-up much like the photos' sorter. 

Hope this makes sense! 
Stay tuned, it should be ready in a week or so! ✌🏻

**Comment by BasilTomato** [comment]
"_So I'm now making it like the Photos sorter. It will have a popup, and show you how things are sorted right now, and all the other ways you can sort._"
Thank you, this solution sounds great!

**Comment by johnozbay** [comment]
Here's how it's going to look like : 

![image](https://user-images.githubusercontent.com/611338/109608948-55534080-7b33-11eb-90c4-8a5164dbf71f.png)

We're testing it on different OS / Browser / Device combinations, and will release soon 🎉

**Comment by johnozbay** [comment]
Give it a try and let me know what you think 🎉

**Comment by BasilTomato** [comment]
Thank you, it is great!

**Comment by johnozbay** [comment]
You're so very welcome 🎉
