### ISSUE TITLE
[Feature Request] Sort documents by creation date

### ISSUE THREAD

**Issue by real-marshal** [cryptee/web-client#117]
**Is your feature request related to a problem? Please describe.**
I have hundreds of notes imported from Bear. They’re like a diary so they only make sense when read in order of creation which often differs from change date as occasionally I come back to them and add something new (with a remark of when the change was added right in a note)

**Describe the solution you'd like**
In Bear there’s a sort by creation date which solves my problem so I suggest adding it here as well.

**Additional context**

**Comment by johnozbay** [comment]
Hi there 👋🏻

Thanks a lot for filing this! 

While I can see how this would be useful for some, we can't add this feature for two reasons. 

1 – For privacy reasons we don't store the creation timestamp metadata. We only store the last-modified timestamp (which we do, only because we have to, in order to be able to detect changes & facilitate sync between devices correctly when something's edited)

2 – Even if we did store this, it would have to be the date of creation in Cryptee (or the date a file was uploaded to Cryptee) and not the creation date of the file itself. [Because just like Cryptee, browsers also don't expose file creation dates for privacy reasons, and instead only expose the last-modified-date](https://developer.mozilla.org/en-US/docs/Web/API/File).

For your specific use case, I'd recommend putting your diary entries in a folder like "Diary" and renaming the documents like "2021-03-21", "2021-03-22", "2021-03-23" using the [ISO date format](https://en.wikipedia.org/wiki/ISO_8601). That way, when you sort the folder alphabetically, you would always see the documents in the correct day order. (and can later re-sort the folder based on the change date as well if you wish)

I know it's not ideal, but this is one of those privacy / convenience compromises we have to make.

Hoping this makes sense and helps ✌🏻

Best,
J
