### ISSUE TITLE
[Bug] Can’t put a cursor after checked items on iOS

### ISSUE THREAD

**Issue by real-marshal** [cryptee/web-client#119]
**Describe the bug**

If you check an item in a list then you can’t move a cursor below that checked item which means you can’t change any following text or add something new. 

**To Reproduce**
1. Create an ordered list
2. Check an item
3. Try to change any item below the checked one

**Expected behavior**

Change any text anywhere regardless of checked items. 

**Screenshots**

**System Information (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.4.1
 - Browser Safari
 - Browser Version 14
 - Browser Extensions / Add-ons / Content/Ad-Blockers AdGuard content blockers
 - Do you have any DNS-based content/ad-blockers? No
 - Are you on a managed network? Using VPN

**Additional context**

**Comment by johnozbay** [comment]
Hi there! 👋🏻
Thanks a lot for filing this and apologies for the delay! 

We can reproduce this and we're working on a solution / workaround. 

It seems like a bug in iOS Safari and how it handles cursor positioning in a buggy way when there's `pointer-events : none` and how our editor handles check-box actions. 

Checkboxes are `::before` pseudo-elements, so on iOS when they are focusable, the rest of the text seems to be not-focusable by the cursor (although it is on desktop Safari, and all other browsers on all other operating systems)

So we're working on a solution for iOS and hopefully will have something soon! 

Thanks for reaching out with this, and for your patience! 

Best,
J

**Comment by johnozbay** [comment]
Hi there, 

Thanks a lot for your patience with this!

Turns out this was a bug with iOS itself, and iOS 15.0.1 seems to have finally fixed this. 

[Screenshots can't show the cursor, but I opened the copy/paste popup to show you what I mean]

![IMG_8B358F196355-1](https://user-images.githubusercontent.com/611338/136670544-36856b13-70b2-4379-a7af-3f7880d64521.jpeg)

Let me know if you happen to bump into this again, and we'll ping the good folks at apple again to give things another look.

All the best,

J
