### ISSUE TITLE
[Feature] Add EtherCalc Support

### ISSUE THREAD

**Issue by gjhklfdsa** [cryptee/web-client#12]
**Description**: Add EtherCalc Instance
**What is EtherCalc**? EtherCalc is similar to google sheets, but free software.
URL: https://github.com/audreyt/ethercalc

**Comment by johnozbay** [comment]
Hey @gjhklfdsa! 👋🏻

This looks fantastic! 🎉
It'll definitely take some time but it's 100% doable. 

- [ ] I'll have to see how and where I can plug encryption 
- [ ] Where I can add cryptee's websocket hooks, 
- [ ] What would need securing (say for example what happens if a user injects a malicious html element / script into the table, would ethercalc strip these out, or pass it straight through the socket to the next user) – this is one of those things I had to make sure Cryptee editor handles well, so that if a user copy pastes a text from a random website, their keys or private data can't be stolen etc. 
- [ ] If this is all doable without having to create a super-off-branch fork that will become a huge burden to keep everything maintained in the longer run.
- [ ] and finally investigate to see if its uncommon license would be a legal problem down the line.
 
I'll run a complete feasibility analysis whenever possible, and keep this thread updated! 
Exciting idea! 🎉

**Comment by johnozbay** [comment]
Unfortunately we will not be supporting this due to how incompatible it would be with our current infrastructure. But more importantly due to its unusual license. I voted for having a parallel infrastructure for this, attorney voted no for license. Attorneys are always right. 🙄

We're looking into alternatives. ✌🏻
