### ISSUE TITLE
[Change] Change default setting of spell checker

### ISSUE THREAD

**Issue by gimbald** [cryptee/web-client#120]
**Is your feature request related to a problem? Please describe.**
I use the spell checker a lot when making docs and I find that I have to turn it on each time I make a new document or re open an old one. 

**Describe the solution you'd like**
It would be nice if it can be either as an option like "On by default" or "Off by default" or just remember if I had turned it on or off in a previous document.

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Thanks a lot for filing this! 
We used to have this feature, and even had some mini-discussions around this in #88 – but with our version 3.0 update in February, we decided to get rid of this. 

The problem with it was: 
Each browser has a different auto-correct implementation; Some perform really well, but some are horribly slow. 
Depending on your browser and how large your document was, some browsers' spell-checker was causing browsers to crash as soon as you loaded a large document. 

So even if you turned on the spell-checker in Chrome, where it worked great, but then later accessed the same document in Firefox for example, the browser would crash as soon as it loaded the document (🤦🏻‍♂️), and understandably, it was confusing the hell out of some users. 

So we decided to remove the default global setting altogether and made it per-document a few months ago. 

We are keeping an eye out for this, and still testing the old idea every now and then with major browser updates. If browsers get better at this in a year or so, we could bring it back! 

But until then, I'm afraid we can't add this feature since it caused more problems than it solved 😞

Hoping this makes sense and helps! ✌🏻

Sorry about this! 

Best,
J
