### ISSUE TITLE
[Bug] Pressing TAB-key in a code block causes cursor to move to the end of next line

### ISSUE THREAD

**Issue by byrmsh** [cryptee/web-client#130]
I saw crypt.ee in a reddit post about 10 minutes ago and my first impression is really great. The UI is outstanding. But after experimenting with the docs, which is most-likely why I will use crypt.ee if I do, I realized the editing inside of a code block is buggy. I am not sure about other languages but especially when tab key pressed while writing HTML, the cursor sometimes moves to the end of the next line.

Related GIF:
![Peek 2021-06-28 22-49 cropped](https://user-images.githubusercontent.com/48856944/123697475-a36c1c80-d865-11eb-944a-f33e9c00fbe7.gif)

(BTW is there an option to set language for code block because i couldn't find. looks like it automatically detects but i am not sure.)

**Comment by johnozbay** [comment]
Hi there 👋🏻

Due to the fact that tons of different devices, operating systems (and their versions), browsers (and their versions), browser extensions (and their versions) and things like DNS filters / VPN filters etc in use nowadays, there is no way we can test against all these combinations and scenarios. 

While filing bug reports, please provide the specific information we ask for in our new issue templates, so that we can reproduce the issues you're experiencing and fix it up quicker. 
 
**We need the following information at the very minimum to be able to look into issues:**
 - Device: [e.g. iPhone6 / Laptop with touchscreen etc.]
 - OS: [e.g. iOS8.1, Windows 10]
 - Browser [e.g. safari, chrome, firefox, stock browser]
 - Browser Version [e.g. 22]
 - Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.] 
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole]
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network]

---

All this being said, tab-keys are treated differently on each operating system and device, each browser, and even depending on whether if you use a soft-keyboard or not. Here's an example of this #48 ... 

So for us to be able to do anything about this at all, we'll definitely need a lot more system info. 

---

Thank you for your understanding! 

John

**Comment by byrmsh** [comment]
You are absolutely right. I should have thought about that.


## Device: [e.g. iPhone6 / Laptop with touchscreen etc.]

Laptop without touchscreen using external keyboard

## OS: [e.g. iOS8.1, Windows 10]

Manjaro Linux (kernel version: 5.10.42) with KDE desktop environment v5.21.5

## Browser [e.g. safari, chrome, firefox, stock browser] & Browser Version [e.g. 22]

Brave v1.25.68 (based on Chromium v91.0.4472.77)

## Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.]

I disabled all of the installed extensions and Brave Shield (which is a built-in feature of Brave that blocks ads and tracking cookies), then cleared the cookies but the bug still occurs.

## Do you have any DNS-based content/ad-blockers? [i.e. pi-hole]

No.

## Are you on a managed network? [e.g. VPN / Corporate / Campus Network]

No.

## Locale & Keyboard Layout
Using `en_US.UTF-8` locale with English (US) keyboard layout. The browser language is also English.

## Extra
The bug also occurs in Firefox v89.0.2 so the bug is most likely not about Brave or Chromium.

**Comment by johnozbay** [comment]
Thanks for your understanding!

We're looking into this now, and we'll try to get a fix out as soon as humanly possible.

**Comment by johnozbay** [comment]
Hi there, 

I've fixed this in the alpha version now and linked this issue to our internal issue/release tracker.
Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification!

Thank you so much for your help and patience! 🙏🏻
