### ISSUE TITLE
[Bug] New document & folder dialogs covered in landscape on iPad

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#135]
**Describe the bug**
When trying to create a new folder or document while the iPad is in landscape orientation, the input dialog is covered by the keyboard.

**To Reproduce**
1. Put iPad into landscape
2. Try to create a folder or document from the sidebar buttons
3. See how the dialog gets covered up.

**Expected behavior**
If you close the keyboard and then reselect the input field, everything slides up and is properly visible, which is closer to what I’d expect to happen the first time.

**Screenshots**
![Image](https://user-images.githubusercontent.com/273696/126020122-8478dc8f-dc05-489b-8f3c-9154562d93c7.gif)

**System Information (please complete the following information):**
 - Device: iPad Pro 11 (3rd gen)
 - OS: iPadOS 14.6
 - Browser: Safari PWA

**Comment by johnozbay** [comment]
Hi there! 
Thanks for filing this! 🙏🏻
Unlike the other iPad OS keyboard bug, this one's on us and not Apple – we'll have a fix out for this asap.

**Comment by johnozbay** [comment]
Hi there, 

https://github.com/cryptee/web-client/commit/13fec562257ea35b3fec08d5b3a9ec180e457f78 brings an entirely new New Doc & Copy Doc modal, so this issue should be fixed, and you should be able to type easily even with the on-screen keyboard open. 

That being said, we're also working on a bunch of cool other improvements (i.e. detecting where the on screen keyboard is and displaying all modals & popups always above the keyboard. and even changing their appearance if necessary [for example on tablets in landscape mode, we can make modals wider, instead of taller etc]) so once these improvements are out with the upcoming releases, I think this will get even better. 

Thanks a lot for reporting this and your patience with this, 

All the very best,
J
