### ISSUE TITLE
[Discussion] Encryption Key Reset

### ISSUE THREAD

**Issue by gjhklfdsa** [cryptee/web-client#14]
**Description**: Add encryption key reset capabilities (with optional opt-out)
**How**? So, I would propose utilizing the original password with some other known data similar to [security questions](https://www.wikipedia.org/wiki/Security_question). In theory you could automatically generate a new password based on this, within the browser (fully offline).

Some apps are already working on similar things like [MasterPassword](http://www.masterpasswordapp.com/) and [LessPass](https://lesspass.com/).

I would assume other options are possible.

**Comment by johnozbay** [comment]
Already considered this about a year ago while starting to build the platform, because this would make life a lot more easier for not-so-tech-savvy users. However, came to the conclusion that there's too many problems with this from a threat-model standpoint. 😔Pretty sure I wrote my conclusions somewhere, but some off the top of my head: 

It can only be added, if it also invalidates and deletes all earlier encrypted data uploaded by the user, ([Similar to Protonmail](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/32760352-why-do-you-have-to-erase-all-mail-when-you-reset-y)) since all existing data would be encrypted with the old key. (but then, might as well delete the account and create a new one, which is what Cryptee already allows you to do without your encryption key, in case if you forget your key, and say for example have a paid subscription etc.)

If `security questions` or alike could be used to reset encryption keys, and resetting encryption keys allowed access to encrypted historical data of users; this would allow for a way for Cryptee staff (or other legal enforcers) to on-demand trigger key-resets and access users' old data in plaintext. (since `security questions` or alike would have to be stored _unencrypted_ in order to be utilized to reset the forgotten encryption key in the first place) and they would of course be hashed etc. but in general this would merely be the equivalent of creating backup keys, and asking the user to remember those, instead of the security questions. 

I'm open for ideas if this could be fit into the threat model without causing an inherent trust issue, or yet another layer of impracticality/inconvenience. As far as I can see, (and evidently as far as PM folks could see) there's no easy way to do this without compromising the no-knowledge architecture. – but again. I'm open for ideas 😅

**Comment by johnozbay** [comment]
After a months of thinking and discussing this we've decided not to add this feature for the time being. It adds way too many complications with our current threat model. 

That being said, I'm working on revamping bulk of the auth flow, incl things like adding 2FA etc before the end of this year. We've decided to bring this up again after the auth-flow 2.0 is out of the way. 

Closing for the time being.
