### ISSUE TITLE
[Feature Request] More space, font size, plugin, line table.

### ISSUE THREAD

**Issue by bryn1u** [cryptee/web-client#147]
Hey,

First i would like to thanks for your great job. Im happy to use it :)

I have a some request. Based on screen below is there any possibility to stretch the white fild where a text is placed. I think around that text filed is to much free space and it can be used as writing space (A1, A2 pages?). What do you think?
https://ibb.co/857gkst

Second. Is there any way to add 12 and 14 font size?

Third. The Evernote has plugin that you can select screen or article or part of artice and put it direcly to note. Which is great option. You don't neet copy and paste, you don't need to take a screenshots or similar. Maybe that kind implementation is possible for Cryptee? 

Fourth. The quote and qoute color is really geat. Dont you think put another qoute color but some birghter color?

Fiveth. When you put a table you can't move a line in the center. The line is static. It isn't comfortable when you have more text on the left or right side :(

You are doing great job.  Im and my friend gonna buy higher subscribtion. Thanks once again.

**Comment by johnozbay** [comment]
Hi there! 👋🏻
Thanks for your kind compliments! Glad to hear you're enjoying Cryptee! 

---

1 – Regarding screen real-estate. This is somewhat related to #58, but basically, it used to be the way you're describing, where the more you stretched your screen, the more the page would expand. Now instead, we have paper-mode, where you can choose the paper sizes (i.e. A4 etc). You can enable this mode by clicking this button on the right side of your screen : 

<img width="84" alt="image" src="https://user-images.githubusercontent.com/611338/162626440-e92a404d-ce28-494a-983d-4cf22b28ad66.png">

Currently it's in BETA, so we're slowly testing and killing bugs in our paper-rendering. Once this is ready, we'll start adding support for more paper-sizes, and rotations. (incl things like A1 / A2 etc) Coming soon 🎉  Keep an eye out to our [blog](https://blog.crypt.ee). We'll make a big announcement there once this is ready. 

---

2 – (Custom Font Sizes) Somewhat related to the previous point as well. It's about how our paper-mode rendering engine works at the moment. Once it's ready for primetime, we'll make this editable, so you'll be able to add custom font sizes as you'd like. At the moment having fixed font-size is critical to how we calculate our paper layouts. 📄

--- 

3 – If I understand correctly, I believe you're referring to Evernote's web-clipper. 

A long while back, we've actually secretly shipped support for a webclipper in Docs – but you could only use it if you had  the unshipped/alpha clipper extension installed. 

https://github.com/cryptee/web-client/blob/e6a0627587bf514057ea2463eed234f30b66899f/source/js/docs.js#L10508

And we ran intense security tests with the clipper extension itself. We discovered that there are SO MANY security issues a web clipper can cause. In short, we decided against building a webclipper after realizing the attack / threat vectors it opens up. We're looking into how else we can tackle this challenge, but for now we're not going to ship it. 

What kinds of security issues you might rightfully ask. 

So for example, what happens if the site you clipped has malicious javascript code embedded in the content? It will get carried over to your Cryptee account, and can try to steal your information etc. So when any content is clipped, Cryptee's clipper extension would need to try its best to strip malicious javascript from it. And this needs to be built in a way that it doesn't strip the actual content away, otherwise you'd be frustrated. Which turned out to be very very difficult, given the way internet is built. Each and every website has a different structure / layout / design etc, and it's challenging enough to build a good clipper, a whole different challenge to make sure it strips malicious content from the clipped stuff before it's passed onto Cryptee. 

i.e. Evernote doesn't do this type of security checks. So if you clip (or even paste stuff) from the web to Evernote, it actually pastes the content as-is. So if you've copy pasted a paragraph with an image in it, Evernote pastes the <img> element directly from the web into your note, instead of downloading the image itself. Due to this, every time you open this Evernote note, Evernote goes to that url and fetches the image from the source. (which means, the image source can track how many times you open that note) – but more importantly, Evernote also allows images from HTTP sources, and doesn't enforce HTTPs. So if you paste/clip an image from an HTTP source, it will also get carried and pasted into your note. (and every time you open that note, Evernote connects to that insecure HTTP url and fetches the image) = if you're on a public connection / office or campus wifi / coffeeshop etc. anyone monitoring the traffic can see the image you're loading. 

So for Cryptee we can't allow any of these. In fact we have a built in tracker prevention system that stops all types of carried-over malicious activity like these. You can read all about this here : 

https://blog.crypt.ee/say-hello-to-a-new-cryptee/#copypaste-tracker-warnings

Which means when you clip something (say an image), the clipping extension needs to serialize / convert the image in your browser at the time of clipping, then encrypt it, then push it to your Cryptee account, and this means, malicious content needs to be stripped in-browser, in-extension, before it gets encrypted and pushed to your Cryptee account. (whereas Evernote can do this on their servers for example) etc. etc. 

And this is the part we tested thoroughly, and decided against rushing this feature, – for a good reason given the state of the internet nowadays. The last thing we want is an ad tracking pixel getting clipped into your Cryptee account or worse some malicious JS stealing information etc. 

--- 

4 – (Quote color) We're trying to keep things simple, and won't be shipping more additions to quotations. We may however, some day ship a way to change text-underline-color. Not exactly what you're after, but figured I'll mention since it's somewhat relevant. 

The reason I'm saying this is because, we'd need to have 4 color dropdowns, one for font color, one for highlight color, one for underline color, one for quote color. It's simply too much / a bit maximalist, and not really in line with our minimalism goal. 😕

---

5 – Adjustable table columns are on the way! In fact coming in the upcoming months! Stay tuned out to our blog, we'll make an announcement 👍🏻

---

Hoping these make sense and help! ✌🏻
Once again many thanks for your kind words, as well as your paid support! Deeply appreciate it! 

Needless to say please keep filing bug reports / feature requests! We'll do our best to get them fixed and shipped as quickly as humanly possible! 

All the very best,

J
