### ISSUE TITLE
[Bug] Folder titles aren't visible on Android Chromium (Bromite)

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#156]
**Important Note**
_If you have any account-specific issues, like having problems signing-in, resetting your password, or issues related to your payments etc, you should first contact our [helpdesk](https://crypt.ee/help). We use Github to track issues affecting all users / bugs with the apps or service, and due to the fact that we can't exchange account-specific information on Github, our Helpdesk is much better equipped to handle account related issues._

**Describe the bug**

The titles of the folders are not visible on Bromite. If I rename a folder it becomes visible again but only until I exit.

**To Reproduce**

N/A

**Expected behavior**

The title does not disappear/becomes invisible.

**Screenshots**

![Screenshot_20220805-125527_Bromite](https://user-images.githubusercontent.com/94188674/183065013-fafef243-da50-4e23-b41c-8d742798f93f.png)

**System Information (please complete the following information):**
 - Device: [e.g. iPhone6 / Laptop with touchscreen etc.] Samsung Galaxy
 - OS: [e.g. iOS8.1, Windows 10] Android 12
 - Browser [e.g. safari, chrome, firefox, stock browser] Bromite
 - Browser Version [e.g. 22] 103.0.5060.140
 - Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.] Default Bromite adblocker
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole] No
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network] N/A

**Additional context**

**Comment by johnozbay** [comment]
Hi there! 

I'm quite confident this is happening because of your browser's customizations. Or you must be using some strange auto-dark-mode extension / feature etc. 

I can tell it's your browser's fault by that screenshot, because tab-part of that folder's design is an SVG file ([foldertab.svg](https://github.com/cryptee/web-client/blob/v3/source/assets/foldertab.svg)), and it's dark. Not white like it appears in your screenshot. 

So I'm 100% confident your browser is doing some strange dark-mode conversion. So consequently,  
Dark Folder Tab => Light Folder Tab
Light Text => Dark Text [ over dark folder ] = invisible. 

---

This brings into question how many other things your browser or your configuration is actually breaking. So I would strongly recommend taking a deeper look into your configuration and double checking #158, #161 and #162 with this in mind. I think your browser or configuration is to blame here.  

---

Best,

John

**Comment by ghost** [comment]
With Vanilla Chromium with default settings this happens the same as with Bromite. With default Firefox and non default Mull this does not happen. Bromite does use some kind of Dark theme checkbox but that does not change anything. Also please note that every test I do is via the WebApp.

**Comment by johnozbay** [comment]
I specifically linked to the image file so you can see it's dark yourself. We physically don't even ship light colored folder tabs. Whatever is going on, is going on because either your Android vendor / OS / browser / something's changing the contents of the page, inverting the color of images (and presumably text as well) 

I'd recommend trying turning your phone's dark mode on / off to see if it helps. But I'm 100% sure this isn't us, because we physically don't ship light colored folder tabs, and there's nothing in our code that can possibly invert those images colors.

**Comment by ghost** [comment]
![Screenshot_20220821-104020_Chromium](https://user-images.githubusercontent.com/94188674/185783120-bfa8fa24-d105-430e-a15b-82b3af71e421.png)

This is how it looks like in Vanilla Chromium and Bromite (after I disabled Dark mode checkbox). I have tried opening an issue to Chromium before with no luck and I think I would also need a Google account for that. Also this is a very specific issue if I decide to open a Bromite issue and they have more important things to worry about last I checked so I don't really know where to turn with this. I have also turned device dark mode off, did nothing.

**Comment by johnozbay** [comment]
Thanks for the screenshot! 

As you can also see the browsers are messing with the actual contents of the page if the dark-mode is switched on. So I'm somewhat certain this is a browser bug. 

We've got a few friends on the Chromium team, so we'll file a bug with Chromium and get to the bottom of this quickly. 
In the meantime I'll check if there's anything we can do to work around the bug while they fix things. 

Many thanks for the screenshots and bearing with me on this. It's super difficult to debug things like this, since as you can see even non-hardened browsers are out there messing with things nowadays 😅
