### ISSUE TITLE
[Feature] Hide "down arrow" icon in Markdown charts when typing

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#157]
**Is your feature request related to a problem? Please describe.**

When typing in a chart the mentioned icon often hides the written text, which is annoying.

**Describe the solution you'd like**

Hide this arrow icon when typing.

**Additional context**

**Comment by johnozbay** [comment]
Hi there! 👋🏻

First off, just to clarify something, Cryptee is **not** a markdown editor. It is a rich document editor, similar to Google Docs / Word, with its own document format, that is **not** based on markdown. 

We support markdown shortcuts, but it's limited to what's in the markdown specifications. Contrary to popular belief, [Markdown specifications](https://spec.commonmark.org/0.30/) **do not** support tables, and only third party flavors do. 

In the interest of inter-operability we don't support flavors. 

Since your documents are encrypted on your device, and our servers can't access your documents, our servers also cannot do maintenance on your documents in the future either. So if some day in the future these flavors casually change, your tables would break, or it could cause crazy inter-operability issues between softwares that support markdown, and our servers wouldn't be able to update your documents due to encryption. 

---

The "down arrow" you're referring to is a standard feature in all rich document editors that support tables. i.e. Google Docs :
 
![gdocs](https://user-images.githubusercontent.com/611338/185777745-dd16251d-7047-4601-bb38-b8fc7a9d685f.jpeg)

So we won't be removing or hiding this, as it is a necessary feature, and one that is pretty much standardized across all rich document editors.

---

We also can't hide while typing. Phones / Tables / Laptops with touchscreens with on-screen keyboards don't report "typing". Think about how your auto-correct/dictionary on the phone works. you see suggested 'words' appear above the keyboard, and once you tap on them, they are populated as a whole word on the screen. So the arrow would be hidden only for 100ms while those words are inserted on the screen, but then re-appear. 

We also can't hide it while the on-screen keyboard is open either. (let's say if we assume on-screen keyboard open =  "typing") On all touchscreen devices, if you place your cursor anywhere, the keyboard will show. And if you close the keyboard the cursor will be removed. In order to know which table row / column you want to take action on, the cursor needs to be present. So we can't hide the arrow while keyboard is visible either, since we need the cursor to be visible. 

---

I hope these make sense!

Sorry to disappoint,

Best,

John
