### ISSUE TITLE
[Bug] Cannot add columns or rows to charts and they are overall really buggy

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#158]
**Important Note**
_If you have any account-specific issues, like having problems signing-in, resetting your password, or issues related to your payments etc, you should first contact our [helpdesk](https://crypt.ee/help). We use Github to track issues affecting all users / bugs with the apps or service, and due to the fact that we can't exchange account-specific information on Github, our Helpdesk is much better equipped to handle account related issues._

**Describe the bug**

There are multile glitches and bugs regarding charts in Markdown. For example on Android sometimes I cannot create new charts (this is not the case on desktop) and is not reproducible. I cannot however create rows and columns anymore on certain charts (Fig. 1) both on Android and Linux, but then I could create a new one under the old glitched one (Fig. 1) on Android (that I could not before) which I could then expand with new rows and columns. But after adding characters and expanding said chart again weird glitches happened again. (Fig. 2) On Linux there was a bug where trying to expand the chart by enters resulted in weird grid glitches as shown on Fig. 1, then the cursor left the chart, started doing something glitchy under the chart, then went ABOVE the chart and started placing linebreaks which I could not delete via backspace, only overwrite text in them (which I could delete with backspace). I could only delete linebreaks with Del. The additional weird thing is that, doesn't matter if I deleted these lines in the document, other Markdown docs somehow inherited them. These disappeared after a reset.

**To Reproduce**

![shrek-good-question](https://user-images.githubusercontent.com/94188674/183071599-a00e59cf-7689-42cf-8ab3-901458c5bc9b.jpg)

**Expected behavior**

No bugs please

**Screenshots**

Fig. 1: 

https://user-images.githubusercontent.com/94188674/185908858-13583ba9-3e0e-4314-be7e-c028b1330aa1.mp4

Fig. 2: ![Screenshot_20220805-133628_Bromite](https://user-images.githubusercontent.com/94188674/183071815-e0a61cb2-023b-4919-96f0-6f62949a63c5.png)

**System Information (please complete the following information):**
 - Device: [e.g. iPhone6 / Laptop with touchscreen etc.] Samsung Galaxy and Desktop
 - OS: [e.g. iOS8.1, Windows 10] Android 12 and Linux
 - Browser [e.g. safari, chrome, firefox, stock browser] Bromite and Brave
 - Browser Version [e.g. 22] Bromite 103.0.5060.140 and Brave 1.42.86 Chromium: 104.0.5112.81 (Official Build) unknown (64-bit) 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{https://github.com/brave/brave-browser/issues/1309} Linux
 - Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.] Default Bromite adblocker and [PrivacyGuides hardening guide for Brave](https://www.privacyguides.org/desktop-browsers/#brave) 
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole] No
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network] N/A

**Additional context**

![4270_amogus](https://user-images.githubusercontent.com/94188674/183072118-4bcf5257-e82c-4cc1-9708-7f09824c9912.png)

**Comment by johnozbay** [comment]
Hi there! 

Thanks for filing this! 

I responded with the below text to another bug report you filed, but I'll refer to this here as well, for others who may find this thread at some point. 

---

First off, just to clarify something, Cryptee is **not** a markdown editor. It is a rich document editor, similar to Google Docs / Word, with its own document format, that is **not** based on markdown. 

We support markdown shortcuts, but it's limited to what's in the markdown specifications. Contrary to popular belief, [Markdown specifications](https://spec.commonmark.org/0.30/) **do not** support tables, and only third party flavors do. 

In the interest of inter-operability we don't support flavors. 

Since your documents are encrypted on your device, and our servers can't access your documents, our servers also cannot do maintenance on your documents in the future either. So if some day in the future these flavors casually change, your tables would break, or it could cause crazy inter-operability issues between softwares that support markdown, and our servers wouldn't be able to update your documents due to encryption. 

---

So if you created this table using Markdown (i.e. via importing a Markdown file into Cryptee which had a table) this is likely a result of markdown-table interoperability / compatibility issues and could be due to a million different reasons depending on how your markdown file was exported. Since again, tables are not a markdown spec standard, there's thousands of different implementations, who knows how each one works. 

And if you created this table using Cryptee (by pressing the table button on the top) — then this bug has nothing to do with Markdown. 

---

Under lab environment and in normal circumstances, we can't seem to reproduce this bug otherwise. If possible could you give things a try with another browser that doesn't have any privacy hardening etc features and send us a screengrab of you creating the table from scratch, so we can see the each and every step you're taking from the moment you create the table to the moment you experience the error? This way perhaps we can figure out what's causing this. 

Otherwise, browser hardening etc break hundreds of browser features that which may or may not be necessary for a rich document editor to function as expected. Afterall these are spec-compliant web-features you're turning off to 'harden' the browser, and needless to say they can break a million things, and we cannot possibly test our document editor against browser configurations that make the browser essentially non-spec-compliant. 

---

Hoping these make sense! 

Looking forward to hearing from you, regarding whether if this was indeed a "markdown" related issue, or a Cryptee Table bug, as well as some steps / video from a standard browser so we can assist you better and fix this up right away.

Best,

John

**Comment by ghost** [comment]
> And if you created this table using Cryptee (by pressing the table button on the top) — then this bug has nothing to do with Markdown.

Thank you, clarified, I did create these charts in cryptee.

>Under lab environment and in normal circumstances, we can't seem to reproduce this bug otherwise. If possible could you give things a try with another browser that doesn't have any privacy hardening etc features and send us a screengrab of you creating the table from scratch, so we can see the each and every step you're taking from the moment you create the table to the moment you experience the error? This way perhaps we can figure out what's causing this.

I have been using both non hardened and vanilla clients on android, this recording below on another issue uses vanilla Chromium.

https://github.com/cryptee/web-client/issues/169#issuecomment-1221505526

I have installed vanilla Firefox and Chromium on Fedora non flatpak to do more testing.

**Comment by ghost** [comment]
So replicating these glitches are really hard. I have managed to glitch out a chart on Desktop Firefox (non webapp) which replicated itself via sync everywhere basically. I don't know how I did it. Usual character, backspace and return spam. it is present in Brave and Chromium webapp on desktop, as well as vanilla Firefox and Chromium on Android. It seems to be an universal issue.

Desktop:
![Screenshot from 2022-08-22 12-19-57](https://user-images.githubusercontent.com/94188674/185905130-97d408cb-f3a9-4c20-93dc-965364a086e6.png)

Android Chromium:
![Screenshot_20220822-121938_Chromium](https://user-images.githubusercontent.com/94188674/185905219-f808094d-e17f-4bbc-a090-02df20634eea.png)
