### ISSUE TITLE
[Feature] Tor Hidden Service (.onion)

### ISSUE THREAD

**Issue by TheUndeserving** [cryptee/web-client#167]
Can there be an .onion site for Cryptee to sign up, access and pay with to make that process a bit more anonymous?

**Comment by johnozbay** [comment]
Hi there! 👋🏻

At the moment we don't have any plans on adding a .onion service, simply because we're receiving unbelievably high amounts of spam and bot traffic over Tor. People try to create thousands of accounts, merge them and store large amounts of data using our free tiers. 

Sadly, while I'm a huge fan and believer in Tor, at the moment having a dedicated tor service would be an incredibly challenging cost for us to bear due to the absurd amounts of bots/spam we receive. 

---

At the moment, our we allow Tor traffic to Cryptee via clearnet however. BUT every now and then, some nodes start sending stupendous amounts of bots/spam traffic our way, so our security blocks / suspends those nodes temporarily. And if you try to access Cryptee via Tor using one of these nodes during a high-bandwidth spam season like the one I described, then you would be consequently blocked access for a while as well. 

---

We also have a security system in place that checks to see if your account is accessed from different IP addresses too quickly (i.e. One moment from US next moment from Algeria next moment from Russia etc) and temporarily blocks accounts to make sure nobody can maliciously access your account. And sometimes this conflicts with Tor, since... ya know Tor is Tor.  

---
 
For now I'm going to close the issue, but in the future, when we have more resources to combat bots and spam on Tor network, we may revisit this again. 

Hoping this makes sense and helps!

Best,

J
