### ISSUE TITLE
Uploading multiple photos hangs

### ISSUE THREAD

**Issue by paulhovey** [cryptee/web-client#17]
Using Windows 10, firefox v67, latest version of cryptee.

I created an album and tried uploading a handful of pictures to it, and the upload process would constantly hang in various spots.  It did not seem to be any file corruption problem, because I could reload cryptee and upload the hung files individually and then they would upload successfully.  The console didn't display any errors or helpful messages other than not to do anything with the console :)

If I can get you more information somehow, let me know!

![cryptee upload error](https://user-images.githubusercontent.com/635145/60627877-324c1880-9db5-11e9-81b2-0a6bd3754769.PNG)

**Comment by johnozbay** [comment]
Hey Paul! 👋🏻
Thanks for shooting this my way. 

I've just ran a test upload with an exact replicate of your setup and it seems to go through. I'm going to take a bold guess and say that it's likely related to content blockers or extensions or other setup specific-bug. 🕷

So I'm going to need a lot more specific information from you (like extensions, their settings, if you're on a VPN, a corporate firewall, etc but also the full versions of your OS, browser etc) – If you wouldn't mind, could you reach out from : https://crypt.ee/help and that way I can help you debug the issue in private.

I'm using github more for service-wide, cross-platform and non-user-specific bugs, and our helpdesk for more user-specific ones. So in the interest of keeping things clean and tidy here, I'm going to close the issue here, and we can continue there in private. 

// in the meantime, if possible could you give things a try with another browser or with extensions etc all turned off so we can try and eliminate this possibility entirely.

Looking forward to hearing from you. 
Best, 
J
