### ISSUE TITLE
[Change] Encryption key input fields don't have the same id/name

### ISSUE THREAD

**Issue by eugenesvk** [cryptee/web-client#170]
**Is your feature request related to a problem? Please describe.**
Encryption key field names differ during **sign up** and **login**, making it more cumbersome than necessary to use auto-fill software like Bitwarden (you have to rename the field for the auto-fill to work)

**Describe the solution you'd like**
Rename both fields to have matching names, e.g. `id="key"`
It would also be greate to actually display the name so you don't have to use page inspector to find it 

**Additional context**

During **sign up** the field name for entering a new encryption key is named
`id="key"`. To avoid copy&pasting incorrect info there, I first create a Bitwarden (password manager) field with the same name, generate the key and store it there, then auto-fill it in the field. It works fine

However, during **login** the field name for entering an existing encryption key is named
`id="key-input"`, so my previously created autofill fails: it inserts a password instead. Now I have to manually rename the field in Bitwarden from `key` to `key-input` to make it work again

**Comment by pablo03v** [comment]
Hey Eugen, I haven't the used id's yet to autofill passwords, but I use Bitwarden every day using url's and it works like a charm for me with cryptee too. I have one entry for the login and one for the key. 

The login password has the url https://crypt.ee/login and the key has the urls https://crypt.ee/photos and https://crypt.ee/docs. Maybe that already helps you personally :)

I'm sure @johnozbay can explain further why the fields have different id's or might even consider changing it, if possible.

Great Day,
Pablo

**Comment by johnozbay** [comment]
Hi there! 
Thanks a lot for filing this! 🙏🏻

This sentence : 
> However, during login the field name for entering an existing encryption key is named `id="key-input"`, so my previously created autofill fails: it inserts a password instead.

leads me to think that Bitwarden in fact doesn't _only_ look at the ID fields when _populating_ the inputs. (Perhaps it does while _saving_ initially — more on this below) Because if it were indeed checking the ID field, why would it populate the `password` into the `key-input` ? 

According to [this documentation](https://bitwarden.com/help/custom-fields/), Bitwarden prefers inputs in this order : 
>HTML form element's id attribute.
HTML form element's name attribute.
HTML form element's aria-label attribute.
HTML form element's placeholder attribute.

But I'm still not 100% convinced this is indeed the case while populating them. 
— also it very specifically uses the term "html form element" (and we don't have a `<form>` element)

---

If we do change the `id` from `key` to `key-input` or vice versa, while it would fix the signup/signin flow for all new users — based on this report and what I'm understanding from Bitwarden's documentation, it would also break the signin flow for hundreds of thousands of existing users using Bitwarden and may have created custom fields to save their keys, as suddenly the encryption key input field which Bitwarden's looking for would have an entirely new ID. 

As for the solution, instead of changing the IDs, we can add `name="encryption-key"` and I think that should remedy the problem. (at least according to Bitwarden's documentation) That way if anyone created custom fields using `id="key"` or `id="key-input"` it would continue to work since fields would now have the same name, and for newer signups it would (should) address the problem.  

Does this make sense / sound reasonable to you both? We don't use Bitwarden so we can only have limited UX tests, and would love to know what you think about this.

---

Also a little bit of a background. We used to have a legacy bot protection system in place to stop bot-signups. Basically people were creating thousands of bot accounts then combining them to get more free storage. So we designed the signup page in a way that it used to change input ids etc randomly. (Banks, Facebook etc all use this method btw, it's a quite common trick) Later down the line, we started using more advanced techniques to combat bot signups, so either myself or someone on the team must have used `id="key"` and moved on. 

---

Let me know if you two think this is a reasonable fix, and I'll have this pushed out with the next update once it passes our automated tests.

Thanks a lot for your help and time! 

Best,

J

**Comment by pablo03v** [comment]
I love your long answers, John. Always really helpful and profound 😍

Yes, it indeed makes sense to me.

**Comment by johnozbay** [comment]
Happy to hear I can be of help and bring some clarity @pabloscloud! 🙏🏻
I'll wait to hear from @eugenesvk — and if this sounds good as well, we'll go ahead and release this fix. (and hope that it actually does fix the issue hah 🤞🏻)

**Comment by johnozbay** [comment]
All our tests seemed to indicate we managed to fix this in 86a5508 — so we released it! 

Let us know if you guys continue to experience issues related to this, and we'll take another look at what we can do to address these types of pass manager problems. 

Thank you so much for your help and patience! 

All the best,

J

**Comment by eugenesvk** [comment]
Just wanted to confirm that your solution works fine, thanks for a prompt fix!

Was just wondering whether it'd be possible to streamline it even further and allow entering all 3 fields together: `id`, `password`, `encryption key` so as to avoid having to press the auto-fill option twice?

**Comment by pablo03v** [comment]
This would indeed be nice, but I don’t think it is with Bitwarden at least.
