### ISSUE TITLE
Support secondary method of installation, without PWAs

### ISSUE THREAD

**Issue by Sajo8** [cryptee/web-client#18]
Hey! So right now Cryptee can only be installed on desktops if you use Chrome, or light-modified Chromium variants. Popular browsers such as Firefox and Vivaldi (heavily modified chromium-base browser) do not support PWAs as of yet. I look forward to their implementation and I definitely think PWAs are the way to go, but for right now there should be another way to access Cryptee aside from using the web version, or installing Chrome(-ium) to install Cryptee.

**Comment by johnozbay** [comment]
Hi there! 👋🏻

So that I can understand your use case a bit better – what would be the differentiating benefit / specific use case for an installable desktop native or packaged app over the current web-version? Because currently, you can use Cryptee offline, in any browser that supports service workers – incl. Firefox – without 'installing' it. 

In general, the current state of Cryptee on desktops is no different (if not better) than Google Docs or Google Photos. In the sense that you can use Cryptee in every modern browser, and distinctively from Google Docs or Photos, you can install Cryptee in desktops if you're okay with using Chromium-flavored browsers for the time being or use it offline in-browser due to the fact that it's built using service workers.

An installable / native / packaged app is particularly challenging, especially because it would need to be developed for Mac, Win and Linux separately, and to cover all these platforms, the best candidate on the market right now would be Electron, which is also built on top of Chromium. 😔

So with all this in mind, I'd love to know what the specific benefits would be for your use case, so that I can understand the need better, and perhaps build a better tailored solution towards these. Otherwise, unfortunately this will need to wait until Firefox adds PWA support to desktops as well, or until there's a mature Gecko or WebKit flavored cross-platform electron alternative. (Btw I'm closely following and internally testing [DeskGap](https://github.com/patr0nus/DeskGap/) for this exact purpose and hopefully once it's a bit more mature I might end up using it for Cryptee's desktop versions)

Hoping these make sense ✌🏻
Looking forward to hearing your thoughts! 

All the best,

John

**Comment by Sajo8** [comment]
Hey! Sorry for the late reply.

I'm completely onboard with using a PWA everywhere, it makes it extremely easy for you, the developer, and it's quite easy to install for the end-user as well.  
However, the main drawback is that some browsers have not yet implemented PWA support, meaning I can't install it on my computer, which feels "better" than using it in a web browser, lol. Firefox has, however, implemented it on their android app (maybe iOS, too) so I expect they will add it to the desktop version.. _sometime_.

Right now, though, I also don't think it's worth the effort to create a separate desktop app with Electron, although DeskGap seems very exciting.

I guess given the challenges associated with making a separate desktop app and the current state of these cross-platform frameworks, the only answer is to wait or use it in a browser -  or keep a chromium-flavored browser installed. I'll close this issue then, thank you for your time!
