### ISSUE TITLE
[Bug] Ctrl + browser zoom hides right panel

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#187]
**Describe the bug**
Sometimes when sitting far from my monitor I use control+ keyboard shortcut to zoom the PWA but when you do, the panel of buttons on the right are hidden. (Last I checked)

**Expected behavior**
The panel stays visible and I can see UI elements and read without changing the font size

 **System Information (please complete the following information):**
 - Device: PC
 - OS: Fedora
 - Browser: De-googled Chromium
 - Browser Version [latest flatpak from flathub]
 - Browser Extensions / Add-ons / Content/Ad-Blockers:  none of these settings are on.
 - Do you have any DNS-based content/ad-blockers? [Yes]

**Comment by johnozbay** [comment]
Hi there! 

Could you post a screenshot please? 

As far as I can see in Mac and Windows in Chrome this isn't a problem (see screenshot below), so the only way we can work on this is if you can show us what's actually broken.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/611338/216842273-809b172a-ee71-48c8-a2c9-97a3944a90ab.png">

If this feature works in one Chromium browser, but not the other (or one system but not the other i.e. depending on your screen's resolution or Linux's environment config etc) I'm afraid I'll have to eliminate this as a browser-specific bug, rather than a Cryptee bug. 

Please post a screenshot and we can continue the conversation from there ✌🏻

Thanks again,

Best,

J

**Comment by S7venLights** [comment]
This issue seems to have come right, I can zoom without issue
