### ISSUE TITLE
[Bug] Offline Docs not loading offline in Brave (Android)

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#190]
**Describe the bug**
This seems to happen intermittently (perhaps after updating the browser). If there һаѕո't been a first launch of cryptee docs after a phone restart, then if I open Cryptee in an offline state; even notes that have been saved for offline access don't load. 
It simply stays loading infinitely.
If Cryptee has been opened once online then this issue doesn't present. 

**System Information**
 - Device: [Mobile]
 - OS: [Android 12]
Browser: Brave Browser
Browser Version [latest off Gthub updates often]
Browser Extensions / Add-ons / Content/Ad-Blockers: Edit: [Had braves default standard tarcker and fingerprint settings on, have now disabled and will keep testing]
Do you have any DNS-based content/ad-blockers? Not sure, I use random DNSCrypt servers changes automatically 4of10 have filtering.
Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there! 

Judging by your other bug reports, I'm going to take a guess and say that you having connectivity / storage issues on your mobile device with Brave isn't a coincidence, and this is actually related to #185. Please follow the steps I wrote there, and give things a try, and if this still doesn't address the problem, if possible give things a try with another browser to see if this connectivity issue is about your android device, your network, or your browser itself. Due to the vast variety of android devices, vendor/os flavors, browsers and extensions and dns configurations we cannot help with issues like without extremely specific information. 

We have our issue templates for a reason. i.e. how can I know if you're trying to use Android 5 or Android 12? You didn't mention it. I cannot know if your Brave browser is from 8 years ago or from this week if you don't write the version. 

I'm deeply appreciate of the fact that you're filing these issues, but please follow our issue guidelines or we cannot help you, it won't improve Cryptee, it will cost you and us time, and result in one or all of us getting frustrated. 

Hoping this makes sense and helps,

J

**Comment by S7venLights** [comment]
Have updated info and will keep testing.

**Comment by S7venLights** [comment]
This issue can stay closed, seems to work fine
