### ISSUE TITLE
[Change] language direction not available on iOS pwa

### ISSUE THREAD

**Issue by asto-ms** [cryptee/web-client#198]
Language direction for Right to Left languages such as Arabic and Farsi is not available on iOS pwa version of the application, while it's available and working perfectly on Chrome's pwa on Mac.

ios pwa
![IMG_2615](https://github.com/cryptee/web-client/assets/143348971/9a6d4003-60f0-4257-ac2d-b6a94950fe57)

Chrome pwa
<img width="227" alt="Screenshot 2023-09-17 at 1 28 07 PM" src="https://github.com/cryptee/web-client/assets/143348971/5d75220e-5de5-4746-ae25-48db21ee57b5">

**Comment by johnozbay** [comment]
Hi there 👋🏻

Many thanks for filing this! 

At some point (if my memory serves me well, around iOS 14 or 15) we had to disable this feature on mobile devices due to some strange iOS text selection bug. 🤦🏻‍♂️ It seems like this is now fixed in iOS 16/17, so we can safely re-enable this. 

We've re-enabled this feature / added it back in the alpha version, and it should work as expected once it's out. 

That being said, if you experience any strange RTL / text-selection bugs while using, please let us know. We could really use some of your feedback with day-to-day RTL / text-selection / direction related issues. The more bug reports the quicker we can collect enough feedback to fix these types of issues ✌🏻

The alpha version and this issue is linked to our internal issue/release tracker now.
So once the update with this fix is out (should be latest in a few days), this issue will be closed automatically, and you'll get a notification!

Thank you so much for filing this, your help and patience!

All the very best from Northern Europe, 

J
