### ISSUE TITLE
Subfolders?

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#2]
I would love to have subfolders!

**Comment by johnozbay** [comment]
Hey Ryan! 
First off - Thank you so much for checking out Cryptee, 
filing the first issue on Github, and your support overall! 🎉
Means a lot! 
 
About nested folders. Oh how I would love that too! 😞

As of today / as it stands, [this isn't possible due to a very technical reason](https://crypt.ee/help?article=can-i-have-folders-within-folders).

**TLDR;** due to real-time sync, client-side encryption, and performance reasons, titles of documents and folders are grouped and encrypted together - then this group is sync'ed. After lots of cross-device real-time testing, I've found that allowing nested folders occasionally caused real-time sync'ing errors with file & folder names, and resulting in some titles to be lost forever if you're on a bad network and move things around quickly - quite unacceptable, so I decided not to have this feature right away.

That being said, this is soon going to change. 🎉
For the past two weeks I've been re-tooling the entirety of Cryptee Docs to use individually encrypted titles instead of grouped. This will cause older mobile devices (mostly circa 2013) to run Cryptee quite slowly, but recent devices will run it 10x faster. I think it's a reasonable compromise. 😎

This upcoming update will lay the groundwork for nested folders to exist in the future.
Actual implementation of nested folders will take slightly longer of course, since there's also cross-device UI / UX changes to take into consideration, but it will eventually be possible. 

It's getting there! One step at a time! I'm quite excited! 🍾🥂

All the very best from Northern Europe ~

**Comment by johnozbay** [comment]
Just a quick update on this. b33a7c3498c628847693b2750342060bc06d4859 starts encrypting titles individually. 
So this lays the groundwork for nested folders to exist in the future. 

Here's to all the future updates 🥂

**Comment by ryanpcmcquen** [comment]
@johnozbay, I am excited to try all the new goodies. Thanks!

**Comment by johnozbay** [comment]
@ryanpcmcquen  – Just to keep this thread up-to date. I'm making crazy amounts of progress towards making this happen. This upcoming update will change the way files & folders work significantly, all while maintaining 100% backwards compatibility, speed loading times up immensely, and prepare Docs to make sub-folders happen. 

(I'd say I'm 60% there and another 40% work left to make kick-ass encrypted nested-folders happen) 😎

**Comment by ronakshah01** [comment]
I can also chime in and say this would be huge for me.

Thanks again!

**Comment by johnozbay** [comment]
Hello everyone! 

Just wanted to give another update on this. 
018fcf1516d530bdba1b5d45cd58a3d048761b6f changes the way Docs / Files & Folders work. Formerly files had to belong to a folder, and folders had to belong to a root, this isn't the case anymore. So things are much more object-oriented now. 

As an awesome side effect of this, you can now _right click_ on any doc, file or folder, anywhere (including search results) and do selections / take actions. This update also changes the way files are moved between folders, since now that things are more modular, it was time this got an update too. 

Instead of a cheesy drag and drop, you can now use the cutting edge technology invented in the 90's = click and choose. Turns out many of Cryptee's users have this extension called canvasBlocker, which blocks access to `domRect` / `.getClientRects()` thus making it impossible to detect drags and drops of docs around into folders or worse fucking up with their entire folder tree structure. ~~(and since it's encrypted on their devices, I can't manually remote-fix these either. So it took a whole week of effort and lots of beta releases & tests to create chunks and chunks of code that would help self-repair/auto-repair their libraries on their devices.) [let's just say I made this rebellious act of treason for a reason](https://github.com/johnozbay/canvas-block-detector)~~ – anyway 

So I'd say if I had to give a progress report on this, and use a percentage, it would be somewhere between 65% - 85% now. I still have a bit more work to do before folders can start hanging out with other folders and socialize, but we're getting there. 

![folders](https://media.giphy.com/media/yy1RLVzuSAiFa/giphy.gif)

**Comment by johnozbay** [comment]
f492412f677b6b773f12d12a4fda05ec41d40d1b 
– allows files and folders to live side by side in the user interface, 
– brings files & folders together into the search results, 
– makes it so that some filenames / docnames decrypt after a folder opens,

So technically there's one last thing left to do now, that's to build the folder-tree-structure, and make tweaks to the UI to make it possible to go from folder to folder, and keep going back!

**Comment by johnozbay** [comment]
Files can now be attached, and images can be embedded into documents from the side panel.

https://github.com/cryptee/web-client/commit/1bf4ea43edc1b7916f1fd71faf2c02f17e141c24 Makes things even more independent, while I work on the nesting UI and functions.

**Comment by elevatorz89** [comment]
Great! Can't wait till nesting folders come out!

**Comment by johnozbay** [comment]
Hey folks! 👋🏻

Words cannot describe how happy I am to be able to post this GIF here after more than a year spent developing this feature. 

![subfolders](https://user-images.githubusercontent.com/611338/69631045-2a3b9080-1056-11ea-9865-7cd5fbc4c75a.gif)

We had to slowly change, re-write, and improve hundreds of things, both on backend and front-end to make this happen during this past year. Therefore, it's backwards incompatible, and there are still 10 - 20 minor bugs we'll need to fix before we can push this out even to [https://beta.crypt.ee](https://beta.crypt.ee) – so currently we're doing a big internal test – 

Just wanted to stop by to say it's coming very very soon. In fact, there's a very high chance the next release will have this feature, as well as a quick, new, one-click "new subfolder" button as you can see in the GIF, and as you'd expect, the ability to move folders around, move files into subfolders etc. 🎉 

We're aiming to ship before the end of December,
and as usual all feedback is welcome! 

Many thanks for your patience on this 🙏🏻
Will keep this thread updated, and close it once the feature is shipped. 

🍷🎉

**Comment by elevatorz89** [comment]
Curious, do subfolders support individual offline status? If so, they would download everything within them, including within other folders, right?
(also can't wait for this update, it will be delightful) 

![giphy](https://user-images.githubusercontent.com/53919102/70398296-f5312580-19e7-11ea-965c-1eb5621e585a.gif)

**Comment by johnozbay** [comment]
@PreciselyPixels 10 points for the gif and excellent questions!  🎉

This and ghosting parent folders are the two things taking so long btw!

1) Subfolders are like every other folder, so you can right-click on them individually to make them available offline (or make them online only). The tricky part here, as you've also noticed is to figure out whether if they should inherit their offline status from the parent or not. 

And logically, they should. So if you make a parent available offline, all children should become available offline too. However technically things are a bit more difficult than that. Especially for high-storage account tiers. What if the parent folder is massive (say 1TB) and would blast your entire phone's storage. Where should it stop? Or for example if you're on a mobile network it should warn you etc. Tons of complications here. 

So the answer is, yes, they will inherit the offline status from the parent, but you'll be able to override them manually if you wish. 👍🏻

2) Similarly, with ghosting, for the time being, I'm going to only allow ghosting folders without subfolders. The logic for ghosting is so complicated that in order not to wreck havoc, I need to disable subfolders for now. (And I think in another month or two I'll add ghosting for folders with subfolders as well) – the difficulty is backwards compatibility. Updating the client side code & server side code isn't good enough in case of ghost folders. 

Since people have folders ghosted pre-subfolders-update, and these specific folders will need to be summoned with pre-subfolder code, but folders ghosted post-subfolder update will need to be summoned with post-subfolder update code. (It's going to have to be a slooooow transition, and could take many months if some users won't summon their pre-subfolder ghosts for months) 👻

So lots and lots of edge cases and added complexities due to all these cryptee-specific features. Will ping this thread once it's ready for beta, so you can test it out and let me know if you like / dislike the ways subfolders behave in certain scenarios. – coming soon 🤓

**Comment by johnozbay** [comment]
Hey everyone! 
I can really use some input!
 
I've got a few edge case scenarios that's essentially holding this whole thing back. 
So I figured I'll ask this here as well. 

Here is the situation: 

📁 Projects
––– 📁 Project A
––– 📁 Project B

## Question 1) Should you be able to ghost a subfolder (Project A)?
If yes what should happen when : 

Step a) You ghost the "Project A" folder
Step b) Two months later, you delete "Projects" folder.
Step c) Three months later, you summon "Project A" back again.

### Question 1a) What should happen when you summon a folder, and its parent no longer exists? Should the subfolder arrive in the root directory?

Also : 

Step a) You ghost "Project A" folder
Step b) Two months later, you ghost "Projects" folder.
Step c) Three months later, you summon "Project A" back again.

### Question 1b) What should happen when you summon a folder, and its parent is ghosted? Should the summoned subfolder arrive in the root directory?

&nbsp;

## Question 2) Should you be able to archive a subfolder (Project A)?
If yes what should happen when : 

Step a) You archive the "Project A" folder
Step b) Two months later, you delete "Projects" folder.
Step c) Three months later, you un-archive "Project A".

### Question 2a) What should happen when you unarchive a folder, and its parent doesn't exist anymore? Should this unarchived subfolder arrive in the root directory?

Also : 

Step a) You archive "Project A" folder
Step b) Two months later, you ghost "Projects" folder.
Step c) Three months later, you unarchive "Project A" back again.

### Question 2b) What should happen when you unarchive a folder, and its parent is ghosted? Should this unarchived subfolder arrive in the root directory?

&nbsp;

–––– I'm thinking of allowing both archiving & ghosting subfolders, and if their parents are missing for some reason, they would appear in the root directory when they're summoned or unarchived.

What do you think?

**Comment by bobleeSwagger2** [comment]
IMHO conventional wisdom & practical norms are that if you delete a parent folder, all subs go bye bye as well, "ghosted" or not. Now, if a parent folder is ghosted, it, along with all subs should be hidden. Again, just my opinions. 
These nested folder ideas are great but I'm still needing mobile share targets ASAP Mr. Ozbay. Thanks :)

**Comment by johnozbay** [comment]
@bobleeSwagger2 unfortunately, conventional wisdom fails when encryption & hashing involved. When you ghost a folder, it's removed from your account for deniability so you can't take any action on them, and they're hashed in a way that Cryptee / servers don't know whether if you have a ghost folder or not. And their foldernames/filepaths are encrypted on your device, so servers can't tell whether if they're subfolders or not. You can read more about how ghosts work [here](https://github.com/cryptee/web-client/issues/33#issuecomment-563244601).

So when you delete a parent folder, Cryptee won't know whether if it has ghosted subfolders or not. Simply because ghosted subfolders are no longer in that parent folder. (it's as if they're moved out of your account) The parent will simply be a folder, with no subfolders inside. 

The issue here is when you summon/bring back a folder, you decrypt their foldername & filepaths = they will still have their paths referencing to "root/parent/subfolder" while being restored, (but now right when you're about to restore you've discovered the parent isn't there anymore) hence my questions about what should happen. 

> These nested folder ideas are great but I'm still needing mobile share targets ASAP Mr. Ozbay. 

Let's stay on topic. I've explained why share targets are taking long [here](https://github.com/cryptee/web-client/issues/27).

**Comment by bobleeSwagger2** [comment]
@johnozbay 
You explain things very well regarding encryption & all that. With that, I think your proposed solution is good & I give it a thumbs up.
Far as changing the topic, I'm sorry. I've been shopping for a new arctic ghillie suit & wanted to share them to Cryptee. Please forgive me Mr Ozbay & keep up the good work

**Comment by elevatorz89** [comment]
IMO, yes, ghosted subfolders could be kept separate from actual folders in the event of 

_You delete a folder, then realize a ghost folder within has files and stuff you actually do need._

So in cases like that which (I imagine) would be rather common for ghosting subs, dropping it in the root of the file tree seems like a safe bet. I could see ghosting subfolders work like that. Though, archiving them... Hmm

**Comment by johnozbay** [comment]
After thinking deeply about the user experience for almost 10 days now, here's our conclusion. 

**1 )** It should be possible to ghost a subfolder. 

**1a & 1b)** If parent(s) exist(s), summoned (sub)folder arriving into its original nested path could be super confusing and potentially dangerous from a user experience standpoint. Here's why. 

When a (sub)folder is summoned, if it's nested 5 folders deep, users will have no visual clue that it did indeed successfully arrive into its original place, 5 folders deep. Checking that it indeed did arrive / accessing it would require navigating to that folder, but a user may not remember its original location after months, if it's 5 folders deep, and could cause issues down the line. 

**Example scenario**, it's year 2022, you're a lawyer : 

📁 Clients
📁 Cases
–– 📁 2018
–– 📁 2019
––––– 📁 John Doe
––––– 📁 Jane Doe 
–– 📁 2021
–– 📁 2022

You summon a folder by its name "Jane Doe", because that's the client name you need to bring up, and access again. But you don't remember which year it was from. If it's automatically placed into 2019, to access it you'd need to sift through all the other years to find it. This gets worse if you've got months in the folder tree as well as years. 

Secondly, this would also require having to decrypt potentially hundreds of files' folder paths which are in the tree of subfolders, and check to see if any one of the folders in those 5 levels don't exist anymore. So each summon operation could take ages if the folder you ghosted has 1000s of files in it. 

**Our solution so far:**
In the interest of keeping the privacy & security of ghost folders as simple as possible, we're thinking of making this so that all ghosted folders are automatically moved to root once summoned back, regardless if their parents are ghosted/deleted or not. This way users can access them right away, and this doesn't require decrypting 1000s of filepaths to check if any folders are missing. So it's more mobile-friendly, it's the least time consuming, and the most convenient option. If a user remembers where the folder needs to go, and wishes to restore the folder to its original location, it would be a simple "right click" > "move" away. –– generally speaking, we think it's better to craft this feature for those who need the most privacy & deniability = reduce complexity, at the cost of making things a bit less convenient if you need to move a summoned folder back to its original place. 

Similarly, 

**2 )** You should be able to archive a subfolder.
**2a & 2b)** When you un-archive a (sub)folder, it will appear in the root as a regular directory, regardless if its parent is ghosted or archived or deleted. 

We're in the process of contacting some friends and trusted users who are lawyers, psychologists, peace workers etc. who rely on ghost folders heavily, to ask for their opinion on this. As programmers we don't want to make a decision that could hurt those using this feature in different privacy-critical scenarios. 

In the meantime, in the interest of beta-testing the core functionality of subfolders, we'll be releasing this to beta very soon, and we'll use the 'always-arrives-to-root-folder' solution for the beta. (at least until we know what's better.)

Please reach out with thoughts / ideas here in the meantime. Once we have a clear path on how this should work from a privacy-standpoint, we will release sub-folders to public.

––

@bobleeSwagger2 nothing to forgive no worries at all! ✌🏻 A new arctic ghillie suit sounds awesome tho! 🥶

**Comment by sith-on-mars** [comment]
Looking great! Any progress yet? You said that you aimed to ship before end of December.

**Comment by johnozbay** [comment]
Alright folks! The day is finally here! 🎉
Head over to https://beta.crypt.ee and play around with subfolders!! 

Caveats : 
1) Subfolders you've created in BETA will appear as regular folders in the LIVE version, but simply appear under all other folders (how's that for backwards compatibility 😎)

2) We've fixed hundreds of UI / UX bugs, but there may still be many, please post them here as you see 'em. 

3) Ideally we'd like to release this for public before the end of January, if not faster. So if possible, please play around and test as thoroughly as you can. 

4) There's still no way to upload folders with subfolders from your computer by drag & dropping. Support for this will come in the near future. (For backwards compatibility we don't want to move too fast and break things altogether, so we're porting these over one-by-one)

Many million thanks for all your patience! 
(esp. @ryanpcmcquen for now being the author of the oldest issue!)

**Comment by ghost** [comment]
@johnozbay I waited so long for this feature and now its finally there. This update is amazing!🙌

One thing I noticed:
I can upload files in a folder, but its no possible for me to upload files to a subfolder. The "Upload a file" -  Button isn't working for me. Uploading files via Drag&Drop works perfectly.

Hope this helps

EDIT: Fixed! Works perfectly now.

**Comment by Visual-Notes** [comment]
I can confirm that issue. Inside a subfolder, clicking the Upload Icon doesn't do anything. 
Hasn't this been tested so far?

**Comment by johnozbay** [comment]
@SteffB44 – Thank you so much for this! 🙏🏻 
Pushed out an update to beta, and this bug should be fixed now. 

@africanforest – It's a _beta_, unexpected bugs happen. 

![](https://media.giphy.com/media/STTGp7oIbnibm/giphy.gif)

As usual, please keep them bugs coming everyone! 
Updating thousands of different things due to sub-folders, stuff could break. 
![](https://media.giphy.com/media/2KAGlmkPywhZS/giphy-downsized.gif)

**Comment by elevatorz89** [comment]
Not 100% sure if this is a cryptee-wide issue, but I've found that occasionally, uploaded files don't appear half the time untill you go back and reenter the sub-folder. Not too much of an annoyance, but it is just a nitpick.

**Comment by PreciselyPixels** [comment]
> Not 100% sure if this is a cryptee-wide issue, but I've found that occasionally, uploaded files don't appear half the time untill you go back and reenter the sub-folder. Not too much of an annoyance, but it is just a nitpick.

**Comment by Visual-Notes** [comment]
@johnozbay  - You're right, sorry for my statement.

**Comment by johnozbay** [comment]
@africanforest No worries at all ✌🏻Thank you so much for the helping hand in general! 🙏🏻 I just don't want to set false expectations for the beta hahaha it may break every now and then. 🙄

@PreciselyPixels – Good catch! We've noticed this bug too, and looking into this. 🦟

It seems like a sync problem. 
In short, when you upload a file, instead of adding the filename from the device memory to the UI directly, the filename is first encrypted, sync'ed up to server, then server sends the client an update like : "hey there's a new file", finally the client decrypts filename and displays it in the UI. 

This monstrous inefficiency is to ensure that all online devices get updates at the same time. For example if you have your desktop, iPad and phone open at the same time, they will all show the file appear simultaneously. 

– In the past this wasn't the case, after the upload, the filename was added to UI from memory, without waiting for the server response. But we started getting super strange sync errors from servers. Turned out to be a super strange race sync condition caused by user-behavior & design.

Since the file(name)s showed up in the UI right away from memory, some users on slow networks tried to select & rename files immediately after uploading them, before the filename was encrypted & saved to server. And this caused servers to freak out and get confused about what to sync to other online devices, causing other online devices to never ever receive that file until those devices' offline caches were reset. //// encrypted realtime sync is a nightmare btw 😩

TDLR; So far it's looking like folders are not getting these socket updates from servers right away, and only displaying new files when you reload the folders. [ and we likely broke this while preparing for the subfolders update to make things backwards compatible with the current live/production release, so this may be broken in the production for some users too, and will be fixed with this release. ]

And since this is GitHub, I'll go further into curious technical details here 🤓 : 

Reason why this turned out to be a bit harder to fix is because, we didn't want to attach too many individual socket listeners for each folder. (Because what if you have a 10,000 folders? We cannot attach 10,000 socket listeners. There should just be 1, and that socket should handle all updates to folders etc.)

**Comment by johnozbay** [comment]
@PreciselyPixels Just pushed out another update to beta and I think this seems to fix the sync issue where the new document isn't appearing in the sub folders. (+ as a side-bonus this fixed an issue where the folder's sort was just casually resetting itself)

– also fixes search results suddenly disappearing/reappearing if a file is in a subfolder and a few other search bugs like this one.
 
– Added a server-assisted batch deletion. (for example if a folder has 10 subfolders, and each subfolder have 10 subfolders, and each sub-subs have 10 files, this would mean when you delete the root folder, you're actually deleting 1000 files, and triggering 1000s of deletes shouldn't be handled on client-side one-by-one. Say for example if your network drops mid-deletion, half the stuff wouldn't be deleted and a whole host of other issues) – so instead now the client side passes on the ID#s of files that will be deleted to server, and server handles all this in batch. (long story short, single-files may take 0.5s - 1s longer to delete due to this roundtrip, but if you're deleting a whole folder with lots of files (and subfolders with files), then you're saving minutes of waiting time. 

Anyhow, give this a try and let me know folks ✌🏻

**Comment by elevatorz89** [comment]
Not sure if this is an intended thing (or non-implemented), but I cannot move anything into any subfolder.

**Comment by Visual-Notes** [comment]
@PreciselyPixels I can't reproduce this with the latest beta. You must move files and folders using the context menu. Select "Move to..." and choose the main folder and then the subfolder you want to move the file to. Of course it would be great if this process could be done by drag & drop, at least on the same level...

Actually I also miss the possibility to move a main folder to another one by drag & drop so that it becomes a subfolder. At the moment you can move the main folders to change their position, but not to move one folder into another.

**Comment by africanforest** [comment]
@johnozbay I found a bug concerning the renaming of files inside a folder that contains files and a subfolder.

To reproduce:

1. Create a folder at root level.
2. Open it and create three new documents and one subfolder.
The main folder should now contain the following: 

```
New Document
New Document
New Document
New Folder
```

3. Now rename the files individually to a, b and c. The contents of the folder should now look like this:

```
a
b
c
New Folder
```

4. Open the subfolder "New Folder" and go back again.
5. The result is that the previously renamed files now magically have their old names again:

```
New Document
New Document
New Document
New Folder
```

**Comment by johnozbay** [comment]
@PreciselyPixels I think this is my fault with bad UX design. So that I can make sure UX with this is actually good & clear – In the move folder dialog, you need to double click on the folder name to open it up and to see its subfolders. 📂

So that I can improve this : By any chance did you try single clicking or give up when you didn't see the sub folders there? I think Google Docs' move dialog is a single-click to open. And I might need to find a different design solution to make this clearer. I'll try adding a mini triangle next to the folder name to clarify it can be opened. What do you think? 🤔

@africanforest In the early versions of Cryptee, you were able to move files by drag&dropping them onto folders. 🎉 –– But –– In order to detect overlapping elements / to detect the target element, one needs to determine the position & size of the target element, and it's only possible to do this reliably across all devices & browsers using a browser API called [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect/DOMRect). 

We had this, it was working perfectly, and you could drag/sort/drop files onto folders, then suddenly we started getting tons and tons of complaints from users about how they can't move anything at all. 😩

Turns out, all these users were using a popular privacy browser-extension called [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) which blocks access to `DOMRect API` as well as other APIs to prevent browser fingerprinting. Looks like they do this, because `getClientRects` & `DOMRect` APIs [can be used for browser fingerprinting](http://jcarlosnorte.com/security/2016/03/06/advanced-tor-browser-fingerprinting.html#getclientrects-fingerprinting) and most privacy add-ons block it. 🤦🏻‍♂️

Many members of Cryptee's security&privacy-conscious user-base have this add-on (presumably as well as 10 other add-ons), and the only way left out of this was to remove this feature altogether, and simplify the move feature down to a basic click-based system. 😞

PS – you can still drag & re-order root folders, and this still relies on the same APIs I mentioned. If `DOMRect` is unavailable/blocked, then users only lose the ability to sort things around, but at least they don't lose a critical functionality like moving files around. I'm not sure if I can add this feature back now due to all the backlash it could cause. I hope all this makes sense ✌🏻

**Comment by elevatorz89** [comment]
Yeah, Google docs has a "single click to go deeper" function, guess I'm too used to it. A triangle should ease the confusion quite nicely.

**Comment by johnozbay** [comment]
Pushed out another update to beta! Now selections are single click, like Google Docs, and doesn't feel as strange with this design + there's a caret. Let me know if this feels unintuitive. ✌🏻

In addition, this update also moves more tasks like batch processing to the new api server. (Be it things like used storage / available storage calculation, to document-generation-checking (to ensure correct sync). 
 
So please let me know if you run into any strange bugs, especially in : 
– document from a subfolder not loading, 
– document from a subfolder hangs while loading,
– _offline_ to online sync fails for a document in a subfolder.
– online to _offline_ sync fails, or mistakenly skips sync thinking offline version is up to date.
– attachment from a subfolder fails to load / hangs while loading
– if an attachment from a subfolder is deleted, doesn't accidentally try to load (and correctly shows a deleted warning/icon)

Tons of edge-case scenarios as you can see, but we're almost ready!
Thanks a lot for the patience and help everyone 🙏🏻

**Comment by Visual-Notes** [comment]
I really like the way you can select the folders now! Also the icons are very intuitive, it couldn't be better.

What I notice is that the folders in the selection box are always sorted alphabetically ascending, but in the folder tree you might have your own sorting, which can be confusing when selecting folders for moving files. Couldn't the folder selection box show the same sort order as it exists in the folder tree? I think it would be a relief if both folder sortings were the same.

**Comment by Visual-Notes** [comment]
> We had this, it was working perfectly, and you could drag/sort/drop files onto folders, then suddenly we started getting tons and tons of complaints from users about how they can't move anything at all. 😩
> 
> Turns out, all these users were using a popular privacy browser-extension called [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) which blocks access to `DOMRect API` as well as other APIs to prevent browser fingerprinting. Looks like they do this, because `getClientRects` & `DOMRect` APIs [can be used for browser fingerprinting](http://jcarlosnorte.com/security/2016/03/06/advanced-tor-browser-fingerprinting.html#getclientrects-fingerprinting) and most privacy add-ons block it. 🤦🏻‍♂️

@johnozbay I now understand that you have to make a few sacrifices in terms of comfort for the sake of safety. And with the new improvements in selecting folders, moving files and folders is very easy even without drag&drop!

**Comment by johnozbay** [comment]
> Couldn't the folder selection box show the same sort order as it exists in the folder tree?
It absolutely could – 
That being said when you sort things in folders, files can be sorted A-Z and Oldest - Newest (based on last edited) whereas folders can be sorted A-Z (Because folders don't have a "last-accessed" or "last-edited" meta) Which means, you can only have A-Z or Z-A in the modal. 

Say we add the feature to make it follow the parent folder's sort, and it's Z-A, but you need A, you'd need to scroll all the way down. And adding another reverse sort button would make the interface very crowded.

Following Google Drive's UI here, (they only do A-Z) and I think logically A-Z makes things easy enough to find without having to re-build an entire redundant file-explorer with multiple sorts etc into the move modal. 
What do you think?

> I now understand that you have to make a few sacrifices in terms of comfort for the sake of safety.

Unfortunately. 🤦🏻‍♂️ I can probably write a whole book about how many times I had to make major UI compromises or [build creative workarounds](https://github.com/johnozbay/canvas-block-detector) because a popular privacy add-on shipped a poorly-thought feature (which now serves the exact opposite purpose due to its small scale adoption) and completely broke a major web API.

**Comment by Visual-Notes** [comment]
> Say we add the feature to make it follow the parent folder's sort, and it's Z-A, but you need A, you'd need to scroll all the way down. And adding another reverse sort button would make the interface very crowded.

What I meant was not the sort order of subfolders, but that the sort order of the main folders in the left sidebar could be the same as that of the main folders in the modal.

I think this would make it easier to select folders in the modal. Currently the folders in the modal are always sorted alphabetically ascending. In the left sidebar, however, you will probably have used a custom sort order in most cases, as this is possible and certainly more practical than just an alphabetical one.
If this custom sort order of folders in the left sidebar would also be reflected in the modal, it would certainly make it easier to select main folders in the modal when moving files or folders.

**Comment by Visual-Notes** [comment]
BTW, if you decide to stick with this (IMO very good) one click solution, you should change the text from
`You can double click on folders to navigate to folders inside of them if there is any.`
to
`You can click on folders to navigate to folders inside of them if there is any.`
or
`You can click on folders to navigate to subfolders if any exist.`

**Comment by johnozbay** [comment]
@africanforest Many thanks for this! Good catch! Fixed now, will be available with the next release.
p.s. looking into how the sort would work logically, going to give it a try and see if it looks good with custom orders.

**Comment by elevatorz89** [comment]
I just got an amazing idea. When you click on the top half of a folder, it lists a few of the documents within. What if they were replaced with subfolders?

**Comment by johnozbay** [comment]
That's a great idea @PreciselyPixels ! Let me think about this a little bit. 

Basically, the 3 documents you see in the folder quick-view are the most recently edited 3 documents in that folder. When you're looking for a particular document you've accessed _recently_, there are two ways to think about document hierarchy especially in business uses. 

**First**: "When did I need/use/edit this document? I think it was yesterday?"
–– Recent Documents list allow you to quickly find documents like these, where _time_ is the main concern.
  
**Second**: "Which project (folder) does this document belong? I think it was 'Project X'?" 
–– Folder quick-view allows you to quickly find documents like these, where _project_ is the main concern.

So there are a ton of users who use folder quick-view to access recent documents, instead of the Recent Documents list because of this.

In order for the subfolders to live in the quick-view, we would need a way to decide which 3 subfolders would be displayed there. And folders don't have timestamps like documents do due to a few technical reasons. (main one being, documents are now stored flat, and folders are virtual to allow nesting) So we can't pick the most recent 3 subfolders (or subfolders with the most recent 3 documents that got edited in relation to the parent folder).

So with the current file hierarchy & metadata architecture we could only use subfolder names to pick the 3 sub-folders to display there. And I think that would be strange. If you have 100 subfolders, you'd expect to find all of them there, not just the first 3 or 30 sorted by A-Z etc.

This could technically be a checkbox on a subfolder, like : "display in parent folder's quick-view" and you could add 3 subfolders to quick-view manually for example. But this would complicate the UI & UX immensely. 

So if you/anyone can think of a practical way to make it work with these restrictions in mind, I'd be happy to add this option.

**Comment by johnozbay** [comment]
Party time folks! 🎉
931c35bb0dd3a5339b297b54166671cda58721a0 is now live, and subfolders are available for everyone! 

You can read more about all the other cool features this update comes with (like multi-threaded parallel encryption/decryption) [here](here)!

Thank you all for your patience and helping test this feature! 🙏🏻
Needless to say, please reach out if you run into any further bugs!
