### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Sajo8** [cryptee/web-client#20]
We need a dark mode! Currently the Dark Reader extension i use gives a great experience but it's not 100% perfect so it'd be cool to have a native dark mode

**Comment by johnozbay** [comment]
On the way! 🎉

This turned out to be A LOT more complicated than I initially thought it would be. Particularly for the editor, because it supports exporting for print. 

So for example if you have dark mode, and selected white-text in the editor, what should happen when you go to print? (It's obvious right? Text should turn black.)

Then what should happen, if you have dark mode, and selected black highlighting + white text, and you go to print? If white text turns black, then it would be unreadable over black highlight when printed. So should highlights invert as well? 

This gets worse with colors btw. Light yellow is easily readable over black background, but not white. So should these colors change as well etc. 

Dark mode comes with quite intense complications for the text editor. Especially because it's a rich text editor for _Documents_ (and not Notes like Apple Notes / Evernote etc for example where it's relatively more acceptable to have less color / style options)

I'm looking into how all this could be achieved without wrecking havoc into the editor, pdf and print functions basically. Sadly physical papers we use don't support dark mode, and business users who use PDF and print features would flood the helpdesk with emails and messages if I push this feature out without thinking about all the edge cases. 😫

**Comment by paulhovey** [comment]
Oh man, I didn't know I needed a dark mode until now!

Would it be acceptable to have the "Print" functionality export a pdf and not pull up the system's print dialog?  I'm thinking that could be a "Print Preview" sorta functionality, so that if you were in dark mode you could see any discrepancies that may arise?

I would think any unformatted text would invert in dark mode when printed/exported (white -> black), and any specially-formatted text would stay as-is?  I don't think it's unreasonable to ask someone to modify the document with a white background if their end goal is to have a pretty, formatted document with a white background (i.e. printing, sharing).  It could actually be annoying in some ways if you try to outsmart the user and modify their document too much before printing.  Just thoughts :)

**Comment by Sajo8** [comment]
+1 for implementing a chromium-style print dialog, but I feel some linux users (like me!) will not like how it bypasses the default print dialog which has the system theme.

On that topic, maybe cryptee could respect system themes on linux, as firefox does? (On my system at least; manjaro gnome with adapta-nokto-eta-maia iirc) If one wanted a dark theme in an app they use they would also probably install a dark system-wide

**Comment by johnozbay** [comment]
@paulhovey, @Sajo8 As much as I wanted to, and tried to, there's no easy way to render PDF. It's a very **VERY** complex format to render from scratch. The easiest way is to create a pseudo-screenshot of the DOM using canvas, and basically slap images from this canvas onto pages of the PDF. (this is what most js libraries like [html2pdf](https://github.com/eKoopmans/html2pdf.js) do as well) [and I've already tried these months ago.](https://github.com/cryptee/web-client/blob/4fda23bf8702e7c83f267b8c7606ac32b342b313/source/js/docs.js#L7089-L7094) 🧐

– but these options all suck, because the canvas-exported images get cropped between PDF pages etc. AND even if you set the page-breaks right with a smart algorithm, this is still not good enough for an editor. Especially because, when you're exporting a PDF from a rich editor like Cryptee you expect URLs to work, images to look sharp, and pages to be separated accurately etc. So in general, I don't think the cause is worth the effort here. Most of these libraries are built for static generated content like, printing scannable tickets or QR codes etc generated in the client side, but not for complex editors with different fonts, text sizes, coloring, styling images etc. tons of complex CSS involved, and nothing static. 😔

To achieve all this, Google Docs / Office 365 etc send your document to their servers, render the PDF there, then send the result to client. There's tons of wizardry and magic involved in making PDF happen. (Needless to say, due to client side encryption Cryptee can't send to server for rendering of course, so everything needs to happen in the browser / on the client side, and it has to be cross-compatible with every OS and browser including iOS and Android where there's limited support for certain APIs, and long-term maintainable) 😫

So after looking into this for months, I've come to the conclusion that it's a baaad idea to try to implement and ship your own PDF rendering code. Particularly browsers already have their own, native, built in, PDF/Print dialogs, and they do an excellent job at exporting final-css-styled complex DOM structures and allow for PDF, Print, margins, etc. all that good stuff you're used to. 📰

@paulhovey 
> I don't think it's unreasonable to ask someone ..

If you have to ask them, it already is. Think about going to Google Docs, clicking PDF or Print, and it shows a pop-up and says : "Please go back and edit the 40 pages of custom styling you did without thinking what would happen if you print this" or worse, not showing a warning, then users going ahead and printing something in a rush, and finding out that they now have to go back and edit pages and pages of custom styling. 😅

>  It could actually be annoying in some ways if you try to outsmart the user and modify their document too much before printing

I don't think it's outsmarting, I think it's simply making it work as they expect things to work. There literally isn't a single document editor where you click print, and get a result different than what you expect. 🖨🤯

That being said, there literally isn't a single rich document editor with dark mode support either. Msft Word, Google Docs, even Apple's Pages on Mac OS Dark Mode has white background. (see below for a screenshot) This is not just a Cryptee thing. Generally rich text editors are built for use with paper, not for screens. So I might make the editor portion of Docs remain white, and the rest dark, but on mobile this won't look any different. There's still much to test and discover. 

@Sajo8 
> +1 for implementing a chromium-style print dialog

This is insane amounts of work, I've considered this but it's a whole javascript library worth of project on its own. Be it different paper sizes from all around the world, paper margins, getting the rendered CSS correctly from the editor, images scaled correctly with anti-aliasing, page-breaks etc. this is just not maintainable. 

> maybe cryptee could respect system themes on linux

It can read the system color-preference, but that's not the problem. On macs even if you're in Dark mode, Pages ( Apple's equivalent of Word / Google Docs ) still uses a white background editor to deal with this problem.

![image](https://user-images.githubusercontent.com/611338/61179830-3c6ee200-a613-11e9-8300-2a961f9e1a80.png)

It's all fun until it boils down to implementing all the details up to every day work-use/business expectations. I don't want to sacrifice quality or proper document editor features like a decent printing and PDF exports just because of dark mode either. Nevertheless I'll keep working on it because I'm a big dark-everything fan myself. Photos is easy. But for Docs, you can safely expect the editor to have white background until there's a good solution to these problems by everyone in the industry.

And PS – Don't get me wrong btw, I'm all for having a dark mode and making things cosmetically nice. It just turned out to be not as simple as inverting colors 😅 

Hoping these make sense! ✌🏻

**Comment by paulhovey** [comment]
Makes perfect sense, and you've clearly put a lot of thought into this 👏

**Comment by johnozbay** [comment]
Hey Everyone! 
This is almost ready. 
You can now start using it on the beta channel. 

**Step 1 : Launch Beta**
https://beta.crypt.ee

**Step 2 : Head over to your account settings > App Preferences**
https://beta.crypt.ee/account?action=preferences-app

**Step 3 : Turn on Dark Mode**

<img width="932" alt="image" src="https://user-images.githubusercontent.com/611338/64255259-aaf06200-cf29-11e9-8a4b-171d283e4608.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/611338/64255167-7f6d7780-cf29-11e9-9353-ee7816c02188.png">

**Step 4 : Join the Dark Side**

![dark-side](https://media2.giphy.com/media/5n02MkDT1iupKsmXo7/giphy.gif)

**Step 5 : Feedback** 
Report bugs or Jedis if you come across any. I've tested and fixed 99% of the stuff, but you never know. Different devices, different browsers, different galaxies. 🕷🌌

Thanks a lot for your patience everyone! ✌🏻

**Comment by paulhovey** [comment]
It looks awesome!!  Push to master ;)

**Comment by bobleeSwagger2** [comment]
No bugs found. Let's go!

**Comment by Sajo8** [comment]
Works great on my end! Let's get this rolled out!

**Comment by johnozbay** [comment]
Happy to hear! 🎉

So I've fixed about 100 more UI / color bugs since the dark mode beta release, and there are still some left like : 

Filesize in the PDF / Attachment viewer
![image](https://user-images.githubusercontent.com/611338/64595529-cdb3c800-d3ba-11e9-9b80-2e39066d7338.png)

Or the accidental icon hovers on mobile devices smaller than certain resolutions etc : 

![a17f97ac-375e-47e4-babf-f6493dff011b](https://user-images.githubusercontent.com/611338/64595568-e45a1f00-d3ba-11e9-8f68-a6ae4398ac34.png)

In addition, I'm working on adding automatic detection for systems that publish it. So if you switch your iPad / iPhone to dark mode, Cryptee will automatically pick that up and use that setting instead. 

Plus, I'm building tests for the newest Android 10 release, and iOS 13 release that's coming up today.  

In the meantime, please keep an eye out especially for things like font-colors, icon / button colors and similar things that might cause difficulty reading. 

Many thanks for your help and patience everyone!

**Comment by johnozbay** [comment]
Party time folks. 🎶

**Comment by brendanperry** [comment]
I don't think there is a perfect way to hold the user's hands on this one. Essentially dark mode is a cosmetic feature not a functional one, so only things changed for the sake of dark mode should be reverted back to light before printing. Obviously people print on white paper. This is the expected behavior. As a user I would be more confused by any attempt to keep any dark mode specific things in the print. I would not try this. That's just a bad idea. While it's not an ideal solution, it would be fair to include an option either on the page or in the settings to toggle between the current implementation and the full dark mode. If it was someone's main goal to make printable things, then maybe they'd rather just have the white all the time. Personally, I wouldn't, but if you're so concerned about the response, then maybe have the white be default. Then have a warning when the full dark mode is toggled in the settings as to what to expect when printing a page.

**Comment by johnozbay** [comment]
As much as I agree with you, this is a vote that should be held by all users. (and not just on Github) And a design decision we're trying to make with user experience research backing our findings.

Because as programmers we're a tiny segment of the general population, and a biased one at that. 
We stare at our IDEs, terminals, console's dark background + white text every day all day. We also don't have jobs that require us to use printers or paper. But that doesn't mean the majority of the users are like us.

I can of course convert black to white, white to black. To us programmers this will feel natural. 
But you have to think about users who are moving from other rich document editors like Microsoft Word, Apple Pages, Open Office, Google Docs etc, and none of these have dark-background for a reason. 

I know Google added this to their mobile apps a few weeks ago, but there's a major difference between how they can handle print and how we have to handle print. They can convert documents on server-side, and can do all sorts of analysis / generate PDFs and render the page perfectly on server-side. Whereas on Cryptee we can't do that, because your documents are encrypted and our server can't see their contents. Meaning that all this document-specific conversion will need to happen on devices themselves, resulting in a much poorer experience. 

---

That being said, we've been discussing this internally for a while now, and I have a couple ideas on how we can pull this off. We're considering making the all-dark switch, also limit the colors you can use for documents. So when you switch to all-dark mode, the color palette you have access to would be much more limited, and the colors would still have good legibility in both modes. 

In short, it'll work like an IDE theme. For example, an easy-to-read light yellow text in full-dark mode would be rendered as a different, much darker orange-like color in white-mode. And the only way this would work is if we limit the colors so we can map them manually to colors that are readable on both dark & light modes.

So it'll be like Atom's One Dark / One Light switch basically : 
![image](https://user-images.githubusercontent.com/611338/90517682-65469c80-e16e-11ea-9908-e9d03a8c1dd5.png)
![image](https://user-images.githubusercontent.com/611338/90517708-6f689b00-e16e-11ea-87f0-e5c6c4879b9a.png)

---

Even then, we think this will have to live behind a second switch, that makes it incredibly clear what that switch does, and what the results would look like if printed. 

---

What do you all think? Does this sound good?

**Comment by johnozbay** [comment]
Also – to add on to this, 

> Essentially dark mode is a cosmetic feature not a functional one

I respectfully disagree. This may be the case for you, but color contrast / accessibility is a very real issue for many people with color blindness. Things like inverted colors / low-contrast modes etc have been around for ages, and they impact many users' internet experience significantly. 

The concerns related to color & legibility are prominent enough that there's an entire, dedicated [Web Accessibility Initiative by W3C](https://www.w3.org/WAI/perspective-videos/contrast/) – and even search engines score pages differently based on their design's contrast & legibility. [So we actually have guidelines to follow even for contrast ratios for usability.](https://web.dev/color-contrast/)

So in my personal opinion, the issue is a bit deeper than adding a simple switch, especially for a text editor, where the service's primary purpose is editing & reading text.

**Comment by brendanperry** [comment]
I guess I understand where you are coming from here, but as a colorblind user myself, I generally avoid any form of color coding in my documents. I just work black and white and would not be impacted by the visibility of colors on a darker background. Although, I do see why that is a concern. To be fair though, if I set a color to blue and the background to black, that's what I would expect to see regardless of whether or not it looks good. I'd rather have that than have a limited color palette because of a web standard that as a user I don't care about. If somebody needed a certain color and wanted to work in dark mode it would be frustrating to restrict their access because it doesn't look good enough when they don't care because it's going on white paper in the end anyway. 

In the end though, you understand the demographic better than I do, and I'll be happy in general with any form of full dark mode.

**Comment by essafik** [comment]
> In short, it'll work like an IDE theme. For example, an easy-to-read light yellow text in full-dark mode would be rendered as a different, much darker orange-like color in white-mode. And the only way this would work is if we limit the colors so we can map them manually to colors that are readable on both dark & light modes.

> 
> What do you all think? Does this sound good?

I think this is probably the best option right now. It gives the users an option and make it easy to switch to light mode for printing because there will be a one to one mapping. If you implement this, I hope you will have a Dracula option ;)

**Comment by johnozbay** [comment]
Hello everyone! 👋🏻

I'm incredibly happy to let you know that we've finally shipped Cryptee v3.0 today! 🎉  ( 01edfe4 ) 
And it has full dark mode support for the editor! Here are two images to get you excited! 

![image](https://user-images.githubusercontent.com/611338/108634553-b9666c80-7482-11eb-8f02-9407ed7f3106.png)

![image](https://user-images.githubusercontent.com/611338/108634573-d26f1d80-7482-11eb-8236-04cdc484e11d.png)

We ended up limiting the color options to get things started, and we'll be adding more color options as we go. 

You can read more about the release here : 
https://blog.crypt.ee/say-hello-to-a-new-cryptee

Looking forward to hearing your thoughts!

Best, 
J
