### ISSUE TITLE
[Feature Request] Preview / Edit search results

### ISSUE THREAD

**Issue by pablo03v** [cryptee/web-client#205]
**Is your feature request related to a problem? Please describe.**
Can't see the search results but only the docs in which the search found the results.

**Describe the solution you'd like**
I'd like to see the search results where I could directly edit the docs.

**Additional context**
I've created a mockup:
<img width="1392" alt="Screenshot 2024-03-23 at 07 56 28" src="https://github.com/cryptee/web-client/assets/93644977/ff60ecf1-bcdc-4f7a-a978-9d51184c5599">

**Comment by johnozbay** [comment]
Hey there @pabloscloud 👋🏻
Thanks for filing this. 

I'm afraid this is mathematically not possible due to how our zero-access encryption works, pretty much for the same reason as #86. (and I wrote a little bit about this in #204 as well) Since all your documents are encrypted on your device, this feature would require downloading and decrypting all documents that match the search criteria in realtime, which is sadly not feasible with all library sizes. i.e. it may work for an account with 50 docs relatively quickly, but it won't work for an account with even 1gb of docs. 

We might be able to add a small preview image to search results i.e. on hover etc though if that helps? 

For now, I'll close this thread, but if you think a preview image helps, we can consider working on something like this. 

Best,

J

**Comment by johnozbay** [comment]
And potentially related to #60 — Figured I would link to make it easier to find stuff in the future ✌🏻

**Comment by pablo03v** [comment]
> We might be able to add a small preview image to search results i.e. on hover etc though if that helps?


This was not the answer I was hoping for but would stilI be ingredibly handy to find stuff quicker imho. You're doing great!

**Comment by johnozbay** [comment]
Sorry 😞  

There are so many things I would love for us to build if only we didn't have to worry about client-side encryption.

— But — 

At least I can say that the small thumbnail idea has been on the table for a while now for multiple reasons. 
We're looking into making something like this happen. 
It will also be super sweet for things like PDFs etc. 

Will update this thread once we have more to share 👍🏻

Thanks for your kind words and continued support and encouragement btw 🙏🏻
World needs more people like you!
