### ISSUE TITLE
[Feature Request] Import from Standard Notes

### ISSUE THREAD

**Issue by Morse6690** [cryptee/web-client#209]
Loving trying Cryptee for the first time. 

All my notes in SN are plain text. 
What is the easiest way to bulk import plain text notes from SN into Cryptee?

I'm guessing there is no way for tags to automatically come across?

**Comment by pablo03v** [comment]
> I'm guessing there is no way for tags to automatically come across?

https://github.com/cryptee/web-client/issues/206?notification_referrer_id=NT_kwDOBZTosbM5OTcwMDQ4NDI3OjkzNjQ0OTc3#issuecomment-2115856407

I opened a feature request about this

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Which formats are you able to export from SN? 
i.e. is it TXT or Markdown or HTML etc? 

If you can export TXT / Markdown / HTML, 
Prepare an example note that uses all editor features i.e. bold / italic etc like : 

**this is a bold sentence**
_this is an italic sentence_
`[[this is a tag]]` (or whatever their tag annotation is like)

and sshoot me an email to :    

john `{~at~}` crypt `[-dot-]` ee 

I'll take a look at it with the team and keep this thread updated 👍🏻

---

If it's txt or markdown, imports should work out of the box. 
Tags on the other hand won't, as @pabloscloud mentioned, I briefly explained why in #206. 

But we've been getting lots of emails and support messages asking about this (especially related to SN since their announcement to join PM) so we might as well actively start looking into this 👍🏻

Hoping this helps,

Looking forward to hearing from you, 

Best,
J

**Comment by Morse6690** [comment]
Mine were all just in TXT format.
I just want sure if there e was a way to retain tags and linkages etc.
I simply dragged them all across to the browser and they uploaded fine.
