### ISSUE TITLE
[Feature] Custom fonts

### ISSUE THREAD

**Issue by mainrs** [cryptee/web-client#21]
Hey there!

I just noticed that you can only choose the standard font classes that you configured in your own browser (sans, sans-serif and monospace). Would it be possible to allow custom fonts to be used? 

I guess a simple enumeration + selection would be enough. There could be a fallback behaviour to just go with the standard fonts if the selected one isn't available on the system I am currently logged in and working on,

The reason is because I would love to use FiraCode for some parts of the document. It's probably a huge request though...

**Comment by johnozbay** [comment]
Hello fellow FiraCode fan ✌🏻Thanks for opening this! 

This has been one of those things sitting on top of my to-do list. As far as implementation goes it's quite easy actually but there are a few reasons why I haven't added the ability to use custom fonts yet. 

1 – Licenses. Because Cryptee is a for-profit company, and the editor allows you to "create" using the fonts, fonts must have the correct licenses. Which means [hosting things like Helvetica is out of the picture for now](https://www.fontshop.com/families/helvetica/buy). But for example it's okay if I use any open-source / Creative Commons fonts like those in the Google Fonts family. (I'll get into more details about this below) – or things like FiraCode. 🤓

2 – Browsers. My first thought was to use system fonts by enumerating fonts available in the browser. However, that is [exactly the technique](https://browserleaks.com/fonts) malicious websites use to fingerprint users on the internet. Because the exact set of fonts you have make you more unique on the internet. So most privacy browser extensions actually block these custom fonts, and as you can guess most of Cryptee's users have 10 extensions like these installed. 💻

3 – Hosting. In theory, anything from Google Fonts would work, since they're mostly open-source or licensed with Creative Commons etc. but since for privacy reasons I can't use Google to host them, I need to host them myself. This also means that when you install Cryptee you end up with a copy of all the fonts installed onto your device. It's not significant, but if it was 20 - 30 fonts, this would start adding up. So fonts would need to be loaded not statically, but dynamically to avoid bloat, which means using a separate build process for fonts, that doesn't "ship" the fonts with the app, but instead they're dynamically loaded into the editor. 📝

I've got a prototype that kinda works, and I'm trying to get this ready for the upcoming uni season so that students / researchers / academics can start using proper fonts for their documents. So I think you can expect to have this feature sometime September / October-ish. 👍🏻

I'll tag, ping and close this thread once this feature is shipped and ready! (Alternatively keep an eye out on [beta](https://beta.crypt.ee), and you can help me test it once it lands there. 
 
Hoping these make sense, 
Best, 
J

**Comment by johnozbay** [comment]
Surprise 🎉

**Comment by mainrs** [comment]
Damn, thanks!!!

**Comment by johnozbay** [comment]
You're very welcome! Still couldn't add Fira Code btw. There's a mini bug related to the way FiraCode's ligatures work. But I'm working on it, and will release as soon as that's ready as well.

**Comment by johnozbay** [comment]
Oh and – found a way to use Helvetica straight from the system without hosting it 😎😂
