### ISSUE TITLE
[Feature Request]  Hope to add support for Canon camera raw file format .CR2/.CR3

### ISSUE THREAD

**Issue by LinYuyang86** [cryptee/web-client#218]
**Is your feature request related to a problem? Please describe.**
Leica is so expensive...
Haha, just kidding.
I mainly use Canon cameras, and I hope you can support uploading photos in CR2 and CR3 formats, and display Exif information like Leica.

**Describe the solution you'd like**
Add support for Canon camera raw file format .CR2/.CR3, Exif too.

**Comment by johnozbay** [comment]
Hi there! 

Apologies for the delay on this! — We've been busy building a bunch of large sized features and finally catching up with feature requests. 

Due to the fact that Cryptee encrypts everything client-side on your device, all photos' thumbnails & preview sizes are generated using the canvas in your browser before getting encrypted & uploaded. Unlike un-encrypted services – which can do all this on their servers. Since they can see the contents of your photos, they can also scale down/crop your photos on their servers.

Unfortunately, due to the fact that browsers don't support encoding or viewing RAW files, or converting these formats in on your device's in-browser canvas easily, we need to build our own encode/decoders for these formats into Cryptee. 

Even if Cryptee theoretically could upload files like CR2 or CR3, the photos wouldn't have any thumbnails in your gallery. 

The difficulty with these formats is that unlike DNG or TIFF files (which are used by Leica and Hasselblad etc), some camera manufacturers, like Canon (with CRW) or Sony (with ARW) and Nikon (with NEF) use proprietary codecs and algorithms to for images in their formats and like that's not enough, these aren't even documented. Only documentation we could find is on random old bulletin boards and forums by others who tried reverse engineering them.

Due to this, there are no easy / readily available ways to add support for these codecs. And since Cryptee is entirely open-source, we cannot easily ship their proprietary algorithms with our codebase, so we're left with no choice but to reverse-engineer and build the codec support ourselves from ground up, which is taking some time.

We have a Sony, Nikon and Canon in the office and we're slowly building support for these. We're very close. Turns out it's even more complicated because some manufacturers ~ahem ... nikon~ don't even use the modern / common jpg compression, but instead use a now-outdated uncommon jpg-in-tiff compression, and their raw format is a variant of tiff etc etc... 

As much as I want to give an estimate on this, we keep hitting strange brick walls due to the vast amount of variance between proprietary RAW formats, and my estimates would be all wrong. So I can only say that we're making steady progress and we hope to have these out very soon. <unless we run into more issues with the codecs...>

Stay tuned to our [blog](https://blog.crypt.ee) via rss or email, and we'll make a massive announcement once it's ready with tons of details and examples. (And of course I'll update this issue once it's out as well)

Many thanks again,

All the best,

J

**Comment by johnozbay** [comment]
I'll update this to say, **_VERY_** soon. hahaha 
Chances are this will be out in a few weeks time.
Stay tuned. 

Best,
J

**Comment by johnozbay** [comment]
Hi there! 👋🏻

42a878604475e86ba7cca05079b4d2db6040ade2 adds support for Canon formats as well as hundreds of other cameras! 🥳 

You can read more about it here : 

https://blog.crypt.ee/cryptee-photos-supports-all-raw-photo-formats/

Give it a try and let us know what you think! ✌🏻

Thanks for your patience with this!

Best,

J
