### ISSUE TITLE
[Feature] File/Folder Explorer for Docs

### ISSUE THREAD

**Issue by elevatorz89** [cryptee/web-client#22]
Heyo!
 
I found that the only way to upload files was to drag them into the document folders, and that tends to get very messy quickly. Not sure if this would be possible, but a File-only view could help remedy the messiness. (As in, not in a side menu, but an entire page dedicated to it).

**Comment by johnozbay** [comment]
Hi there! ✌🏻

This is a great idea!
So for you would the ideal File Explorer look like full-screen page/modal/pop-up inside Docs, where you can explore your folders, docs & files – am I understanding this correctly? 

If I got this right – 

I can see how this would improve file-exploration / search etc.
But your upload flow wouldn't change much. So you would still need to drag and drop files into folders. Or you would still need to select and upload files into these folders. It'll be a bigger / wider folders view, but that's about it.

Can you give me a few example use cases / workflows / step-by-step actions you take, that would improved by this new flow, so that I can think about how I can design and make this better?

Thanks ✌🏻

**Comment by elevatorz89** [comment]
Probably should have elaborated on this first, but yes, you have the right idea. Something similar to a cloud storage, if you'd compare it to that. 

I'm personally planning on storing different files that I'd rather keep out of big-named cloud storages but ones that nessesarilly wouldn't need to be inserted into a document/arent documents themself. It would also save the hassle of having to open the side menu (which is a hover-only thing) every time you'd need to upload a new file.

**Comment by johnozbay** [comment]
I see! Got it! 👍🏻

I'm in the process of building a whole new product dedicated and specific for file-sync (similar to Google Drive or Dropbox) and for now I can't give a timeline for this since it's a massive undertaking. 

In the meantime it's better to think of Cryptee Docs along the lines of Google Docs / Dropbox Paper. On their platforms the services are very interconnected, so with a quick look it's easy to think they're all part of one product. But infrastructure-wise these have completely different storage models under the hood. Mainly the usage-cadence of files. 

So for example for Photos, you're more likely to keep uploading albums of let's say 100 photos and 10mb photos each, and every now and then open the "summer vacation 2016" to take a look at it. When you do look at it, you're not really loading the 10mb-size originals though, you're instead loading a lidhbox-sized resized version of the original that's 500kb, and maybe a thumbnail sized one that's 100kb at max. So when you think about it, you never really download the originals, and these are used for long-term storage, whereas thumbnails are frequently accessed. So you need to store thumbnails and Lightbox sized images in hot storage, but originals can be kept cold safely. 📷

Whereas with Docs, you need access to all your files instantly, right away. = all hot storage.
File-system / sync (like dropbox/drive), similarly, you need access to these instantly, and right away if possible. But with much much deeper folder structures and it would need to scale to hundreds of thousands of more files and folders all nested as many layers deeply as it takes.

And as soon as you have a folder-tree / nested-folder structure, things become harder and harder to manage. For example on Cryptee file & folder names are also encrypted. Which is what takes time for Docs to boot up. You need to decrypt all of that first to even show the UI for you to click on the Doc you wish to load. There is of course a local cache, but nevertheless decrypting things take time.

With tens of thousands of files this would take a long time, and encrypted local caching tricks solve this problem, but with hundreds of thousands and millions of files, (say for example if you throw a fancy `npm_modules` folder in there, then things will get really _really_ complicated) – the easiest way to see what I mean is to download [Cryptomator](https://cryptomator.org), and give it a try with a complex nested file&folder structure. You'll see after a deep folder or two how time consuming it would become if you had a giant 2TB drive in there with tons of folders. 🗂

– So while I'm working on this every day, and there's a dedicated sync'ed storage product in the pipeline, this will take time, since it's a massive infrastructure and algorithmic undertaking to make sure everything is safely stored, and it's usably fast & practical. 

In the meantime, for sync'ed file storage needs, I'd still recommend Cryptomator in harmony with another storage provider. It's open source, and does an excellent job at encrypting everything including filenames. 

That being said – let's talk about what I can do about the sidebar. 

I've intentionally made it so that when you drag anything into Docs, the sidebar opens up and shows all the folders. Or you can also select individual files with the upload button and upload directly into folders themselves. Can you think of any other different ways I can improve this experience? I'm all open for feedback and changes on this. ✌🏻

In the meantime I'll also look into whether or not if it's possible to make a full-screen docs-explorer. I think this is a great idea and it'll improve things immensely.

**Comment by johnozbay** [comment]
Looks like making this with #2 is going to be easier. So figured I'll link here to keep track

**Comment by johnozbay** [comment]
Today we've released Cryptee v3.0 ( 01edfe4 ), and it  brings a much better file explorer! Give it a try and let me know how you like it, and what you think could be improved. We now have two prototype file explorers, and we'll be beta testing these in the upcoming 2 - 3 months!

**Comment by elevatorz89** [comment]
The "pin button" for the new file explorer pretty much alleviates any struggles I've had in the past. The "type" sort makes the mess manageable. Although there is one small nitpick I have with **renaming** documents. When clicking rename, it doesn't allow you to edit the existing name, and it requires you to retype the entire thing, which can be annoying if you're fixing a one-letter typo.

**Comment by johnozbay** [comment]
> The "pin button" for the new file explorer pretty much alleviates any struggles I've had in the past

Really happy to hear this helped! 

> When clicking rename, it doesn't allow you to edit the existing name, and it requires you to retype the entire thing, which can be annoying if you're fixing a one-letter typo.

Just pushed out an update for you ( af391224e650aae52802f30cea2d7e040f6c5880 ) and this should be fixed now 🎉
In the interest of closing old-ish v2 issues I'll close this one for now. But please keep shooting bug reports our way! 

We're on a roll this week 🎉
