### ISSUE TITLE
[Bug] Manifest has a zero-width character making it impossible to install Crypt.ee using "PWA for Firefox extension"

### ISSUE THREAD

**Issue by MoralCoral** [cryptee/web-client#222]
**Describe the bug**
Can't install Crypt.ee as PWA in Firefox using the "PWA for Firefox" extension

**To Reproduce**
1. Go to Crypt.ee
2. Click on the "Install this site" button up in the address bar
3. Fill in the app preferences (or use default settings)
4. See error message: 
"Error
Failed to parse web app manifest: parse failed. at line 48 column 28"

**Expected behavior**
The app would install

**System Information (please complete the following information):**
 - Device: Lenovo Thinkpad X1 Carbon
 - OS: Endevour OS (Arch linux)
 - Browser Firefox
 - Browser Version [e.g. 22]
 - Browser Extensions ublock origin, Progressive Web Apps for Firefox
 - Do you have any DNS-based content/ad-blockers? No
 - Are you on a managed network? No

**Additional context**
So far, Crypt.ee has been the only app that can't be installed. Github, Reddit, WhatsApp web etc have worked without any issues

**Comment by johnozbay** [comment]
Hi there! 
Oh wow thanks for this catch. The Line 48 column 28 was super helpful. 
Which is this

https://github.com/cryptee/web-client/blob/4c974c470a3ae08fa8186fdfba439efdbe7f5dac/source/webapp.json#L48

In short, that space before the "x" seems like a zero-width character, which we couldn't see in our code in the editor. 
That being said, this didn't stop our manifest from being parsed successfully on other browsers, including Firefox itself on Android. 

So it looks like PWA for Firefox made an error in their code / implementation of the manifest parser as well. 

We fixed this in the alpha version and the issue is linked to our internal issue/release tracker.
Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification!

Thank you so much for filing this, your help and patience!

**Comment by MoralCoral** [comment]
Thanks a ton! It works now :1st_place_medal:
