### ISSUE TITLE
Question: Image storage

### ISSUE THREAD

**Issue by mainrs** [cryptee/web-client#25]
Sorry to use the issue tracker for questions about crypt.ee :(
I wanted to create a PWA podcast application and was wondering how you handle image storage on the local device. As far as I know it's limited by the browser and there is currently no good way to actually store large files within a PWA app.

For my case that would be mp3 files.

**Comment by johnozbay** [comment]
Hi there! 👋🏻

No worries. It's still 50% Cryptee related, and I love PWAs haha! 
Cryptee uses a combination of localStorage + IndexedDB via [localforage](https://github.com/localForage/localForage).

Here's what you should take a look at : https://github.com/cryptee/web-client/blob/6c95e4c09ce29802748fecec7ff0786f473cb19d/source/js/docs.js#L8894

And here's some good reading related to offline storage for PWAs : 
https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/offline-for-pwa

Overall, you can't store massive amounts of data. But you can safely assume you have access to 5 - 10% of the users available storage on Chrome / Firefox, and 50MB on Safari. This will likely change very soon for the better tho. 

For Cryptee you can only keep Cryptee Documents offline, and not images or other files. And since your documents are merely encoded & encrypted text, it doesn't take up that much space.  

The current most popular workaround (which I'm not using, but have considered using) is to use iframes and partition your offline storage into multiple domain names. This allows every new domain from the iframe to get a new storage space allocated. This is especially useful for Safari, since each domain can get max 50mb. For example for a podcast app, you can tell your users that they can only have 10 podcasts downloaded offline. Add 10 subdomains, and load 10 iframes. This would allow you to store 500mb, and this way you can package this technical limitation cosmetically. 

Beware though especially on Safari, but mainly on iOS (since Chrome/FF etc are all running WebKit under the hood) if your device is running out of storage, iOS may evict your data without notifying your user.  

Also, since you mentioned podcast, take a look at the relatively new Background Fetch API demo: 
https://developers.google.com/web/updates/2018/12/background-fetch
It's basically a podcast app, and it could be a nice addition on Android. 

–– Closing this thread, but feel free to ping me using the email from the footer of the site. 
a) I'll get back to you faster.
b) We'll keep GitHub cleaner. 

Cheers ✌🏻
