### ISSUE TITLE
[Feature] Markdown Triggered Emojis for Cryptee Docs

### ISSUE THREAD

**Issue by l-lin** [cryptee/web-client#26]
It will be nice if cryptee docs could support emojis that are displayed as we type in the document.

Maybe using something like https://github.com/markdown-it/markdown-it-emoji?

**Comment by johnozbay** [comment]
Hi there! 

First off, Cryptee Docs already do support emojis. 

![image](https://user-images.githubusercontent.com/611338/64706191-c9ba9f80-d4b9-11e9-82a4-ecb67c6aab8a.png)

So if I'm understanding your request correctly, this isn't about supporting emojis, but supporting markdown-triggered emojis. Is that correct? 

Given that Cryptee is a document editor, similar to Google Docs, or Dropbox Paper, I think this would cause tons and tons of frustration with business documents. 

More importantly, there would need to be an edge case for the code blocks. Otherwise things like  `;)`  or  `:-`   could trigger emojis unnecessary in some programming languages. 

I know things like GitHub have this in the comments, but given the context I think it makes less sense that this feature exists in a Document Editor.

Does this make sense?

**Comment by l-lin** [comment]
Yes, I was thinking something like what you mentioned: markdown-triggered emojis.
The challenge to include is feature is indeed not trivial.

Maybe an alternative is to add an option in the menu, something like the github comment reaction, that adds the emoji in its unicode form?

**Comment by johnozbay** [comment]
All operating systems, Android, iOS, [Mac](https://www.imore.com/how-to-use-emoji-on-your-mac), [Linux](https://www.howtogeek.com/fyi/how-to-use-emoji-in-ubuntu-18.04/) and [Windows](https://blogs.windows.com/windowsexperience/2018/02/05/windows-10-tip-get-started-emoji-keyboard-shortcut/) have emoji input keyboards, which input Unicode Emojis already. I don't see any reason to redundantly build this feature into Cryptee. 

It's often messengers or comment boxes that have this emoji-markdown feature like Slack, or Github comments etc, where there's limited input space, and you need to type emojis really quickly to respond to something in a timely manner. Not in document editors where you have a large page to type text into, and more time. 

I think this is out of scope and redundant given that you can input these using your computer/phone's keyboards already. Closing for now.
