### ISSUE TITLE
Add Offline-First Mode to Cryptee Docs

### ISSUE THREAD

**Issue by mbande** [cryptee/web-client#28]
I'm a new comer, and as i investigated with the web-client, one of the most annoying things is that it is supposed that every time the user has internet connection.
when you go offline, the directory structure disappears, and one should start by an empty space!
also, every note to be available offline, should be "toggled" one by one.
is there any good reason to not having a global "Offline" Mode, to work offline by default, and a "Sync" button to go live when needed?

**Comment by johnozbay** [comment]
Hi there! 

There are a few very specific reasons why this is the case, I'll break it down, and I think it'll all make sense once you hear it too. 

With apps like Evernote, all your notes are stored offline-first and offline by default, THEN sync'ed to the cloud for sync'ing between devices. This is great if your files & library won't be large, since you don't have to wait for your note to be downloaded & decrypted.
 
Whereas Cryptee Docs is online-first. Similar to Google Docs, and you can choose to make specific documents / folders available offline for accessing them faster / on the plane without internet etc. This has to do with the fact that Cryptee Documents and libraries are built to grow a lot larger. A doc can easily be ~25-40mb if you start embedding large photos, KaTeX math, writing code in it etc. But also, because Cryptee Docs isn't just storing note/doc files, but also PDFs, Audio, Video, Zip whatever file you throw in the same folder or attach the document. Like a PDF Report side by side with your doc, and keep taking notes etc.
 
Because you can attach any encrypted file to documents in Cryptee, it means that your library can grow really big really quickly, and you could theoretically have more docs on Cryptee than your phone / tablet / laptop's storage space. (Cryptee supports 2TB for example, which is way beyond most laptops and phones) Side effect of this is that it’s impossible to make it offline-first because your device would run out storage space quickly.
 
For these reasons, I've intentionally named Cryptee Docs "Docs" rather than "notes" because contents could get heavier than notes, it's got more features than just simply writing plaintext notes, and as the platform grows the behavior will mimic things like Google Docs, instead of Evernote. 

I hope this makes sense, 

Best,
J

**Comment by mbande** [comment]
@johnozbay thank you for you through response
If I understand your arguments correctly,  it's about storing big docs, as you think storing them in the cloud is the right way.
what if users want to use cryptee for just "note taking", or they want to store big docs selectively on the cloud.
even if I agree with all of your statements, the current offline mode has a "bug" which makes it useless for me: the directory structure disappears offline. and the created offline docs should be moved to proper location later.

**Comment by johnozbay** [comment]
Cryptee's behavior is identical to other rich document editors like Google Docs, Dropbox Paper, Quip etc. (or things like Spotify that are data-heavy, and also needs to be online-first / selectively-offline) so if you're looking for an offline-first / selectively-online solution, for now, Cryptee isn't it.

As for directories disappearing, there's a ton of reasons why I had to do it this way, but in short, it's related to #2 and #22 – and will get better once these two features are ready for primetime.
