### ISSUE TITLE
Inactivity timeout not saving

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#3]
I have set inactivity timeout to `0` multiple times but it keeps resetting to `30`. I am on Brave on Android 9.

**Comment by johnozbay** [comment]
Hey @ryanpcmcquen! 
Thanks for sending this through. 

I can replicate this on my end as well!

Seems like a problem with the way input type="number" change events are handled in some browsers - Somehow, the "on change" event of the number input fires only when you press the down arrow/button next to the input box if the number reaches "0". 

Will push a fix for this in the upcoming release. 

In the meantime, a temporary solution is to use a desktop browser, 
1) Select all the text, 
2) Type "0",
3) Then using the browser's number ticker on the right side of the input box 
(press the down button/arrow as if you'll be setting it to -1) 

Number will appear to stay 0 (because there's a limiter to prevent it from going below 0) But this time it will be saved to the server - which will be automatically picked up by your phone too.

**Comment by johnozbay** [comment]
Mini update, figured out the problem. An incredibly silly JS oversight on my part. 

https://github.com/cryptee/web-client/blob/c6dc9bd0df01761fb64ece6ea9127fb54c504009/source/js/account.js#L1117

if `parseInt` returns 0, that means the `||` (OR) operator will take it as `false`. 
Simply removing the `|| 30` here 

and using `>= 0` here :

https://github.com/cryptee/web-client/blob/c6dc9bd0df01761fb64ece6ea9127fb54c504009/source/js/preferences.js#L110

seems to fix the problem. Expect these in the next update ✌🏻
Sorry again!

**Comment by ryanpcmcquen** [comment]
You could also use `Number()`, which is more declarative, and should return `0` rather than the falsy `NaN`.

**Comment by johnozbay** [comment]
Actually it's not that `NaN`-ness but the fact that in JS `||` takes `0` as `false`.
So even if you pass Number() it'll still pick 30 because :  
`var test = 0 || -1 ;` 
returns `-1`. 

And say for example: 
`var test  = 0 || false || undefined || "" || 8 || -5;` 
would return `8`.

**Comment by ryanpcmcquen** [comment]
Ah, yes, a logical misstep. A ternary would work better here.

**Comment by ryanpcmcquen** [comment]
The plot thickens. I did as instructed on desktop and the timeout is still resetting to `30` on mobile.

**Comment by johnozbay** [comment]
Hey Ryan! I'd say it's likely saved on the server, but the settings aren't being reflected due to this : https://github.com/cryptee/web-client/blob/c6dc9bd0df01761fb64ece6ea9127fb54c504009/source/js/preferences.js#L110 which needs to use `>= 0` as per my previous post. 

The update I'm working on this week has a lot of fixes + things that are directly related to preferences and how they're loaded etc. So I'm sorry for the delay, but I think it's best to push it all out together to make sure it all works this time.

**Comment by ryanpcmcquen** [comment]
Well, besides not being reflected, it is also timing out quickly ...

**Comment by ryanpcmcquen** [comment]
@johnozbay, any updates here? Changing the setting on desktop does not affect mobile ... I am not sure the `0` timeout actually works at all.

**Comment by johnozbay** [comment]
Hey @ryanpcmcquen! 

Sorry for the wait! 😞
The implementation error regarding "0" = false, exists even when reflecting the settings you got from the server. (you can see the line of code for why in my previous response) - I've already patched this in the private dev branch and it's scheduled to release with the upcoming update in a few days. (which will fix approx 100 more non-critical bugs along with this one)

The reason I'm not pushing it out right away just for this fix is because updates bust caches of all users, and forces downloading the latest version of all files for security reasons. So I don't want to bust megabytes of cache on everyone's devices for a few non-critical fixes, only to push another update in a few days. Sorry again for the wait with this one. Almost there I promise. 🙏🏻

---

Also just to further clarify what "Inactivity Timeout" is, so that we're on the same page here:

It's basically to erase your encryption key from memory after a certain period of inactivity. (say for example 5 minutes) So if you left Cryptee Docs open on your laptop at work, and walked away, Cryptee will lock down after 5 minutes.

This is less useful / important on Mobile/Tablets, since every time you quit / restart Cryptee you have to type your key in anyway. (unless your device goes to sleep while Cryptee is the actively open app, then Inactivity Timeout will still lock your device when your device wakes up after say 6 minutes)

The reason why you have to type your key on Mobile/Tablets every time is because your key is never written to disk for security reasons, it's only kept in memory to decrypt while the app / window is open. This means that it can't be stolen or extracted from the disk. And having physical access to your device or its disk wouldn't compromise your files' security. 

Same situation applies for Desktop if you close the tab/window/app by the way. Your key is only kept in memory instead of sessionStorage, - because as it turns out, if your device goes to sleep, browsers write sessionStorage to disk, and do so in an unencrypted form. 🤦🏻‍♂️

In fact some more fun details here: To make sure your key never stays in sessionStorage and gets written to disk if your device goes to sleep, in order to retain your key in memory when navigating between Cryptee's pages, (say from Docs to Photos) -

I tap into the 'click' events of every link, 
Check to see if it's an intra-cryptee link or not, 
If it's a Cryptee page, write the key from memory to sessionStorage right before navigating away, 
Then once the new page is loaded, restore the key to memory from sessionStorage,
Then erase it from sessionStorage again. 

So the only time your key ever touches sessionStorage is during page loads. (and unless you can manage to sleep your computer right before the page loads, your key is never written to sessionStorage/disk to assure your key's physical safety)

I hope these make sense ✌🏻

**Comment by johnozbay** [comment]
Hey @ryanpcmcquen just wanted to keep you posted on what's taking long. ✌🏻

<img width="1552" alt="new-docs" src="https://user-images.githubusercontent.com/611338/46299680-903f9b80-c5aa-11e8-8659-ed78bed0bc50.png">

It's a massive update! Almost there! 🎉
So many new features + new design + 100s of bugfixes + performance & security improvements etc.

Sorry about the delay, but I promise it's going to be worth it. 🤓
Thank you for your patience and understanding

**Comment by ryanpcmcquen** [comment]
@johnozbay, I am excited to see these changes!

**Comment by johnozbay** [comment]
Just another mini update with a screenshot to let you know how things are progressing. It's quite a crazy update. 

<img width="498" alt="screen shot 2018-10-05 at 15 55 12" src="https://user-images.githubusercontent.com/611338/46536408-19124c00-c8b7-11e8-899a-669c17354ea4.png">

Aaaalmost there. 🧐

**Comment by johnozbay** [comment]
Hey @ryanpcmcquen - Finally the massive update is out. ( b33a7c3498c628847693b2750342060bc06d4859 )  

First off - many million thanks for your bug reports, and your patience! I owe you a beer for the patience on this one. This bug report just happened to overlap with the biggest update in the history of the service. So forgive me for the delay once again. 

b33a7c3498c628847693b2750342060bc06d4859 fixes about a hundred bugs, but as far as big updates with 4000+ lines of changes goes, I'm sure this introduces another hundred bugs. Play around and let me know if you're still having issues with the inactivity timeout. 
(and needless to say feel free to file up all the bugs as you find here)

After this bug report, I've decided that it's wise to ask everyone what they think about a setting/preference to "always remember decryption key on mobile" - but make it off by default with a big red warning. - I'm going to collect feedback on this via all means possible, and will eventually add a preference to allow this as well. 

The reason I didn't want to add this is because it creates a security issue. (what happens if your device is stolen / abusive partner unlocks your device without you knowing etc. Essentially a  "remember decryption key" is against Cryptee's threat model.) So I'm generally very hesitant to add this. I will keep asking around, do some research, calculate the risks, and maaaybe add a setting for this with a huge red warning that explains users what they're about to do. Feel free to let me know what you think via email / helpdesk, and we can talk more about a "remember key" checkbox.

Thanks again for your patience! Let me know how you like Docs 2.0, and/or if you find any bugs! 🎉

**Comment by ryanpcmcquen** [comment]
I think with the proper warnings it would be great for usability. If you care about security, there should be locks on your mobile devices before you can just open any app, so any app security is a second layer.

**Comment by johnozbay** [comment]
As much as I agree with this, having a device password isn't enough per-se in a very specific situation, which Cryptee and its threat/security model addresses directly. Which is that even if you have to unlock your device in front of someone, your Cryptee files / folders should still be safe. 

This is called [rubber-hose-cryptanalysis](https://en.wikipedia.org/wiki/Rubber-hose_cryptanalysis). And here's an [XKCD comic](https://xkcd.com/538/) about this.

In short, say if you have an abusive partner, or you're at an [oppressive border checkpoint](https://www.nytimes.com/2018/10/02/world/asia/new-zealand-passwords-devices.html), Cryptee can still protect your data. ( be it using ghost folders, or having a second layer of encryption key etc. depending on the circumstance ) So there's definitely a need for the app to ask the key. I'm just trying to figure out the best way to make sure users' data is safe. 

The way I see things, security & convenience is like two ends of a slider. Your data can be very secure, but it would be inconvenient to access it, or your data can be conveniently accessible, but won't be as secure (say for example keys would be stored on device etc, creating all types of potential security issues) - in short, I'm trying to strike the right balance between security & convenience here.

**Comment by ryanpcmcquen** [comment]
Very true. The way Standard Notes handles this is with an optional, additional passcode lock. That is just one idea of course. Making it optional means you could switch on extra security when traveling, for the famous border agent example.

**Comment by johnozbay** [comment]
Agreed for optional, but I think it should be opt-out by default. We should encourage stronger security, not weaker. 3 big countries and likely many more unreported ones are starting to become very oppressive with this. 

[US is ramping up](https://www.wired.com/2017/02/guide-getting-past-customs-digital-privacy-intact/) its efforts, [China is reportedly installing spyware on devices](https://www.reddit.com/r/security/comments/8ofiiw/chinese_border_police_installed_software_on_my/), and [New Zealand ](https://www.nytimes.com/2018/10/02/world/asia/new-zealand-passwords-devices.html) can fine you if you refuse to provide keys...

And I've even considered using biometrics instead of encryption key on mobile, [but it's not considered a password at borders, and they can ask you to unlock that as well](https://www.eff.org/press/releases/digital-privacy-us-border-new-how-guide-eff). So until I can find a better way to assure files on Cryptee to be safe, not just borders but in any sort of power asymmetry situation (like abusive partners in relationships, or [employers asking future employees their social media / account passwords](https://www.telegraph.co.uk/technology/facebook/9155368/Companies-asking-for-Facebook-passwords-for-future-employees.html) and countless more like this) 

Sadly we're now living in a crazy world where these heightened security measures may well be justified.

**Comment by ryanpcmcquen** [comment]
Secure by default, I like that.

**Comment by ryanpcmcquen** [comment]
Made a new issue to continue this discussion: #6
