### ISSUE TITLE
[Feature] [docs] default home page to reduce the time to load the page

### ISSUE THREAD

**Issue by l-lin** [cryptee/web-client#31]
**Is your feature request related to a problem? Please describe.**

I'm using cryptee on both my computer and my phone. However, I have some documents with extensive content (images, ...). In my computer, decrypting the document is fast, but my phone is not as performant as my computer, so the decryption can take a while (and can fail if the document is too large for my phone to handle).

Currently, cryptee docs loads the last opened document, so if I opened my "large" document in my computer, then later in the day, I open cryptee doc in my phone because I want to read another document, I have to wait the latest opened document to be loaded before I can find another document.

**Describe the solution you'd like**

Have a default home page on cryptee doc instead of loading the latest opened doc.
The default home page will be as lightweight as possible and will not decrypt any document content to reduce the time to load the page.

or

Always open the "Home document" by default (can be configured in the account settings).

**Comment by johnozbay** [comment]
Hey @l-lin! Thanks a lot for filing this! ✌🏻

I'll break this up and address in two parts.

**The Bug 🕷**
In general, whatever you can open on the desktop, you should be able to open on your phone without issues. If your phone's failing to load a document / crashing due to the document size, this sounds like an ugly bug. And one that I'll need some specific info to address. 

If you wouldn't sharing these pieces of info here on GitHub, can you let me know your phone's model & RAM specs, OS & version, browser & version? – If you'd prefer not to share publicly here, please reach out from https://crypt.ee/help with a bug report there, and mention "Github #31" somewhere in the message – I'll take it over from there. 

In addition, I'll need to know the size of the document you see on the top right corner. (Say for example 40mb etc)

**"Load by Default" 📑**
This is coming very soon, most likely with the next update or the following. 
You'll soon be able to choose between : 
Last Document [ default ] 
Home Document,
Cryptee News / Blog (few kb html, and unencrypted, so quite fast), 
Nothing / Blank Document,

This will be a locally-stored, device-only setting, so you can have 3 devices with different preferences. 

Can't comment on an exact release date, but either the upcoming update, or the one following it will have this feature. Will keep this thread posted. 

In the meantime, please reach out with specs & detailed info regarding the bug and I'll fix this ASAP.

Thanks ✌🏻

**Comment by l-lin** [comment]
I'm sorry, I expressed myself poorly. I did not encounter the "bug" on my phone (yet?) as most of my documents do not exceed 5Mb in size.

However, I do have some files that I uploaded with size about 100Mb. My computer can handle them (albeit slowly) but my phone do not. That's why I wrote "can fail if the document is too large" and I think it's possible the phone won't be able to load the document if it's too large (I did not test and I do not have such large document).
I don't think it's worth the trouble to fix such "bug" as >100Mb document is not what cryptee docs should be handling.

For information, I have a Honor 8 and the specs are the following: https://www.phonearena.com/phones/Honor-8_id10168

**Comment by johnozbay** [comment]
Hi there! No worries at all! 

Regarding large files, it makes perfect sense now! 👍🏻
I'm doing a lot of work behind the scenes to make large-file handling better. (incl things like using typed arrays or array buffers instead of strings, and stream-encrypting & stream-uploading in chunks, instead of a single file in memory etc.) hopefully soon even the slowest mobile devices will be able to handle encrypting/decrypting much larger files. 🎉

It's also going to take some work on browsers's side too like : [Firefox still doesn't support Streams API's Writable Streams ](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream), or [Chrome/Opera doesn't have streaming upload for Fetch API](https://bugs.chromium.org/p/chromium/issues/detail?id=688906) – but I'm following it all closely, and hopefully very soon file-size limitations will be a thing of the past. 🚀

And sounds like the upcoming changes to the default start-up loading behavior should address your issues. 🎉

**Comment by johnozbay** [comment]
Hey there! We've just released the Cryptee v3.0! ( 01edfe4 ) 🎉 
There's now a default home page in Cryptee Docs, and you can also configure Cryptee to skip home, and launch straight into Docs on your devices to save even more time! You can read more about this on our blog here : 
https://blog.crypt.ee/say-hello-to-a-new-cryptee

and even get to see it in action in my cheesy video there! Many thanks for this recommendation! I'll close this issue for now, but please feel free to re-open it if you'd like to see improvements in this area! 

Thanks for everything ✌🏻
