### ISSUE TITLE
[Feature] [docs] A4 doc representation

### ISSUE THREAD

**Issue by l-lin** [cryptee/web-client#32]
**Is your feature request related to a problem? Please describe.**
I'm using Cryptee doc to write letters. However, as cryptee does not display the document as a "A4 paper", I don't know if the content of my letter is filling one or two pages.
I have to export the document in PDF to know how many A4 paper my letter is filling, which is not convenient.

**Describe the solution you'd like**
Something like Google doc, i.e. displaying an A4 representation of the document.

**Comment by johnozbay** [comment]
Hi there! 

This is in the works, however it's a very VERY complicated topic with multiple moving parts, mostly related to the way PDF / Print-rendering works. 

1 – Almost all un-encrypted applications render PDF on their servers, because they have access to your unencrypted documents. So for example Google Docs, converts the rich text content into PDF on their servers, then points your browser to a link like docs.google.com/afile.pdf then your browser downloads this. 

However, because all encryption/decryption takes place on your device with Cryptee,
Cryptee can't simply give you a .pdf url to download from, since there isn't one on the server, all the server has is encrypted. So the server can't do any complex PDF rendering calculations. 

And because of this difference, Cryptee can only convert to PDF in your browser when the document itself is open, by first hiding all user interface elements on the page, then triggering the system print dialog on the page. 

2 –  Turns out, PDF is a very VERY complex and proprietary format, that keeps evolving and it's really difficult to render it in the browser. Most JS libraries out there are built for use cases like QR ticket-printing for concerts/flights etc, and work kind of like screenshooting the content on your screen into a canvas as images. So the text becomes un-selectable, and links won't work in PDF etc. 

And operating systems' built in PDF exporters take the entire HTML/CSS and renders that into a PDF really well. Which is why Cryptee's using this for now. 

3 – So to create an A4 preview, Cryptee would need to figure out font-sizes on different screen resolutions & displays (retina vs non-retina for example), different page margins, and different embedded image resolutions on virtual pages. 

That being said, every OS (and some browsers) renders fonts differently, and every OS, and even some browsers, have different ways of rendering PDFs on the print dialog in the first place. (Then add the multiple different international page sizes like US Legal vs A4 or A5 etc. this becomes increasingly more difficult)

So this turned out to be a very complex cross-compatibility & math problem, rooting originally from the on-device encryption, and I'm working on it, but it's going to take a while to figure this out.

Hoping these make sense ✌🏻
Will keep this thread updated! 

J

**Comment by l-lin** [comment]
Thanks for taking the time to analyze this request :+1:

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Just wanted to give you a quick heads up – we're making steady progress towards this and already shipped parts of this in v3. 
We have a relatively larger thread about the same topic going on in #58, so I'll close this issue and we can continue the conversation in #58! 

Thanks ✌🏻
