### ISSUE TITLE
Auto-ghosted Folders

### ISSUE THREAD

**Issue by mengledowl** [cryptee/web-client#33]
**Is your feature request related to a problem? Please describe.**

Needing to ghost folders by hand every time is problematic for plausible deniability, IMO.

The way I see it, if you're looking for plausible deniability, you're probably in a situation where you're **not going to know** if/when an adversary is going to force you to log into your account and show it to them. This means that you couldn't possibly predict when you'd need to ghost your folder(s). As a result, you need to remember to ghost your folder(s) every time you're done working with them. This is not ideal because:

1. It's extra friction
2. It might be a lot of work if you have numerous folders to ghost
2. It requires you to **remember** to do it every time you're done
3. It requires you to **have the time and opportunity** to do it every time

Why is the last one important? What happens if you're working on your document, and you get a 10-20 second warning before someone is attempting to force you to show them your account? With the right security settings, closing the window is enough to force you to re-enter your encryption key, which you would have time for, but you certainly wouldn't have time to ghost your folders.

**Describe the solution you'd like**

I would love to be able set folders to auto-ghost anytime there's an event that would force me to re-enter my encryption key. That would include things like: 

* signing out
* timing out,
* closing the window

**Disclaimer:** my understanding of the code and techniques being used here are somewhat rudimentary. I fully expect that it may not be as easy as just adding a flag and keeping them in an always-ghosted state on the server.

Here's my understanding of how ghosting works from reading, watching network tab, and looking at the code a bit (could be wrong):

Normally, your folders and their contents are encrypted with your key client-side, then pushed up to Firebase with an association to your user account. This allows you to pull the full list of folders tied to a user later.

When a folder is ghosted however, the folder name and contents are encrypted with the key and sent to Firebase with **no** association to the user. When the folder is summoned, you type the name of the folder, that folder name is encrypted with your key, which can then be used to uniquely identify and find the folder. The folder is returned to the client, which then turns around and sends the folder and its contents back to Firebase with the user association, effectively returning it to the state it was in before ghosting.

If I'm correct, I would think that it might be as simple as:

1. Add a flag to the folder, something like `autoGhost = true`
2. Do initial ghosting of the folder
3. When summoning, never perform the final step of re-associating the folder to the user's account
4. Remove all auto-ghost folders from the device when an event occurs that requires the user to input their encryption key again

Again, I may not be correct about how this is being done. If I'm not, please correct me as I'd love to know what's _actually_ going on. Either way, this is an awesome project and I'd love to see auto-ghosted folders added!

**Comment by johnozbay** [comment]
Hi there @mengledowl! 
This is a fantastic question!

While building ghost folders, I've spent ~2 months thinking about this exact feature, and tested the theory under multiple different scenarios, discussed with folks who are journalists and peace-workers overseas, and realized _auto-ghosting is not possible_ – because to make it possible you'd need to compromise even more, and make matters even worse. 

I'll break down how things work, how it has to work for privacy, and you'll understand why it's not possible to auto-ghost things as well. 

The only thing you're missing here is how filenames / folder names are stored on Cryptee, and that makes a huge difference. All your folder names and filenames, as well as your files' contents are encrypted on your device with your key, and your key never leaves the device. So, _only you know_ the names of your folders, and nobody at Cryptee can see your filenames / foldernames etc. thus, we're mathematically not able to hand over any plaintext (decrypted) filenames or foldernames even to a government with court-enforced legal data requests for example. 

Now with this in mind – 

📂 **Here's how you ghost a folder** 
Step 1) You click "Ghost a folder" 
Step 2) You confirm its name by typing it. 
Step 3) In order to be able to retrieve a ghosted folder to you by its name, the server needs to know the name of the folder. BUT. Remember, we don't want to know the names of your folders, especially your ghost ones. So what do we do? – In order for the server not to know your folder's name, your folder name is _hashed_ on your device. 

https://github.com/cryptee/web-client/blob/e6a0627587bf514057ea2463eed234f30b66899f/source/js/docs.js#L4296

Step 4) Your folder name's hash + folder id + user id is passed to the server. 

Step 5) [ server-side ] Server takes the folder name's hash (FNH) + user id (UID) and, hashes these two together to create a unique ghost ID (GID). –– So the server still doesn't know your folder name, nor can we look at the GID and be able to tell which user id it belongs to after it's hashed. –– All your folder's contents are copied to this ghost folder with the unique GID, and then the original folder is removed from your account. 

––  You've now successfully ghosted something. Now. Even if a govt comes knocking our door to say, hey, hand us over all the ghost folders of this user id, we can't do this. Because we can't find out which ghost id (GID) belongs to which user id, because we don't know the hash of the foldername, to hash with the userid and compare. So it's impossible to tell which ghost folder belongs to which user by looking at our server.

👻 **Here's how bringing back a ghost folder works.** 
Step 1) You type the name of the ghost folder. 
Step 2) What you've just typed, the name of the folder you'd like to bring back, gets hashed into a Folder Name Hash (FNH) on your device: 
https://github.com/cryptee/web-client/blob/e6a0627587bf514057ea2463eed234f30b66899f/source/js/docs.js#L4341
Step 3) and this FNH + userid (UID) is sent to server. 
Step 4) Server takes FNH and UID, then hashes them together to recreate the ghost ID (GID). If it can find a ghost folder with the GID, then it copies all the contents of this GID to your account, and deletes the ghost folder. 
Step 5) Your folder is back. 

**Now – here's why you can't auto-ghost folders on the server** 
(after you're logged out / close the tab / window / power off device etc.)

Because the server would need to know your foldernames, or hashes of their names, to be able to do this even after you're logged out. (Otherwise how else will it allow you to bring them back by typing their names) This would mean that either : 

a) server would need to know your folder names at all times = they're not encrypted = terrible for privacy, so can't be done.

b) server would need to know the hash of your folder names at all times = they're still not encrypted =  could be brute-force guessed by us, or by a govt if they have a hashed dictionary. (for example if your folder is called : "divorce" you can easily hash an entire dictionary of all languages to find common words like this.) = So pretty much as bad for privacy, so can't be done. 

c) your key would need to be sent to server so that server can decrypt your foldername and ghost it. = hell no. 
 
Therefore, there is no feasible way to make folders auto-ghost when you're logged out, because the foldernames, in their plaintext (decrypted) form, only exist on your device, while you're logged in, and your encryption key is in your device's memory. 

And the only way server can do this on behalf of you, is if it knows your folder names (or their hashes). And that's not okay, because the only way to achieve the level of deniability and privacy is if you're the only person who knows your filenames and foldernames. Any other way would be catastrophic for peace workers, journalists, lawyers, or folks in abusive relationships etc. where foldernames could be life-critical, but easily guessable.

–– finally it's not just a government this protects users from, but also hackers. If we could tell which ghost folder belongs to which user / and could hypothetically auto-ghost/auto-bring back folders, and some day if a hacker would manage to gain access to our backend, the hacker would theoretically be able to force-restore everyone's ghosts. not cool. But right now, due to the way things are hashed, this isn't possible either. So even if some day we're hacked, forced at gunpoint, or served a legal court order enforcing us to restore users' ghosts, we mathematically can't. 😎

**A hypothetical solution that wouldn't work**
There's one semi-feasible, hypothetical workaround to this problem. And that is for you to assign nicknames / safe-words to folders, which are safe for the server to know, instead of using the folder names to ghost/summon them. But this would cause an insane usability problem, us mortal humans would confuse or forget the foldername, nickname or safe-word and lose access to that folder forever. And security is only as good as practical usability. If things are not practical, users could make mistakes, and getting caught with ghosts would make manners even worse.

Hoping this makes sense, and I could explain the reasons why this isn't possible. 
If you can think of a solution please do let me know, but after spending months on this, and discussing this issue with others, I couldn't think of a way to make this possible without compromising some of the core privacy/security/deniability values of Cryptee.

**Comment by dhda** [comment]
I found this issue searching for information about how ghost folders are implemented and because I'm desiring a similar kind of feature. @johnozbay you've written about why server-side auto-ghosting isn't possible, but I'm not totally clear on why client-side auto-ghosting wouldn't be possible. Is it because apps (and probably especially PWAs) don't have any way to run code in the background when they exit, and that forgetting the encryption key isn't an active event that happens, but is actually a passive, implicit effect of the app's memory being cleared by the OS?

-----

As to server-side ghosting, I'm curious about this approach:

> b) server would need to know the hash of your folder names at all times = they're still not encrypted = could be brute-force guessed by us, or by a govt if they have a hashed dictionary. (for example if your folder is called : "divorce" you can easily hash an entire dictionary of all languages to find common words like this.) = So pretty much as bad for privacy, so can't be done.

Could you hash encrypted titles instead of plaintext titles? The server already knows those. Seems like that would eliminate the privacy concerns of storing foldername hashes on the server, unless there's a reason that ghost folders specifically require a hash of the plaintext title to work properly. It introduces the challenge of how to deterministically produce that encrypted title, though, so that it can be usable as a consistent hash. Maybe you could use HMACs (being used as basically a better salting function with a client-held-and-derived secret key)? An attacker would be able to determine that two folders of a specific user had the same title, but that may be an acceptable amount of information to leak.

As it is, couldn't an attacker with access to the database of all Cryptee ghost folders trivially run a brute force attack against a specific user (with known id) to determine the existence of a ghost folder (expecting ghosted folder names to be simple, short, and memorable)? Does the server at least do any salting of the ghost ids right now? If it's just storing hash(hash(folder name) | user id) that's pretty easy to brute force. It sounds like in the current scheme ghost folder names need to be treated like passwords in order to be secure, but having a long randomly generated password isn't effective because it would need to be stored (defeating the deniability), and memorizing a long enough secure phrase for just a folder name is a pain. That seems like a fairly plausible attack for a state actor to run against an individual.

_Side-note: the handling of ghost folders with identical titles is really interesting! Reading your description of the implementation I was curious if it would break. It actually works (I was surprised!) and after ghosting two folders with the same name, they are summoned one at a time in the reverse order in which they were ghosted. I was expecting the first ghosted folder to get clobbered, and I'm glad it doesn't._

Auto-summoning of folders seems to be clearly impossible, but I think that would be undesirable anyways.

-----

It sounds like the privacy and deniability properties of ghost folders already require users to put a lot of trust in the server to do what it says it's doing and not log anything that could reveal the existence of a ghost folder. If the Cryptee server were to be compromised, ghost folders wouldn't be effective anymore. A malicious server could log the incoming hash(folder name) and use it to prove the existence of a ghost folder or to brute-force its plaintext title.

**Comment by dhda** [comment]
I'm also interested in a related, middle-ground feature for ghost folders, which is some kind of emergency ghost-all-and-quit panic button that skips asking for folder name confirmation. It's not quite auto-ghosting, but would save a lot of time (speaking to @mengledowl's number 4). Supporting subfolders in ghost folders would also go a long ways towards reducing the time to ghost in critical situations.

**Comment by johnozbay** [comment]
Hey @dhda! 👋🏻

I think you should read a bit more about how AES 256 encryption and hashing works in general  there are a lot of deep confusions here. I'll write a lengthy answer below, and address your points one by one, so that in the future others who are curious about this could read even more about how ghost folders work. ✌🏻

---

> I'm not totally clear on why client-side auto-ghosting wouldn't be possible. Is it because apps (and probably especially PWAs) don't have any way to run code in the background when they exit, and that forgetting the encryption key isn't an active event that happens, but is actually a passive, implicit effect of the app's memory being cleared by the OS?

You're 100% correct. 
Once you type your key, and your folder-names are decrypted, both your key and decrypted / plaintext folder names are kept in memory. As soon as you leave the app, the memory is wiped, so there's no key nor folder-names in memory to work from anymore. Each time you launch the app, we decrypt folder names once again. This way, after you left the app, even if someone inspects your device, they can't get anything out of it. 

---

> Could you hash encrypted titles instead of plaintext titles?

No. This is the part where you should learn a bit more about AES256 / encryption and hashes in general. A quick 101 explanation would be : 

If you _hash_ `hello` you'll always get the same result, something like :
`2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824`

If you _encrypt_ `hello`, each time you encrypt it, you'll get a different result. 

This is so that even if you encrypt the same piece of text, 100 times, using the same key, all 100 encrypted results will look different from each other on the server. To learn more about this, you can read a bit more about [initialization vector](https://en.wikipedia.org/wiki/Initialization_vector), and the purpose it serves in encryption when you're using the same key.

So you can't hash an encrypted folder title. You'll get a different hash each time = you can't recover your folder. And pretty much everything else you wrote after that in the same paragraph would be invalid. 

---

> As it is, couldn't an attacker with access to the database of all Cryptee ghost folders trivially run a brute force attack against a specific user (with known id) to determine the existence of a ghost folder (expecting ghosted folder names to be simple, short, and memorable)?

> If it's just storing hash(hash(folder name) | user id) that's pretty easy to brute force 

To answer both – read Step 5 from my initial response above : 

> Step 5) [ server-side ] Server takes the folder name's hash (FNH) + user id (UID) and, hashes these two together to create a unique ghost ID (GID). –– So the server still doesn't know your folder name, nor can we look at the GID and be able to tell which user id it belongs to after it's hashed. 

In addition to that response above: 

1 – Ghosts are stored on an entirely different server & database, in an entirely different geo-political region, to make it even more difficult to piece together information via legal-means without causing an international political shit-show. 
 
So the hypothetical attacker would have to compromise two different databases. One to get all Ghost IDs (`GIDs`) and another to get all User IDs (`UIDs`). (and we're talking server generated unique user-id's not usernames here)

2 – They would then need to: 

a) Hash every possible Folder Name in existence in every possible human language. 
_(hash operation number 1)_ 
Store these trillions and trillions of Folder Name Hashes (`FNH`)

b) Then take all possible random generated `UIDs` in existence, and all these trillions and trillions of `FNHs`, and hash them together once more time to get Ghost IDs (`GIDs`).
_(hash operation number 2)_

Due to the double hashing, the difficulty is increased exponentially. 

c) They would then need to compare these trillions  ... trillions ... trillions of `GIDs` to `GIDs` that are in the database. To hopefully find whether if a user has a ghost folder or not. 

This task would take SO LONG, and require so much time and computational energy, that [they're better off trying to hack your devices by other means](https://xkcd.com/538/). 🔧

Even if they manage to do all that, they would only discover that you have ghosts. That's it. They still can't open anything, because the contents are still encrypted with your key on your device. 

So I'd respectfully argue that this would take insane amounts of effort, all to find whether if there's a ghost folder named "`apples`" that belongs to user id : `1234567890` 🍎😅

So to address this specifically : 

> If it's just storing hash(hash(folder name) | user id) that's pretty easy to brute force.

I'm curious to hear why/how you think this would be easy given the double hashing. By its very nature hashes are built to be slow, so we're talking about an incredibly long and exponentially slower process here. 

---

> Does the server at least do any salting of the ghost ids right now?

You cannot salt. 
If you use a random salt each time, every time you hash the same folder name, you'd get different hashes = you can't recover the folder. This means you'd need to store the generated random salt for each ghost folder somewhere in a table.
 
If you store this salts table on the server: 
server will know you have a ghost folder, its GID, and its salt. = this means the server would need to know way more than it does right now. = defeats the purpose.

If you store the salts table on client side & encrypt them:
You'd reveal that you have ghost folders on the client side (and that would defeat the whole point of ghost folders. which is to ensure, even if someone can gain access to your device / account, they can't find out whether if you have ghost folders or not = plausible deniability) 

---

> That seems like a fairly plausible attack for a state actor to run against an individual.

Read our [Threat Model](https://crypt.ee/threat-model) > Recommendations & Use Cases

https://github.com/cryptee/web-client/blob/9e403e8e88d2e1d423eab67bf5fe20de48848190/source/threat-model.kit#L81

If you're concerned that a nation state actor would try to compromise an entire infrastructure, to target you alone, use dedicate a supercomputer to brute force through hashes of all possible folder names in existence in all languages hashed to all usernames in existence, then you have way bigger problems than them knowing whether if you have a ghost folder named `apple` or not. They're better off targeting you individually, and they'll save time and money. 

---

All in all, this is a feature built to provide you, the user, plausible deniability. And I've built it in a way that team Cryptee can't see your folder names, and even if a govt comes asking us via legal means, we can't provide any info on whether if you've got ghost folders or not. That's about it. 

So to summarize things : 

we still don't know your folder names, 
we still don't know if you have ghosts, 
we still can't give info to a government asking for information via legal means, 
and there's no way to brute-force for ghost folder names from client side via manual/automated means. (Servers will time out for 5 seconds at minimum if you enter an inexistent ghost folder name, and block the account altogether after too many quick & consecutive attempts.)

If a state actor decides to target you _personally_, and send their intelligence arm after _you_, then you've got bigger problems here, and you should re-consider your personal threat model. 

---

> Side-note: the handling of ghost folders with identical titles is really interesting! Reading your description of the implementation I was curious if it would break. It actually works (I was surprised!) and after ghosting two folders with the same name, they are summoned one at a time in the reverse order in which they were ghosted. I was expecting the first ghosted folder to get clobbered, and I'm glad it doesn't.

Ha! I'm so glad you've discovered this! 🎉 This is a feature I intentionally didn't want to advertise on the landing page (to provide even more deniability), but I hoped and assumed those who need this would personally discover and use it just like you did 😅 haha 

Basically, while hashing, the server also checks to see if the GID already exists before it writes it, (so that it won't accidentally overwrite something) and adds "-1", "-2", "-3" etc. at the end of the GID hash. And when you're retrieving it's retrieved in reverse order. 

This way, you can even bury a ghost folder 100s of folders deep to increase difficulty. So for example in an abusive relationship, you can bury the real "divorce" folder 4 - 5 fake "divorce" folders deep, and utilize this to gain even more deniability if an abuser asks you to type "divorce" into the summon box. The first 4 - 5 "divorce" folders they summon would be a fake / blank one etc. 🎉 😎

---

> If the Cryptee server were to be compromised, ghost folders wouldn't be effective anymore. A malicious server could log the incoming hash(folder name) and use it to prove the existence of a ghost folder or to brute-force its plaintext title.

There are two important things to remember here. 

1 –  If you need the deniability ghost folders provide, this means _you don't trust your own device_ in the first place, and you're worried someone might login to your account / device, and try out folder names, so you hide them using ghosts. 

Therefore you are instead trusting the server to keep a secret for you, because you don't trust your own device.

So all scenarios that require you to store any information regarding ghost folders on your device is already out of the picture.

And perhaps most importantly, if the server is compromised :

2) The contents of the folders are still encrypted on your device. 

We're only talking about the folder name `apple` belonging to user id `1234567890`. That's it. Nothing else. Neither the contents of the folder, the documents' names, nor the documents' contents etc. those are all encrypted.  

So think about that for a second, we're talking about a feature built to defend against an adversary who has access to your device/account, so much so that you use ghost folders to hide something in your account. So a compromised device/account AND a compromised server. Once again picking the correct model for yourself is super important here. 

---

> I'm also interested in a related, middle-ground feature for ghost folders, which is some kind of emergency ghost-all-and-quit panic button

So here comes the 100$ question. Where do you store the ids of all folders that needs to be ghosted?

Client side? (Remember, we don't trust the user-device here) 
– This means anyone who has access to your account / device can see your "panic ghost list". 

Server side? (Remember we don't want the server to know you have ghosts either)
– So we can't even instruct the server to ghost your folders on your behalf once you leave. It doesn't and can't know you have ghosts. 

Basically what I'm trying to describe here is that if your threat model is : 

a) "I don't trust my abusive partner / work laptop etc, so I need to ghost and hide stuff from my partner / boss" – then great! = use ghost folders. 👍🏻🎉

b) "I don't trust my device, idk if it's hacked" – read Cryptee's threat model. We can't protect you on a compromised device, since they can steal your encryption key or log your keystrokes too. But if you have pre-ghosted folders, and you haven't entered their names after your device is compromised they still can't find out. 👍🏻🎉

c) "What happens if Cryptee's servers are hacked?" – your data is encrypted on your device, and they can't get hold of anything usable about you. Worst case scenario, if you have ghosts, and the attackers have insane super-computing resources, years and years of time, and patience, they can learn a folder named `apple` belongs to userid `1234567890` by brute forcing. 🍎👀
 
d) "I don't trust my government, idk if they do mass surveillance" – no problem, we're most likely out of their jurisdiction, and if they come to ask us with a court order, we can't give them anything. 🍷 

e) "I don't trust my government, and idk if they would send their intelligence division after me" –  [Historically, chances are very high that they'll first come knock _your_ door](https://www.theatlantic.com/magazine/archive/2020/06/edward-snowden-operation-firstfruits/610573/), not ours. It's easier, cheaper & faster for them in every way.

---

> Supporting subfolders in ghost folders would also go a long ways towards reducing the time to ghost in critical situations.

You're in luck with this one! I'm looking into and actively working on this. It's harder than I initially anticipated due to all the edge cases. 

Like: 

Should you be able to summon a sub-folder without its parent? 
If so, where should it go when it's summoned, since its parent is ghosted? 

What happens if you ghost a sub-folder, then while its ghosted, delete its parent. 
When you summon this sub-folder where should it end up? 

What happens if you have a ghost folder named "apple" and one of the 1000s of sub-folders have a folder called "apple"? 

etc. etc. tons and tons of edge cases like this 😩 but it's coming along. I don't know how long it will take, but I'm working on it. ✌🏻

I hope these make sense, and I could explain all the many reasons why I made things the way they are without being too geeky or too boring here 😅

Thank you so much for the fantastic questions and all your help on GitHub! Cryptee's getting better and better with all your bug reports and help, and suggestions! 🙏🏻

Best,
J

**Comment by dhda** [comment]
> No. This is the part where you should learn a bit more about AES256 / encryption and hashes in general. ...
> ...
> So you can't hash an encrypted folder title. You'll get a different hash each time = you can't recover your folder. And pretty much everything else you wrote after that in the same paragraph would be invalid.

I offer "encrypt then hash" as an intuitive starting point of a solution to your point b) from your first response in this thread, not as a literal suggestion to `hash(openpgp.encrypt(...))` the folder titles.
AES is not synonymous with encryption–it's a block cipher, it's deterministic, and it doesn't actually have any knowledge of Initialization Vectors. The modes of operation are where IVs come in (Electronic Codebook is the deterministic mode). The page you linked on Initialization Vectors explains all this.
I explicitly addressed this point of getting a different hash each time when i wrote of the need to use a "deterministic encryption" for this particular use case of folder titles.

Encrypting with a zero IV and block cipher and taking the last block happens to be exactly how [CBC-MAC](https://en.wikipedia.org/wiki/CBC-MAC) and [CMAC](https://en.wikipedia.org/wiki/One-key_MAC) are implemented, by the way (don't use CBC-MAC for variable-length messages, though). HMAC is a keyed hash function, and another MAC. It has the properties of typical hash functions, but will additionally prevent any kind of dictionary attacks from being effective. OpenGPG.js has a wrapper for CMAC, and HMAC is supported in WebCrypto. Either would work! Using a MAC as an index like this isn't what it's usually used for, but I think it would provide exactly the properties needed for ghost folders.

Derive a secret key from the clients encryption key and then use that as the key to HMAC: `HMAC(derived_key, folder_name)`–and voilà, you have a deterministically computed Folder Name Hash that is safe from dictionary attacks, that only the user can compute, and that would be safe to store on the server for purposes of auto-ghosting. Like I said, the leak introduced in this scheme of storing FNHs on the server is that an attacker could see that two folders on a user's account have the same MAC value, which is a reduction from the way things currently are when everything is fully encrypted, but seems like it could be an acceptable trade off for an auto-ghost feature. If we're talking about an attacker who can observe the server and DB, they can already observe the incoming Folder Name Hashes, so I'd argue that this is a minimal reduction in security.

Conceptually a MAC also makes sense here: when a user requests to unghost a folder, for example, requiring them to provide `HMAC(folder_name, secret_key)` is a cryptographic guarantee that they are truly the person who originally ghosted that folder. `sha256(folder_name)` is forgeable, `HMAC(folder_name, secret_key)` is not.

> b) server would need to know the hash of your folder names at all times = they're still not encrypted = could be brute-force guessed by us, or by a govt if they have a hashed dictionary. (for example if your folder is called : "divorce" you can easily hash an entire dictionary of all languages to find common words like this.) = So pretty much as bad for privacy, so can't be done.

You are explicitly referencing brute force attacks (including by a government) here as to why auto-ghosting folders would be impossible–I'm offering a solution to this concern.

-----

> I'm curious to hear why/how you think this would be easy given the double hashing. By its very nature hashes are built to be slow, so we're talking about an incredibly long and exponentially slower process here.

Noooooo! Hashes are *fast*. *Password hashes* (usually built on Key Derivation Functions) are built to be slow, and one of the ways they can do that is by running hundreds of thousands of rounds of hash functions like sha256... On the client you're hashing with a single round of sha256 (https://github.com/cryptee/web-client/blob/51cd8bc43216f18a612a9cdab0a40a4dd146fa28/source/js/main.js#L1230) and I'm assuming the ghost ID hash on the server is computed with another single round of sha256. Double hashes double the time it takes to compute, it's not an exponential increase.

> a) Hash every possible Folder Name in existence in every possible human language.
> (hash operation number 1)
> Store these trillions and trillions of Folder Name Hashes (FNH)
> 
> b) Then take all possible random generated UIDs in existence, and all these trillions and trillions of FNHs, and hash them together once more time to get Ghost IDs (GIDs).
> (hash operation number 2)

The search space is not the same as finding arbitrary hash collisions. You yourself named dictionary attacks in your first response.

A modern GPU can compute somewhere around 3000M hashes/sec (that 3 billion/sec). My laptop with an 8 year old cpu can compute `sha256(sha256(name) | user_id)` for a single user_id for all 240000 words in `/usr/share/dict/words` in about 1 second, using the python standard library, with a slow naive implementation, and lots of slow file IO, on a single thread. Hashes are fast and this is a very achievable attack!

This is the reason that you need to use password hashing functions like PBKDF2 or scrypt for storing passwords. Two rounds of hashing is nothing when it comes to dictionary attacks. And dictionary attacks are likely to be pretty effective for ghost folders–who uses anything other than relatively simple combinations of a few dictionary words for folder names? I doubt many users are going to treat their ghost folder names like passwords. I even understand the potential vulnerability of this and I'm still not going to treat them like passwords, because it would make actually using the feature a huge pain. An attacker doesn't need to hash every possible string in existence to mount an effective attack.

-----

> 1 – Ghosts are stored on an entirely different server & database, in an entirely different geo-political region, to make it even more difficult to piece together information via legal-means without causing an international political shit-show.
> 
> So the hypothetical attacker would have to compromise two different databases. One to get all Ghost IDs (GIDs) and another to get all User IDs (UIDs). (and we're talking server generated unique user-id's not usernames here)

This is great! And great to know, thanks for sharing this piece.

> and there's no way to brute-force for ghost folder names from client side via manual/automated means. (Servers will time out for 5 seconds at minimum if you enter an inexistent ghost folder name, and block the account altogether after too many quick & consecutive attempts.)

Also great 👍 

-----

> You cannot salt.

This makes sense–I didn't think that through enough.

-----

> So here comes the 100$ question. Where do you store the ids of all folders that needs to be ghosted?

Just ghost all of the folders that are currently visible to the client or are in a users account?

You pointed out a bunch of other practical concerns beyond the technical details, which I totally hear. You can't just store a persistent list of folders to auto-ghost somewhere, and it feels like a huge point of friction (and an easy thing to forget to do or to mess up) to have users go through and mark which folders they want to have auto-ghosted every time they log in (though I'm sure that would work for somebody, somewhere 🤷‍♀️). So I think the feature would be limited to auto-ghosting all folders except for the Inbox, and requiring users to manually unghost the specific folders they want to work with every time they log in. They'd have a seemingly "blank slate" every time they logged in. It'd be like a super-paranoid mode.

-----

> could be brute-force guessed by us, or by a govt if they have a hashed dictionary

> finally it's not just a government this protects users from, but also hackers. If we could tell which ghost folder belongs to which user / and could hypothetically auto-ghost/auto-bring back folders, and some day if a hacker would manage to gain access to our backend, the hacker would theoretically be able to force-restore everyone's ghosts. not cool. But right now, due to the way things are hashed, this isn't possible either. So even if some day we're hacked, forced at gunpoint, or served a legal court order enforcing us to restore users' ghosts, we mathematically can't. 😎

You gave these arguments for the impossibility of the server auto-ghosting your folders, and I'm responding to them. Are they part of your threat model or not?

-----

By the way, how are you hashing user account passwords?

**Comment by dhda** [comment]
Hash cracking is fun, so here's some numbers to demonstrate the scale. 250000 words is a decent average for # of words in many languages. Let's say we're targeting a user who speaks five different languages!

If we want to try a likely first target, an attacker might try every combination of two dictionary words with all possible capitalizations of the first character of each word. That's:

(2 \* 5 \* 250000) ^ 2 = 6.25 trillion folder names
6.25 trillion names * 2 hashes = 12.5 trillion hashes
12.5 trillion hashes / 3 billion hashes/sec = 4166 seconds ~= 70 minutes

70 minutes to compromise some of a single user's ghost folders with probably a pretty decent success rate, using single desktop GPU. Some imaginary attacker with access to some kind of supercomputer GPU cluster would rip through your database. The first pass of hashing possible folder names can be cached into a rainbow table. Also, the more ghosts you can compromise, the fewer uncompromised ghosts exist in the db, which would make those easier to target or associate with a specific user id.

**Comment by johnozbay** [comment]
Hey hey! 👋🏻
First off – Forgive the tone of my initial response, not knowing whether or not if you're familiar with cryptography in general I didn't get into too much detail, so I wrote things more abstract than I should have. And I hope it didn't come off too strong, or too shallow, my apologies! 🙏🏻

You've made some fantastic points! Thank you so much for this conversation! 

---

> Derive a secret key from the clients encryption key and then use that as the key to HMAC: HMAC(derived_key, folder_name)–and voilà

After writing yesterday, I checked my notes on why I didn't make things this way in the first place. Because it makes perfect sense! My note-to-future-self reads this : 

a) HMAC derived keys would still need to be stored somewhere, revealing that the user has ghosts. (similar to the problem with salts)

b) if the derived key is stored only on client side, then if user changes devices, they would lose all access to all ghosted folders.

c) if the derived key is encrypted on client side with user's key, and stored on server to be retrieved on login, both server & client side would know user has ghosts. 

–– reading back my notes on this, and now that I think about it again after 3+ years, there's actually one way this could work.

If every user automatically gets a derived ghost key on signup. This way, accounts with ghosts and accounts without ghosts would be completely indistinguishable, neither server nor client can know if a user has a ghost, and would provide the level of deniability we're after. I don't know why I didn't think of this approach before, and I can't find another note-to-self about this either. 
 
> Using a MAC as an index like this isn't what it's usually used for, but I think it would provide exactly the properties needed for ghost folders.

Overall using HMAC like this makes perfect sense and fits the purpose quite well as long as we can still assure deniability. It's an excellent improvement indeed, one which evidently I didn't think of long enough, and should have thought of more.

I'm going to think about a strategy to roll this out and make this happen. It will take a while, and will have to be a slow and gradual roll-out. New signups would get the key automatically, existing users would get the key next time they login after they get the update, we'll version the ghost/summon APIs.

This is a great idea! 🙏🏻

---

> You pointed out a bunch of other practical concerns beyond the technical details, which I totally hear. You can't just store a persistent list of folders to auto-ghost somewhere, and it feels like a huge point of friction (and an easy thing to forget to do or to mess up) to have users go through and mark which folders they want to have auto-ghosted every time they log in (though I'm sure that would work for somebody, somewhere 🤷‍♀️). 

This practical / real-life implications part of ghost folders is what made things a lot more difficult to decide / build indeed. 😅 There are many non-technical angles to consider and they complicate things greatly from a technical perspective. Like the inability to store ghost-lists etc.

> So I think the feature would be limited to auto-ghosting all folders except for the Inbox, and requiring users to manually unghost the specific folders they want to work with every time they log in. They'd have a seemingly "blank slate" every time they logged in. It'd be like a super-paranoid mode.

I've spent weeks thinking about this specific use, and even asked peace workers and activists whether if they would like this or need this. And they said this is super risky. – there's many practical & legal problems with it. (And I've even built some guard-rails to protect users against some edge cases)
 
1) If your account appears _completely_ blank – but you seem to be using 100gb of storage, it would reveal that you have ghosts. So it's better to have some stuff in the account, and not keep it completely empty. 

2) Legally, the overwhelming consensus is that, border agents could view deliberately hiding data from them as illegal.[[link to eff](https://www.eff.org/wp/digital-privacy-us-border-2017)] and having a blank account with used storage would be a giant red flag.

I've also assumed that a malicious actor could take the extra-effort and delete all visible files & folders, to see if the account still shows "using 50mb" for example, to find out whether if there are ghosts.

So to address this problem, I've made it so that used storage ramps down slowly, and not immediately when you delete files. In addition if you have paid accounts, the last few 100mb goes down sloooowly over the course of 24 - 48 - 72 hours to make it very difficult to figure out if someone has a ghost by watching it. 

In addition, I assumed that someone who learns about this would try and upload stuff to fill up the storage quota, and could also try that angle to figure out if there are ghosts. To make things harder, I made it so that all users can upload a little past their storage quotas! (even free users) – so even if you exceed your quota while uploading, upload isn't interrupted. This is intentional. So on a 100mb free plan, you can theoretically store 120 - 150mb etc. (and it's random each time to make it even more difficult) 

But all in all, having an empty account with ghosts is a bad idea practically, and [potentially] legally. 😕

---

> This imaginary attacker with access to some kind of supercomputer GPU cluster would rip through your database.

It's really important to remember that the reason why someone would use ghost folders, is if they don't trust their own device / an abuser is standing next to them and coercing them to unlock their account / abuser has access to the device & key. The main (and best) use case I built this for, is to hide something briefly if you suspect you might be under duress to access their account. But _not_ keep things ghosted 24/7, and only retrieve when you need them. This is basically the same as trying to hammer a nail using a plier. Like yes, you could do it, but it's simply not what the tool is built for. And you could hurt yourself doing it.

With this in mind – it's important to highlight what we're trying to protect from here. Is it someone who's standing next to you, threatening you to unlock your account? Or is it someone who has access to a supercomputer GPU?

Because the only way the math you wrote checks out is if the attacker is both. Meaning that the user ghosted something because they're worried about the physical safety of themselves / device AND the attacker hacked both servers/databases, and can brute force through with a supercomputer all while the folders are ghosted.

> 12.5 trillion hashes / 3 billion hashes/sec = 4166 seconds ~= 70 minutes

So this is if both the user ids server and our ghosts server is breached, attacker has access to all ghost ids & user ids, a user is being targeted individually, and the attacker knows the specific user id. (and practically speaking, the user doesn't trust the device, or is under duress, and decided to ghost stuff in the first place)

The part I was referring to by how slow it would be to brute force, is if you're trying to bulk scan to find out which users have ghost folders OR mapping out which ghost belongs to which user via means of brute forcing. Since the function is : 
`hash(folder name hash + unique user id)`

Based on your math, that would be 6.25 trillion folder names * number of users (since you'll need to test them against each and every users' id to get a match to find out which users have ghosts / which ghost belongs to which user etc.)

So at 100k users that's 100k unique user ids: 
6.25 trillion * 100k = 6.25e17 (625 quadrillion)

at 1m users that's : 
6.25 trillion * 1m = 6.25e18 (6 quintillion 250 quadrillion)

So 6.25e18 / 3 billion hashes/sec = 2083333333 seconds = 24112 days = 66 years.

---

> By the way, how are you hashing user account passwords?

Account passwords are hashed and salted using [scrypt](https://www.tarsnap.com/scrypt.html). 

---

I hope this all makes sense, and I'm not deviating too much from the main topic here ✌🏻
Thanks a lot for this constructive thread btw! Deeply appreciate the time you're taking to discuss ideas & help Cryptee get better!
