### ISSUE TITLE
[Feature] Breadcrumb navigation for Docs

### ISSUE THREAD

**Issue by Visual-Notes** [cryptee/web-client#38]
At the moment when a page is open, you actually have no idea in which folder this page is located. 
I think it would be very useful if a breadcrumb navigation was positioned above the editor bar. 
The location would be convenient because for breadcrumb navigations mainly the width is important. The small loss of space by the height the bar is more than justified by the advantage of the useful feature, I would say.

What do you think?

**Comment by johnozbay** [comment]
I think this is a good idea, but I think it would make the editor's main view very crowded, especially if the folder and file both have long names. 

For example, if you take something like : 
> Rechtsschutzversicherungsgesellschaften

One of the longest German words that can be used day to day, which roughly translates to something like : "insurance companies providing legal protection", – I always use this word internally to test if something will break the user interface 😅 – You can easily see how it could make the user interface really crowded if typed out large on the main editor view. 

And now imagine adding a long German folder name in front of that: 
> Kaftfahrzeug-Haftpflichtversicherung

Which roughly translates to "motor vehicle liability insurance", and you'll end up with a massive:
 
📁 Kaftfahrzeug-Haftpflichtversicherung > Rechtsschutzversicherungsgesellschaften
(motor vehicle liability insurance > insurance companies providing legal protection)

Initially, while designing Docs, I looked at how other editors handle this problem. If it's a desktop app like Pages / Word etc, they simply don't show a breadcrumb navigation, since they rely on the file explorer of the OS, or show it in the title bar depending on the application. For example VSCode shows a breadcrumb, presumably because it's a lot more common to have files with same names while coding (like `index.js`) so it helps figure out which `index.js` is open.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/611338/74831162-58f79900-531d-11ea-96ba-2aa7e8ce68c2.png">

If it's a web app, I think Google Docs's approach with this is the best one. They have this on the top : 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/611338/74825422-94409a80-5312-11ea-9279-fe95927bb05a.png">

Where you can only see the open document's name, but not the entire folder path leading to it. 
And I can sort of agree with this approach. 

In context, bearing in mind that Cryptee Docs is an editor, I think it's best to make it so that the full breadcrumb only shows in an info popup/modal, similar to the way Mac OS X Finder shows info about a file, like this : 

<img width="467" alt="image" src="https://user-images.githubusercontent.com/611338/74831651-53e71980-531e-11ea-8ae0-cafbed1d8834.png">
 
So in a way, I think this will go along perfectly with #39. I can put an info button ( ℹ️ ) next to the document's name, and if you hover or click on this, it would show the full path / breadcrumbs in a mini pop-up or modal. 

What do you think? 
Would this work for your use case?

**Comment by Visual-Notes** [comment]
> I think this is a good idea, but I think it would make the editor's main view very crowded, especially if the folder and file both have long names.

Look how Notion solved that problem. For me this is the best working solution, a sophisticated strategy of how to abbreviate the names (of pages in this case, but with documents it would be the same). No matter how narrow the browser window is, the breadcrumb navigation is still fully functional and you can see where the page is located despite the abbreviation of the names.
 

![breadcrumb_navigation_01](https://user-images.githubusercontent.com/1451511/74833863-9d356a00-531a-11ea-8a76-658aebef470d.png)

In a narrow browser window:

![breadcrumb_navigation_02](https://user-images.githubusercontent.com/1451511/74833873-a1fa1e00-531a-11ea-9bf8-a8735bc645f5.png)

**Comment by johnozbay** [comment]
In the context of the screenshot you've sent it makes perfect sense that they have a breadcrumb because: 

If you click on "Third sub..." in the breadcrumb, this would open another (parent) page named "Third Subpage with a very long name". A page (the parent) in this context, is something editable _in the editor view_. Therefore it makes sense to have a breadcrumb _in the editor view_.

Whereas in the context of Cryptee Docs, a document's parent can only be a folder, which is not something one can edit in the editor view. (unlike notion) – Therefore it doesn't make sense for the entire folder path to exist _in the editor view._ I'd even go so far to say it's bad UX design, and would unnecessarily clutter the interface. 

Since with Cryptee Docs, none of the actions you can take on the breadcrumb will effect the editor view, it would perhaps make more sense for a full path breadcrumb to be visible in the navigator view on the left. So for example, with a breadcrumb on the left, if you click on a folder, this action would open that folder. 

---

Additionally, when writing, for attention & focus, it's really important to only see the text you're reading/writing, and no other piece of text / labels. There's some great research[[1]](https://ieeexplore.ieee.org/abstract/document/7889580) and UX experiments about this exact topic. 

While designing Cryptee Docs, I've read a bunch of research papers and articles about this and decided to design the interface around this concept as much as possible. 

So centered editor, and no always-visible text or text-buttons (with the only exception of font selection, and I'm thinking of making that an icon too in the next update). 

And for parts where you need to see other pieces of text (such as a list of documents or table of contents), the virtual "paper" slides left/right and reveals it under / around the "paper", making it especially easy to separate the content of the editor from the content outside the editor. 
 
I hope this makes sense and I could explain what I'm thinking.
I think in the context of Cryptee Docs, it makes a lot more sense to have the breadcrumb on the left, or in a pop-up somewhere.

**Comment by Visual-Notes** [comment]
I see. I think I may have misunderstood the concept of cryptee a little. Your explanation has clarified that now, thank you!

**Comment by johnozbay** [comment]
In general for Cryptee, the concept is: a safe and encrypted place for personal digital belongings. For now, there's only Docs and Photos, but there's two more apps on the way for this year. 🤞🏻 

As for Cryptee _Docs_ the best way to think about it is similar to Word / Pages / Google Docs etc. but an encrypted and private alternative, with unique features tailored towards security & privacy. (like ghost folders)

The earliest / first version of Cryptee used to [look a lot more like Evernote or a note taking app in general](http://crypt.ee/imgs/old/docs-pdf.jpg). So I think the first wave of early adopters started using it that way. – but as the platform matured, I've started chatting with the customer base more, and understood that there's a much greater privacy need for more complex document-editing, and I've started building & designing Docs around this. 

I'm also working on a dedicated note-taking & journaling app for Cryptee, which starts up instantly and works way faster, but with less & more specific editor features. I think that many users will find this more suited for quick daily note-taking. 

Hoping these make sense!

**Comment by Visual-Notes** [comment]
> I'm also working on a dedicated note-taking & journaling app for Cryptee, which starts up instantly and works way faster, but with less & more specific editor features. I think that many users will find this more suited for quick daily note-taking.

Wow, that sounds extremely interesting! This would make Cryptee even more versatile!
Unfortunately there are not many options regarding note apps at the moment, if the focus is on security.

**Comment by johnozbay** [comment]
I agree! I think there's a great need for this. But again, this will have to have a very limited feature-set compared to Docs. For example, the PDF-viewer in Docs alone is ~2,2mb javascript. 
(https://github.com/cryptee/web-client/blob/v2/source/js/lib/pdf.js)(https://github.com/cryptee/web-client/blob/v2/source/js/lib/pdf.worker.js)

And I'm not even talking about MSFT Word compatibility, Markdown, Fonts, etc. These all affect initial start-up times negatively, and also the reason why apps like Cryptee Docs or Google Docs take a few seconds to start. I think having a tailored private note / journaling tool will address all these performance & practicality related issues.

**Comment by chriskfwoo** [comment]
> > I'm also working on a dedicated note-taking & journaling app for Cryptee, which starts up instantly and works way faster, but with less & more specific editor features. I think that many users will find this more suited for quick daily note-taking.
> 
> Wow, that sounds extremely interesting! This would make Cryptee even more versatile!
> Unfortunately there are not many options regarding note apps at the moment, if the focus is on security.

@johnozbay Agree! This would be useful. Whats the status of this development? Thanks :)

**Comment by johnozbay** [comment]
@chriskfwoo Happy to hear there's interest! 🎉

> Whats the status of this development? 

The best answer I can offer for now is : In-development. 
It's hard to give a timeframe or percentage at this stage 😅
– Partly because since the beginning of February, the user base has been growing non-stop at an insane +9%/week rate. So had to briefly shift gears into spending more time on things like server & API speeds, service availability, smoother on-boarding, helpdesk articles etc.

**Comment by johnozbay** [comment]
Hi there! Today we've released Cryptee v3.0, and it's a complete remake of the application! ( 01edfe4 )
We now have a completely new navigator, and it has features like "go one folder up" or "open the folder containing the document" etc. 

It's not a direct breadcrumb navigation per-se, but we think it will satisfy 90% of the use cases! Give it a try and let me know! 

For now I'll close this issue, since we've shipped a very similar feature, but please share your thoughts and ideas, and we'll gladly improve this feature in the following few months! 

Thanks all ✌🏻
