### ISSUE TITLE
[Feature] Show the name/title of a document at its top

### ISSUE THREAD

**Issue by Visual-Notes** [cryptee/web-client#39]
Currently, when a document is open, you have no idea what its name/title is. I think it would be useful if the name/title of document would appear at the top left of a document.

What do you think?

**Comment by ghost** [comment]
I agree, this would be very useful!

**Comment by johnozbay** [comment]
Agreed. I will start looking into where the best place would be to add this, and make it happen. 
Linking this to #38, I think these two features would work very well together.

**Comment by johnozbay** [comment]
Hi there both! 

Today we've released Cryptee v3! ( 01edfe4 ) and it has a dedicated document info box on the right side, where you can see the name of the document, the folder containing the document, as well as a bunch of other information. 

![image](https://user-images.githubusercontent.com/611338/108633798-f3357400-747e-11eb-98d2-360de4c61856.png)

You can not only see the name of the document there but also, click on its folder to open the folder, and navigate to its folder tree.

For now I'll close this issue, since we've shipped a very similar feature, but please share your thoughts and ideas, and we'll gladly improve this feature in the following few months!

Thanks all ✌🏻
