### ISSUE TITLE
Cannot embed second image in document.

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#4]
The first one embedded correctly, but the second just says 'Attaching ____ to document.', but never appears.

**Comment by johnozbay** [comment]
This does sound like a bug, and _I think_ I've already fixed this in the upcoming version. It had to do with the area that accepts dropping files, which changed with the new design etc. so I think it's already fixed. Will test against the new version now. Can you tell me which OS / Browser / Version this happened in, and the format of the images ? (Was it JPG / PNG / WEBP or something else?)

**Comment by ryanpcmcquen** [comment]
Linux/Firefox/latest. PNG.

**Comment by johnozbay** [comment]
Thanks a lot! 🙏🏻Will prepare a test today and keep you updated!

**Comment by johnozbay** [comment]
This should be fixed in b33a7c3498c628847693b2750342060bc06d4859 - let me know if it comes up again 😎

**Comment by ryanpcmcquen** [comment]
Still not working in Linux/Firefox/latest.

**Comment by johnozbay** [comment]
All the tests seem to passing, on my end with the exact tech-specs.
Just so that I can create the exact test case scenario on my end, could you describe how it happens step by step? Asking because there's 3 different ways you can embed images.

1) Drag and drop into the document
2) Click embed image icon on top of the editor, then select an image from Cryptee
3) Click embed image icon on top of the editor, then select an image from your computer

Then the combination of these three for the second round of embed. 

And tested all three with a combination of all three - and it seems to be working on my part!

I'm suspecting this may have to do with the way firefox handles scrollbars and the new layout hiding these scrollbars for vanity. (so there's a small chance that the whole embed image from computer modal isn't being displayed correctly)

It should look like this : 
<img width="300" alt="screen shot 2018-10-11 at 12 14 36" src="https://user-images.githubusercontent.com/611338/46793821-4182c600-cd4f-11e8-8a15-ba76a3454803.png">

Not a fan of this uploader's UI / UX in general btw. Put this together super quickly in the early days of building Docs 1.0 - Changing this is quite literally the first item in my todo list.

**Comment by ryanpcmcquen** [comment]
I ran option 2. The document has the following format:

```
Image
Code block
** Where I am trying to put the second image. **
Code block
```

**Comment by ryanpcmcquen** [comment]
It must have been something with the note, I ended up just having to choose 'From device' and re-upload the image.

**Comment by johnozbay** [comment]
Just checking in - was this document specific? Were you able to reproduce this with another fresh document?

**Comment by johnozbay** [comment]
@ryanpcmcquen checking in ✌🏻

**Comment by ryanpcmcquen** [comment]
@johnozbay, this seemed to be document specific, closing.

**Comment by johnozbay** [comment]
Glad to hear it's resolved! Ping me back if it shows up again! Not going to rest until I kill all the bugs 🕷🐞🐛
