### ISSUE TITLE
[Design / Bug] Photos - Album created for the first time is not visible

### ISSUE THREAD

**Issue by Visual-Notes** [cryptee/web-client#40]
When we use the Photo function for the first time, we are prompted to upload photos ("Let's get started").
After uploading by drag and drop, the thumbnails of the uploaded photos appear, but they are apparently not in any album. 
If we create a new album by clicking "New Album" (only now we see that link!), photos will be uploaded to this album and we can give the album a name. 
Still the first uploaded photos are apparently not in any album. In order to achieve this, we need to create a new album and move the first uploaded photos to this new album.

I don't think that this behavior is intended.

The problem could be solved if the function "Let's get started" would trigger the same action as "New Album".

![new_photo_album_01](https://user-images.githubusercontent.com/1451511/74930408-ce2aa300-53dd-11ea-8d6e-a28bd7a711b5.png)
![new_photo_album_02](https://user-images.githubusercontent.com/1451511/74930412-d256c080-53dd-11ea-9bb3-7a0e3799d5eb.png)
![new_photo_album_03](https://user-images.githubusercontent.com/1451511/74930419-d551b100-53dd-11ea-9d64-5b7ecfd1b52e.png)
![new_photo_album_04](https://user-images.githubusercontent.com/1451511/74930423-d7b40b00-53dd-11ea-8478-854850dd47dc.png)
![new_photo_album_05](https://user-images.githubusercontent.com/1451511/74930425-da166500-53dd-11ea-93be-7f568dbb630c.png)
![new_photo_album_06](https://user-images.githubusercontent.com/1451511/74930433-dc78bf00-53dd-11ea-9b68-7448b87f61a4.png)
![new_photo_album_07](https://user-images.githubusercontent.com/1451511/74930436-dda9ec00-53dd-11ea-891a-00098b56c958.png)

**Comment by johnozbay** [comment]
Hey there!

I think the UI is confusing here, and I take full blame. But this is the intended behavior. (In fact, it's the same behavior as all other online Photo services like Google / Amazon etc.) Here's why. 

Most users want a place to dump photos, and not have to worry about categorizing them. They want the platform to be smart enough to somehow group the photos for them. This is exactly the reason why Apple, Google, Amazon, all offer things like face-recognition, location-recognition, gps-based grouping, date-based grouping, AI-detecting birthdays and grouping parties etc type of functionalities. To auto-categorize these bulk-dumped photos.

And just like all these other services, on Cryptee your photos don't need to belong to an album. You can dump 100,000s of photos to your home folder, and not have to put them in albums if you really want to so. So photos & albums live side by side on the home folder. 

So, it's correct that let's get started does not create a new album. Instead it specifically encourages dragging & dropping photos. Once these photos are uploaded, users can select, and move them into albums if they wish. 

– About the bad design part –
I think the reason why this design is confusing is because when you create an album, the brand new "unnamed album" is called "New Album". 

And the move pop-up shows you 3 options right now. 
1) "+ New Album" (This creates a new album from your selections / moves the selections into this new album)

2) "Home" (Since these photos are already in home folder, it's greyed out)

3) "📁 New Album" This is the album you've created earlier. 

(Rename the albums to something else like "Album 1" and "Album 2", and I think you'll understand what I'm trying to explain here.)  

What I take from this is : 

- [x] I'll change the default name of an album to "Untitled / Unnamed Album", this way the New Album button won't be as confusing. 

- [ ] Now that you mentioned this, I am starting to see why the NEW ALBUM button on the home screen looks confusing. It looks like a header / heading / name of an album you're in. 
While in fact it's the button to create new albums. 

<img width="989" alt="Screen Shot 2020-02-20 at 22 22 36" src="https://user-images.githubusercontent.com/611338/74975429-b4b24700-542f-11ea-8a43-b7e2696accc8.png">

But if you have no albums, and only 4 photos, it's natural to think, oh I've uploaded photos, and they're in "New Album". I now completely see how this is confusing, and I'm going to redesign this button and make sure it's clear this is a button. 

– I'm quite surprised this exact flow didn't come up in our UX test. So I think I need a clearer way to show this is a button. 

- [ ] Finally, I'll make some changes to the move dialog to make things clear. For example I'll use something like "+ Create New Album" (instead of "+ New Album") etc. 

Does this make sense?

**Comment by johnozbay** [comment]
We're making incremental improvements to this flow, and this was the first update to address some of the design issues. Thanks a lot for bringing these up!
