### ISSUE TITLE
[Bug] Improvements for images in documents

### ISSUE THREAD

**Issue by Visual-Notes** [cryptee/web-client#41]
1) It would be useful if we could select, copy, cut and paste images in documents - just like text, both via context menu and standard shortcuts. 

2) An image embedded in a document has handles that can be used to change the visual size of the image. The maximum size is limited by the width of the document. However, there is no limit to the minimum size of an image, which means that you can use the handles to reduce an image so that it disappears completely. Since this makes no sense, I suggest setting a default limit for the minimum size of an image. Because of the fixed radius of the round corners of images, a size below 100 pixels width makes little sense anyway, so this could be the limit.

**Comment by johnozbay** [comment]
1 – This one's quite tricky. And it mostly depends on the way browsers interpret images. Basically when you're dragging anything (say an image) around, [most] browsers don't know whether if the image being dragged is dragged from within the browser, or from outside of the browser into the browser. 

And dropping an image into the editor means 'uploading' a new image. So if you drag an image that was in the editor, and drop it somewhere else in the editor, it ends up re-uploading the image = copying & pasting the image, instead of moving it. 

For this reason I had to disable moving images. 
So this is the reason why it's tricky to "select" an image, since the selection is quite virtual for the lack of a better word. 

Now, there is technically already a way to do what you're asking for. If you select an image next to text (or even a blank space really, you just need to select the image, not by clicking on it, but by dragging the mouse past it like you'd select text) then you'll notice that the image becomes highlighted, like the way text becomes highlighted when you select/highlight it with your cursor. You can then all the shortcuts like text. Copy, cut, paste etc. will all work. Selecting the image this way, will treat it like an inline-text-object. 

However, clicking on the image itself, treats it like an inline-block/cryptee-image-object, so that it can be resized. 

2 – This is a great catch. Will add a minimum width to images with the next release.

**Comment by Visual-Notes** [comment]
> Now, there is technically already a way to do what you're asking for. If you select an image next to text (or even a blank space really, you just need to select the image, not by clicking on it, but by dragging the mouse past it like you'd select text) then you'll notice that the image becomes highlighted, like the way text becomes highlighted when you select/highlight it with your cursor. You can then all the shortcuts like text. Copy, cut, paste etc. will all work.

Whatever I tried - and I even managed to select an image this way (finally it was highlighted!) - no shortcut and no context menu command worked (Firefox 73 on MacBookPro, Catalina).

I think, if such basic functions are technically not possible - maybe because of encryption or the fact that Cryptee is browser-based only or for other technical reasons, whose background requires a solid knowledge that most of us don't have - then the user should be able to consider if this is actually the right software for him - but he can only do this if he is informed accordingly. I therefore believe that it would be good to basically explain which expectations are not and never will be technically feasible, so that potential users do not have false expectations and think they only have to wait for the next updates to see a desired functionality implemented. It would be fair to make it very clear on the homepage what Cryptee is designed for, and especially what it is not and cannot be.

@ johnozbay: 
To me, this has only become a bit clearer through your very detailed and informative answers. But as you can see from my request above, obviously still not clear enough ;)
I now tend to believe that Cryptee is mainly made for people whose top priority is security, and it is clear that in this case the lack of some functionality is of course accepted.

But the majority of people who want their personal files to be encrypted will probably not mean highly sensitive secret documents, but will have just the normal desire to keep private things private. I think that these people, including myself, should be informed early about the fact that they will have to make some compromises and accept the definitive absence of some features.

**Comment by johnozbay** [comment]
First off, I think you're misunderstanding what I wrote. The basic functionality you're referring to (the ability to cut/copy/paste images _does indeed exist_). So I made two gifs to show you what I mean. 

You wrote : 
> It would be useful if we could select, copy, cut and paste images in documents - just like text, both via context menu and standard shortcuts.

And here's what I wrote above – that you **can in fact** select an image, copy, paste, cut etc – working in Firefox on a Mac : 

![Firefox](https://user-images.githubusercontent.com/611338/75064783-3ec1e480-54f0-11ea-9463-85df96204118.gif)

and here it is working in Chrome on a Mac :

![Chrome](https://user-images.githubusercontent.com/611338/75065075-c27bd100-54f0-11ea-8711-a6adccdd0190.gif)

I used dropdowns instead of keyboard shortcuts to illustrate my point more visually in GIFs, but keyboard shortcuts work as well. 

---

If this doesn't work for you, it doesn't necessarily mean the feature you're looking for doesn't exist. It means that either you have an extension breaking this feature in your browser / OS, or there's a bug in Cryptee specific to the browser & OS version you're using. 

Tons of Cryptee users have extensions or Firefox privacy settings configured that disable/break/change all the standard features you'd expect from a browser. 

And this is the reason why, we have a bug-report template that looks like this : 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/611338/75065517-ae849f00-54f1-11ea-9224-a726dd634afb.png">

So all I can kindly ask is, next time you file a bug report, please use the bug-report template we have on GitHub. This template is there for a reason. The information on that template is there to understand if something should work in a browser/os but doesn't, how it should work, how/what/where things fail.

If you see a functionality you think should exist, but looks like a bug, ideally either disable the extensions to see if they're breaking something or test it on another browser to make sure it's not an extension you have that's breaking something. (Or it can even be a browser lacking so many necessary features that we don't even support. Like : [Pale Moon](https://www.palemoon.org)) This will save everyone time.

--- 

Now to further clarify what I'm talking about here : 

> So if you drag an image that was in the editor, and drop it somewhere else in the editor, it ends up re-uploading the image = copying & pasting the image, instead of moving it. For this reason I had to disable moving images.

Dragging an image around isn't possible for now. – You _can_ cut/copy & paste the image. 

I'm sorry that Cryptee, a bootstrapped, free and open source software doesn't have exactly the same features you expect to find in Word or Google Docs, two softwares made by trillion dollar companies. But I cannot possibly make a list of all the 100,000 little features Cryptee doesn't have compared to Word or Google Docs either. Because I don't know which little feature is more important to who. 

And this is exactly why there's a free tier. You can try it, use it, and find out whether if it satisfies your needs or not. If dragging an image around is absolutely critical for you, you can file for a feature request / bug report, and we'll do our best to ship it right away. 

Finally,
> 2 – This is a great catch. Will add a minimum width to images with the next release.

This is now fixed, and will be out with the next release.

**Comment by Visual-Notes** [comment]
I apologize, I tried it again on Chrome and it worked, on Firefox I couldn't get paste to work,  maybe - as you mentioned - because of some extension, which I don't know what that could be.

All I tried to say is that I personally think it would be good if users were made aware of possible limitations from the start. But I understand that this is the wrong place for this.

**Comment by johnozbay** [comment]
This update added minimum width to images, and we've re-written most of the editor. 
The app is 45% smaller now. 

Looks like this re-write fixed hundreds of other bugs as well. 
Give it another try to see if you can cut/paste images as you'd expect in Firefox now ✌🏻 
Thanks for these!
