### ISSUE TITLE
Folder's offline-available option turns off after creating a new note

### ISSUE THREAD

**Issue by HitchRait** [cryptee/web-client#45]
Not actually sure whether it is a bug or... a feature :)
**As is**:
Let say there is a folder with some notes inside, in folders's menu I tap "Docs Available Offline", menu closes and in a couple of seconds can see: (1) option is enabled in folder's menu, (2) blue dots on each note inside the folder. Then if I move some other note (not available offline) from outside of it to the inside or just create a new note inside the folder, this note does not become available offline and folder's "Docs Available Offline" option turnes off. Moving the note back outside (or deleting newly created note) turns it on.

**Expected** (...at least as I was expected):
Offline-enabled folder keeps all notes inside offline-enabled as far as they stay in that folder, so that
an online-available note (or new one) if moved into offline-enabled folder, becomes available offline. And vice versa - any note that was made offline-available by enabling folder's option turns online-available after moving outside of folder. But any note deliberately made offline-available by user (in note's menu) preserves that option if moved outside.

**Comment by johnozbay** [comment]
Hi there! 

This is a fantastic catch! 👏🏻

I'll explain why we've built things this way, and I think you'll agree that this was the least confusing solution to a bigger problem. 

In short, this behavior has to do with a couple things. 

1) Ghost Folders 
2) Subfolders
3) On-device encryption 
4) Cryptee being online-first (instead of offline-first).

With apps like Evernote, all your notes are stored offline-first and offline by default, THEN sync'ed to the cloud for sync'ing between devices. This is great if your files & library won't be large, since you don't have to wait for your note to be downloaded & decrypted.
 
Whereas Cryptee Docs is online-first. Similar to Google Docs, and you can choose to make specific documents / folders available offline for accessing them faster / on the plane without internet etc. This has to do with the fact that Cryptee Documents and libraries are built to grow a lot larger. A doc can easily be ~25-40mb if you start embedding large photos, KaTeX math, writing code in it etc. But also, because Cryptee Docs isn't just storing note/doc files, but also PDFs, Audio, Video, Zip whatever file you throw in the same folder or attach the document. Like a PDF Report side by side with your doc, and keep taking notes etc.
 
Because you can attach any encrypted file to documents in Cryptee, it means that your library can grow really big really quickly, and you could theoretically have more docs on Cryptee than your phone / tablet / laptop's storage space. (Cryptee supports 2TB for example, which is way beyond most laptops and phones) Side effect of this is that it’s impossible to make it offline-first because your device would run out storage space quickly.

This behavior is pretty much the same on all services that require larger than usual storage capacity. i.e. on Spotify you can selectively make songs offline. or on Google Docs, you can selectively make things offline etc. 

---

Now with this in mind, here's some of the things that would happen if things downloaded for offline availability automatically when you put them in folders. 

**Case 1)** Folder has one doc, you make folder offline. Then you move 100 x 10MB documents into that folder. Your phone would need to download 1GB worth of files in the background. But worst of all, what if your device has less than 1GB storage? How should these downloads be prioritized? 

**Case 2)** Folder has 100 docs, you make folder offline. Then you attach 1 x 10MB attachment to each document. Arriving to the same problem as Case 1. 

**Case 3)** 
You have 10 folders named like `"Project 1"`, `"Project 2"` ... `"Project 10"` etc. each have 100 docs, and are around 1GB each. 

You have a `"Projects"` folder, it's marked available offline, and has only one doc in it. 

You move all 10 `"Project 1"` - `"Project 10"` folders into the "Projects" folder. 
Should `"Project 1"`, `"Project 2"` ... `"Project 10"` etc. all become available offline? - thus resulting in a 10GB download. 

–– Theoretically these three cases could be solved, if we show users a modal, and warn them that the device will now need to download 1GB worth of content, and let them choose if they wish to. 
But it doesn't end there. 😔

**Complication 1)** You have a folder with 100 docs. It's available offline on your phone, and your phone is offline / app isn't open. On your desktop, you ghost this folder. –– Cryptee intentionally doesn't let clients know whether if a folder was ghosted or deleted or disappeared. (otherwise this flow could be used to identify the existence of ghost folders) ––

So when your phone goes online, it checks to see whether if that folder is there. 
Now what should take priority. Should your phone delete the offline folder? (because server says it's deleted) OR should your phone upload the offline folder to server (because server says it's deleted)

This specific situation gets amplified and worse with Subfolders. See this https://github.com/cryptee/web-client/issues/2#issuecomment-565531632 😩

**Complication 2)** You have a folder, with 100 documents, each doc has 1 PDF attached to them that are in another folder. You ghost the folder with the docs. 

Since all the docs are encrypted on your device, and all the attachment/link-pointers are inside the encrypted docs, there is no way to know whether or not if the docs point to attachments without downloading, decrypting all 100 docs, and following all these links one-by-one. Since this isn't mathematically possible, (or it is but would take impractically long amounts of time and consume lots of data) Cryptee cannot check for these. 

So in theory, Cryptee cannot ghost the attachments/links. (they could even be linked by multiple documents) 

Similarly, if you ghost the folder with the PDFs, but docs are still pointing at the individual PDFs, those links will continue to work, since Cryptee cannot download & decrypt each and every doc you may have (could be up to ~2TB of docs) and remove these links. 😞

---
 
Now that I got the cases and complications out of the way, you can see how combined with the complications, these 3 edge cases cause a nightmare of a sync problem. And since everything is encrypted on your device, and Cryptee servers cannot see your docs, it's not possible to handle sync/conflict resolution on the server. So all sync/change-reporting/conflict resolution happens on/between client devices with Cryptee. (further contributing to all the complications I mentioned above)

For these reasons, in the interest of simplifying all these complications, while developing offline-folders, I've decided that it's best to make it so that _files_ themselves have offline statuses, but not folders. Instead folders have an offline "shortcut" (for the lack of a better word) in the dropdown, where if you press this "make available offline" shortcut, it simply triggers "make offline" button for each file inside the folder. 

And if you add a new file into that folder it simply carries its own offline status. 

---

Hoping all this makes sense! 😅 

I'm all open to suggestions if you think there is a solution to these scenarios and edge cases. But after weeks of contemplating, testing, and trying out different approaches, this was the only solution that made sense and worked flawlessly in every scenario and complication I listed above. 

For now, I'll close the thread, but will gladly reopen it if you have ideas / solutions to some/all of these!

Cheers ✌🏻
