### ISSUE TITLE
[Feature] Word count

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#49]
I think its pretty simple put a word count somewhere, bonus points if it also shows the count of words you have currently selected with your cursor, kinda like google docs do.

I'd also suggest putting it somewhere in this menu:
![Screenshot_2020-03-30_03-35-43](https://user-images.githubusercontent.com/49041398/77865643-125c5f00-7238-11ea-841f-def1f2279be5.png)

**Comment by johnozbay** [comment]
Hi there! 👋🏻

The desktop version actually does have word count & character count! 
It's on the bottom right side of the editor when you hover your mouse to that side.

![Screen Shot 2020-03-30 at 10 38 05](https://user-images.githubusercontent.com/611338/77887058-959aa680-7272-11ea-82d8-bd84491c6eef.png)

Granted it's not clear that it is there, [so we made a helpdesk article just in case](https://crypt.ee/help?article=how-can-i-see-the-word-count-and-or-character-count), but I'll try to think of a way to make it clear without making the design too polluted.

As for the mobile version, Cryptee has to work all the way down to 320 x 568 pixels to support all the way back to iPhone SE, since the SE still runs an up-to-date iOS, but has a tiny screen. 

So with that small of a canvas to paint on, I had no other choice but to cut out some features for the mobile versions, and prioritize perhaps unfairly. 

– In fact, that menu barely fits on some compact android devices, so I've been working on removing some features from that menu. (i.e. "close" is two taps away [one for dropdown, one for close action], and it only opens the home document, while I do know that many users need and want it, opening the home document is technically easier if you swipe to right, and tap on home doc) etc. So I'm trying to find ways to minimize what's on the dropdown, and if I can fit more there, I will add the word count as well ✌🏻

I'll close this for now to make internal tracking easier, since Cryptee does have the feature. 
But let's continue the conversation here, if this doesn't address your use-case / needs! 👍🏻

Hope this helps! Please let me know if there's anything else I can help with! ☕️

**Comment by domanteli0** [comment]
Wouldn't making that menu scrollable fix the issue, allthough, I guess, it would make the navigation a bit more cumbersome on smaller screens.

**Comment by johnozbay** [comment]
While in theory this would be a duct-tape fix, like you also said it would make the navigation very difficult on small screens like the iPhone SE. 

Plus, in general it's a bad UX practice to have same gestures perform different actions on the same view/screen. 

In case of Cryptee, swipe/scroll up&down is for scrolling the document, and swipe left/right is for opening the menu on the left. 

If there was a "tap to click on dropdown menu, swipe up/down to see more", it would be very cumbersome and confusing on a tiny 568px screen, since the screen on iPhone SE is quite literally ~2.5x size of an average person's thumb. Here's a photo for reference:

![](http://cdn.gsmarena.com/pics/13/09/apple-iphone-5s/big.jpg)
