### ISSUE TITLE
Unable to format text as code on mobile.

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#5]
Perhaps we could add in markdown’s triple backtick wrapped syntax for this?

**Comment by johnozbay** [comment]
Hey Ryan! ✌🏻

This is actually already available and documented in the markdown shortcuts window. 
It's `triple backtick` + `enter` 

<img width="427" alt="screen shot 2018-10-05 at 15 38 15" src="https://user-images.githubusercontent.com/611338/46535620-b1f39800-c8b4-11e8-8ebb-3c825a6ab3c7.png">

The syntax has to be a bit more different than the typical markdown syntax. Reason being, typical markdown renderers (say for example the comment boxes here in Github) store markdown compatible plaintext (with backticks) - but then when you click `Preview` (from the top) or `Comment`, the editor parses this plaintext and renders it in the preview window / browser as HTML. I hope I could express the difference and this makes sense.

In case of Cryptee, the editor + renderer are the same, and Cryptee works with a special JSONic delta format that allows cmd + z / undo / and highlighting selections etc. 

Closing due to availability ☕️
