### ISSUE TITLE
[Feature request] Ability to see a word count in partial side by side

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#51]
I'm always frustrated when I can't see word count in partial side by side or then the pdf is lowered.

**Describe the solution you'd like**
I'd expect to see a word count in places marked with red when hovering a mouse cursor above the pdf window in the right side
![Screenshot from 2020-03-31 23-38-27](https://user-images.githubusercontent.com/49041398/78073349-421e7a80-7390-11ea-8563-2603fe40c63e.png)
![Screenshot from 2020-03-31 23-38-31](https://user-images.githubusercontent.com/49041398/78073351-434fa780-7390-11ea-9c0e-bbbb6e01a326.png)

**Comment by johnozbay** [comment]
Looking into how we can make this happen without breaking other things. 

If your document uses headers like H1, H2, H3, a header navigation is shown on the right side, enabling you to scroll through stuff and navigate through your document using headers quickly and easily. 

![image](https://user-images.githubusercontent.com/611338/79430533-bc2a4280-7fd1-11ea-9a69-243ca2afb6bd.png)

For example some of our users mentioned that they're writing long journal entires, and use this instead of regular scroll to get to chapters easily. 

So I think word-count can only be visible if the PDF/file previewer is minimized, otherwise I don't think it'll work. 

Looking into this, and will try to add this to the upcoming release.
Thanks for this ✌🏻

**Comment by johnozbay** [comment]
Next update is shipping this. 🎉
Counts will now show if the previewer is minimized.

Due to cross-device screen-size constraints, there's no place to fit them if the viewer is maximized, but I think it's a start. 
Long-term, I'll find a better solution and move the counts somewhere else entirely.

Once the update has shipped, the issue will automatically be closed, so you'll get a notification ☕️
Thanks a lot for filing this, sorry for the delay, and thank you so much for your patience! ✌🏻
