### ISSUE TITLE
UI goes out of alignment when attaching a file

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#55]
**Description**

Attaching a file to a document makes the document page display half off the screen. If I then click on the document, it flies to the _other_ side of the screen, and displays half of a context menu for something.

**To Reproduce**
1. Open a document
2. From the folder browser, click “...” on a file and select “attach”
3. Behold the chaos
4. Click on the document text
4. Behold the chaos
5. Click on a button on the top edit bar (like the bulleted list button)
6. Normalcy restored

**Expected behavior**

The file attaches and I’m returned to the regular document screen.

**Screenshots**
![44CCEB62-8E4C-4CF4-A0E7-AD2543814F13](https://user-images.githubusercontent.com/273696/80290055-c9dd7780-86f7-11ea-8b33-ba09f83bb79f.png)
![5377E8E5-8086-474F-B36B-AA37A893BCC6](https://user-images.githubusercontent.com/273696/80290057-cc3fd180-86f7-11ea-8d43-bf3b421b86f4.png)
![1F7580CB-2A8A-4BB1-AAFF-6D24AC7B5E36](https://user-images.githubusercontent.com/273696/80290058-cd70fe80-86f7-11ea-86f1-d293c1d4b799.png)
![C5F4ABD0-8FF5-462A-8FCC-61EE07A04603](https://user-images.githubusercontent.com/273696/80290059-cea22b80-86f7-11ea-9f89-ee08cac3cd22.png)
![FB646FA2-C4F8-4148-8F5D-89BBBA44B8A5](https://user-images.githubusercontent.com/273696/80290061-d06bef00-86f7-11ea-9b11-8e39ca607889.png)

**System Information (please complete the following information):**
iPhone 6s, iOS 13.2.3, PWA on home screen

**Comment by dhda** [comment]
This also happens while embedding an image inline.

**Comment by johnozbay** [comment]
I can reproduce and confirm this! Working on a fix now. 
Don't know how this went through the test.
Thanks a million for filing this ✌🏻

**Comment by johnozbay** [comment]
Wow. So turns out I broke a few things with the way slider works 3 - 4 months ago, but it wasn't noticeable at all due to the loading order of things. Last update it made it so that documents load faster, and looks like that suddenly made all these old bugs noticeable. 

i.e. that dropdown was supposed to be outside of the viewport,  past `overflow:hidden` – but looks like if Cryptee hands over focus to the keyboard first – before moving the slider, then the operating system slides and centers the overflow view itself causing this to happen🤦🏻‍♂️

Working on a fix now, and as soon as it's ready, will push it out as a delta-update / bug fix update. 

As a positive side effect, menu will work much faster now. 
Thank you for reporting this. I owe you a big one. I still don't know this went past the tests, given that we do a visual overall testing of all layout features.

**Comment by johnozbay** [comment]
^ This should be fixed now! Let me know if you're still having issues after the update ✌🏻 And many thanks for reaching out with this. Seriously a hall-of-shame level fuck-up on my part with automated testing. 😂 Will do better I promise.
