### ISSUE TITLE
Backspace sometimes sends browser back instead of deleting

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#56]
**Describe the bug**
When I try to delete an inline image by selecting it (so that the resize handles and alignment buttons appear) and then pressing the Backspace key, it triggers my browser to go back to the previous page (which takes me out of Cryptee's documents space because that's the previous URL). Selecting the image and using the Delete key works as expected. Placing the text cursor immediately after the image and pressing Backspace also works as expected.

**To Reproduce**
1. Click inline image
2. Press Backspace
3. Cryptee goes back to home page (and from there requires me to reenter my encryption key).
4. Reloading the document, the image isn't deleted.

**Expected behavior**
Image gets deleted, I don't get kicked out of my document.

**System Information (please complete the following information):**
 - Device: Macbook Pro
 - OS: OS X 10.11.6
 - Browser: Firefox 75.0
 - Browser Extensions: tested with all extensions disabled

**Additional context**
Maybe there's a tangential feature request in this to do some URL magic to make the browser history work more as expected. Though I understand that browser history could be an information leak for some use cases (though can't they deal with that more robustly using private windows?).

**Comment by dhda** [comment]
I just tested this in Chrome and all works as expected, so it seems to be an issue only in Firefox.

**Comment by johnozbay** [comment]
Hi there ✌🏻
Thanks a lot for filing this! 

This is a Firefox specific issue indeed. 
All other browsers consider the image a selectable element / building block in the text editor, so in all browsers you can select an image much like you can select text, and the editor won't lose focus if you click on the image. Whereas Firefox treats the image in the editor differently, and if you click on the image, the editor loses focus. And Firefox's default behavior when you press backspace is to go back to the previous page. And Firefox users have been incredibly frustrated about this silly hotkey shortcut for 8+ years now, voicing their frustration on tons of different websites, as well as Mozilla's support forum :

https://support.mozilla.org/en-US/questions/924490 (8 yrs ago)
https://support.mozilla.org/en-US/questions/1113960 (4 yrs ago)
https://support.mozilla.org/en-US/questions/1195262 (2 yrs ago)
https://www.reddit.com/r/firefox/comments/8jfkmk/need_to_disable_backspace_back_hotkey/
etc. the list goes on and on.

Short of overriding the backspace button entirely, changing the built-in browser behavior, and checking to see if each backspace press takes place in a text box / input field / text editor / image / or the user is simply trying to go back to the previous page – which would be a bad idea overall in my personal opinion – there really isn't much we can do here. If you're not using the backspace to navigate to the previous page hotkey in Firefox, I recommend disabling it from Firefox's settings and things should go back to working as expected. 

In the meantime, I'll see if we can find a way to override the backspace key selectively & un-invasively. Each browser has a different selection of hotkeys you can't override. i.e. on Macs, browsers prevent overriding `cmd + w` or `cmd + q`, so that malicious websites can't stop users from closing the tab. 

For now, I'll close this issue – but we'll keep exploring different options for future releases.
