### ISSUE TITLE
Cannot search images ‘From Cryptee’ after latest update.

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#7]
Since the latest update, when searching images to embed ‘From Cryptee’, no results ever appear.

**Comment by johnozbay** [comment]
Hey @ryanpcmcquen!

Which Browser / OS / Device / Version is this happening on? This pest certainly managed to get past through the tests. 🕷I will need to know more to be able to reproduce this.

**Comment by ryanpcmcquen** [comment]
Safari on iOS 12.x.

**Comment by johnozbay** [comment]
Hey there! 

Seems to be working on my devices. Here's a screenshot from iOS 12, iPad 2018.

![img_6b52d8ea93f4-1](https://user-images.githubusercontent.com/611338/46794465-8bb87700-cd50-11e8-963c-d77353712beb.jpeg)

If possible could you detail the steps you took? So that I can reproduce it exactly on my part.

Sorry about asking a lot of questions btw - having this many platforms to support means that I have to test every new addition/fix on ~15 different device + OS + browser combinations. To make sure everything works smoothly, I have an automated test system, which tests pretty much every combination, permutation & route you can take to perform an action, but of course, with as many possibilities, machines can't fully replace live-testing, and sometimes doing things in a different order causes these bugs to pop up.

**Comment by ryanpcmcquen** [comment]
I am in between two code blocks and click the embed image icon. Then I type ‘sk’ and no results appear, but I know there is an image that begins with that name.

**Comment by ryanpcmcquen** [comment]
I was also able to repro this on Linux/Firefox/latest. I ended up just having to re-upload the image to embed it.

**Comment by johnozbay** [comment]
Is this related to #4 ?

**Comment by ryanpcmcquen** [comment]
Yep!

**Comment by johnozbay** [comment]
Continuing this at #4.
