### ISSUE TITLE
[Bug] Ebook reader: text size, text area borders, full-screen mode

### ISSUE THREAD

**Issue by HitchRait** [cryptee/web-client#74]
Whenever I tried to open epub books in cryptee, it shows me unpleasant result (comparing to other ebook viewers):
1) Text area is so narrow, sometimes it fits only 4 words in a line (true to desktop and mobile)
2) There is a plenty of space between text area and (2.1) arrows to turn pages, (2.2) book title on top and screen edge on bottom (only desktop)
3) I cant change split screen ratio, it is 50-50 by default (only desktop)

So I came up with the options mentions in the topic that may solve those problems.

**Comment by brendanperry** [comment]
I've noticed this same thing. They are unreadable on my SE because there are so few words on a single page.

**Comment by johnozbay** [comment]
Hi there! 

Thanks a lot for filing this, and apologies for the delay! We've been working on a major re-write – Docs v3.0 for the lack of a better word – and we're running two parallel versions, fixing as much stuff as we can in the current one, and making sure the new/upcoming version has the fixes applied as well. So I've been slow at responding to GitHub lately.

Looks like this is actually related to #68, and will be fixed once that's fixed. I wrote a lengthy answer there regarding why this one's going to take a little extra while to fix. 

tdlr;
> epub ebooks are actually simply well structured html files. This means they're great for viewing online. But as a side effect, the epub format itself comes with a big potential security risk if you're viewing it online/in a browser. Because ebooks could theoretically contain malicious code in them, and if we were to open them without proper sandboxing, these could potentially compromise your account security in some way.

So due to the additional security overhead, progress is moving slower with ebooks, but we're making steady progress nevertheless! 

Will keep this thread (and the other one) posted with more info as we're ready to roll the fixes out to beta, so you can start testing and let us know how things are looking like!

Many million thanks for the help both, deeply appreciate it!
– And once again apologies for the delay, and thank you for your patience! 

Best,
J

**Comment by johnozbay** [comment]
Hi there everyone! We've released v3.0 yesterday, and it has a much better & improved ebook / epub reader with font-size adjustments new layout and dark/light mode etc. Here's how it looks like : 

![Docs  DM – Grid – iPad   iPhone Green (Scene 8) EPUB](https://user-images.githubusercontent.com/611338/108709390-4b21b880-751b-11eb-9cd0-45102dffe151.jpg)

So I think this should be fixed in https://github.com/cryptee/web-client/commit/01edfe472a72557aa2c323fc55a77e25612b0da4 so I'll close this issue  for now – but feel free to re-open this and let me know how you think we can improve this, and we'll make it happen!
