### ISSUE TITLE
[bug] Bold+italic text is always rendered with the default font

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#78]
## Describe the bug
Text that is set to a non-default font, with both bold and italic formatting, gets rendered in the default font.

_screenshot:_
<img width="416" alt="Screen Shot 2020-06-25 at 21 43 09" src="https://user-images.githubusercontent.com/273696/85821422-7f936980-b72d-11ea-9459-7eb5bdecbb89.png">

## System Information
Happens with both Firefox on MacOS and iOS Safari.

 - Device: Macbook Pro
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox
 - Browser Version: 77.0.1
 - Browser Extensions / Add-ons / Content Blockers: All disabled
.
 - Device: iPhone 6s
 - OS: iOS 13.4.1
 - Browser: Safari PWA
 - Browser Extensions / Add-ons / Content Blockers: None

**Comment by johnozbay** [comment]
Fantastic catch! Thanks for this! We'll line up the fixes for the upcoming release!

**Comment by johnozbay** [comment]
We've just released v3.0 yesterday, and this should be fixed in https://github.com/cryptee/web-client/commit/01edfe472a72557aa2c323fc55a77e25612b0da4 now. 

![image](https://user-images.githubusercontent.com/611338/108708886-b028de80-751a-11eb-9d29-19344c6d2186.png)

Let me know if you run into this again with any other fonts etc, and we'll be happy to kill this bug for good! Until then I'll close this issue! 

Thanks a lot for this ✌🏻
