### ISSUE TITLE
No longer able to access large notes.

### ISSUE THREAD

**Issue by ryanpcmcquen** [cryptee/web-client#8]
I have some large notes (from around 100kb to 1mb), I was able to load them before the big update, but now they just crash my browser. Tried on Linux/Firefox/latest and Linux/Chromium/latest.

**Comment by johnozbay** [comment]
Hey Ryan, the performance update didn't change anything regarding document handling. Only some GUI changes, boot order, and handling large libraries of document titles more efficiently. 

In addition, I run all deploys with a 20mb test doc with images + texts + embeds and all combinations available. It is passing every test I can throw at it on both FF and Chromium Linux. I have also run multiple test scenarios by hand manually. Everything seems to be passing.

Since all the contents of your notes are encrypted, and I have no way of seeing / debugging these types of doc-specific issues.

Did you try creating a new document and embedding large images into this new document? Does that crash as well? Or is it just these specific docs?

I'm afraid, I'll need more doc-content-specific and likely private info to debug this. 
Be it from what's actually in the doc (that might be crashing your browser - to if you've tested opening these in another browser / os / mobile etc.) In the interest of keeping your information private I'm closing this thread. Please reach out via email where we can discuss the details privately.

**Comment by johnozbay** [comment]
If these documents have lots and lots of text, try turning off the spellchecker from account settings > preferences, and try opening again.

One user reached out before I pushed b33a7c3498c628847693b2750342060bc06d4859 out, and said that s/he is writing a book in Cryptee, and would love the ability to turn off spellchecker, because it slows down the browser to a point of freezing if there's too much text to spell-check.

**Comment by ryanpcmcquen** [comment]
They are all text.
