### ISSUE TITLE
[Bug] Pasting images results in the image appearing at the top of the document.

### ISSUE THREAD

**Issue by jebbster88** [cryptee/web-client#80]
**Describe the bug**
Pasting images from the clipboard results in the pasted image appearing at the very start of the document. It appears that as soon as you hit paste, the cursor jumps to the start of the document (as if ctrl-home as hit first), before pasting the image. Any text typed after pasting the image appears immediately after the image (at the top of the document).

**To Reproduce**
1. Open a cryptee document
2. Get an image onto your clipboard somehow
3. Put the cursor anywhere in the document
4. Paste, either by Ctrl-V, Shift-Ins or right click menu.

**Expected behavior**
Image should appear where the cursor is.

**Screenshots**
![image](https://user-images.githubusercontent.com/8920215/88599068-bfb67680-d062-11ea-9941-772094ee219a.png)
![image](https://user-images.githubusercontent.com/8920215/88599092-d52ba080-d062-11ea-8a5a-b9461baacb1d.png)

**System Information (please complete the following information):**
 - Device: Laptop
 - OS: Arch Linux (i3wm), also confirmed same issue on Windows 10
 - Browser: Tested in Chrome & Firefox
 - Browser Version: Chrome 83.0.4103.116, Firefox 78.0.2 
 - Browser Extensions / Add-ons / Content Blockers: Issue present in browser with no extensions.
 - Do you have any DNS-based content blockers? [i.e. pi-hole]: Pi-hole (same issue when disabled). 
 - Are you on a managed network? [e.g. VPN / Corporate Network]: No

**Additional context**
Have tried alternate clipboard managers, same results.
Have tried copying from different sources, same results.
 - Copy image from browser (right click, copy image)
 - Copy image from gimp
 - Copy image using gnome-screenshot

The issue doesn't occur in the following scenarios.
 - When copying an image that is already in the Cryptee document (by using the mouse to drag-select it). 
 - When uploading through the upload image tool.
 - When dragging an image onto the page from a file explorer

The issue is not present in the quill-js playground on their website.

I'll hopefully get a chance to test this on windows tomorrow.

**Comment by jebbster88** [comment]
Just came across this, describing the same symptoms I'm receiving.

https://stackoverflow.com/questions/40420446/quilljs-insert-image-on-cursor-position-via-button-click-goes-to-top

**Comment by jebbster88** [comment]
Update: Confirmed same issue present from a windows 10 machine.

**Comment by johnozbay** [comment]
Hi there! 

First off many million thanks for this incredibly detailed bug report, and even taking the time to dig through quill & stack overflow! 🙏🏻 The developer world needs more kind and amazing folks like you! 

Looks like while implementing tables (and adding some table-related exceptions to the clipboard to prevent images from getting pasted into the tables we messed up how images are getting pasted in the first place)

I can confirm that we are able to reproduce this, and we've already started working on a fix. It's going to take a little bit of extra time, because we're also going to build automated test-cases to prevent this from happening again + make sure we don't break clipboard handling for tables when we fix this.
  
I'll keep this thread updated, and release a fix for this ASAP.

Thank you so much for filing this issue! Deeply appreciate it! ✌🏻

Best,
J

**Comment by jebbster88** [comment]
Awesome thanks. I'm so far really enjoying my experience with cryptee, solves a problem I've always had about wanting access to my knowledge base from insecure machines (work ones mainly!) That said there are a couple of niggles (or possible user errors), what's your preferred medium for reporting non-obvious bugs? You seem so active everywhere!

In the meantime if anyone else is experiencing this, I've found the easiest workaround to be...

1. Paste image, cursor jumps to top and image is inserted.
2. Type Shift-left to select the preceding image.
3. Ctrl-x to cut the image
4. Image can now be pasted properly wherever you like

Little bit annoying in larger docs to go find my place again but manageable.

Edit: Read this back and didn't like the positive negative balance. To add, Cryptee is incredibly impressive. I've spent some time reading through your Reddit comments and your commitment to security and your user-base was the main thing that tipped me over the edge and take the plunge.

**Comment by johnozbay** [comment]
Really happy to hear you're enjoying your time on the platform so far! And thank you for your patience while we fix all these little kinks.
  
If you run into errors, it's actually better for us team if you reach out from the [helpdesk](https://crypt.ee/help). At the bottom there's a bug report button. 

Internally we use a much more comprehensive bug-tracker, and can link pieces of your info to possible causes on the platform. 

i.e. we log the speed performance of our APIs, and say for example if our payment processor's API is slower than usual for an hour, and you've encountered an issue, if you reach out using our helpdesk, we can easily map out the time of the incident, and the details of your bug report to see if they're related.

Or let's say if you had a bigger issue, something completely broke on you, reaching out via the helpdesk would make it infinitely easier for us to quickly learn what happened from you, and using your user id we can check our server-side errors that might be related etc etc.

So ideally, use the helpdesk, it'll save us time from all the back/forth messaging, and allow us to assist you faster, armed with more info! 

---

And thank you for your kind compliments! Deeply appreciate and happy to hear my online-presence was a factor for you to choose Cryptee! I love interacting with the users as much as I humanly can on all platforms. I think it's incredibly important that I do this, especially for an encrypted / privacy-focused service like Cryptee.

Since we don't track usage/behavior, nor have any in-app analytics, we have no way of knowing what's working well, what could be improved, and where we are failing. All we can do is play blindfolded-chess, do our best in thinking ahead where bugs might happen, put tons of failsafes in place, and trust the feedback we get from all the amazing people like yourself online! 

I think coding for Cryptee is kind of like coding for a spacecraft. Once it's out of orbit, there's no way to easily de-bug or check what's going on or what's going wrong. Heavy encryption makes it incredibly complicated/impossible to identify and fix errors, since we can't see any of users' data or usage behavior / patterns etc. Essentially the only thing we can do is try to predict what may happen, how it may happen, and write some self-fixing / auto-correcting pieces of code to fix the issues in the browser.

So please reach out with anything you think we can improve, fix or change. Always here to make thing things better.

Many thanks once again! ✌🏻

All the best, 
J

**Comment by johnozbay** [comment]
Hi there! 

Today we've released Cryptee v3.0, which is a complete re-write of the application, and fixes this bug. ( 01edfe4 )
I'll close this for now, but needless to say let me know if you run into this again and we'll get this fixed much faster this time! 

Thanks a million for filing this!

Best,
J
