### ISSUE TITLE
[Feature Request] global search in all documents

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#86]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way to search in the content of all documents stored in Cryptee.

**Describe the solution you'd like**
Global search in the content of all documents stored in Cryptee.
I think it would be enough if Cryptee lists the documents where the search string is present.
If the documents are decrypted in the local client only: it is already possible to decrypt each and every document with the "export all data" function, may it be possible, to first decrypt the documents then search for the given string of characters? It does not matter for me if it takes some time until the search is completed, the export process is slow also.

**Additional context**
n/a

**Comment by johnozbay** [comment]
Hi there, 

I'm afraid this isn't possible, and likely won't ever be possible, _as much as I'd love to make this happen_.

Since everything is encrypted / decrypted on your device, all search takes place on your device as well. Basically if you want to search for the word "cat" and you're on a 2TB plan, with 1.5TB documents / files, you're talking about downloading, decrypting, searching 1.5TB worth of documents on your device, in memory here. It's simply impractical, and borderline impossible.

In part because it's impractical for anyone to wait for 1.5TB of documents to download and decrypt, every time they need to search for a word in their documents,

But also impractical from a financial standpoint. Part of the reason why export feature is possible, is because people don't go ahead and download 1.5TB of their data once a week. They usually do it once a year to have an offline backup or once if they're moving away from the service. 

Right now, our pricing is based on the fact that if you have 2TB of documents, at max you'd use another 25-50% of that in bandwidth every month. (500GB - 1000GB/mo) if users were to download 2TB every month, we'd have to raise the prices to account for the incredibly high bandwidth costs + add more servers to cope with all the extra download traffic. 

It's less so about the speed / time it takes to do all this, but more so about the amount of memory, bandwidth, and impractical amounts of time it would consume for the little benefit it would bring due to its impracticality to users.

Same goes for other on-device encrypted services, like Protonmail. [You can't search the message body for the exact same reasons. ](https://web.archive.org/web/20200813022501/https://protonmail.com/support/knowledge-base/search/)
 
I hope this makes sense,
Best,
J

**Comment by BasilTomato** [comment]
Thank you for the detailed explanation, it is understandable.
At the moment I have only 2.1MB documents, thus as a workaround it is possible to export everything to achieve global search once in every few weeks.
