### ISSUE TITLE
[Feature Request] ability to disable auto correct function

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#88]
**Is your feature request related to a problem? Please describe.**
The auto correct function which is enabled by default, and it is not possible to disable this.
It may be a personal preference, but auto correction is the first function I tend to disable in any software solution, because I think it is quite annoying.
In this case if a new line begins with the "-" character then it is replaced by a bullet list item.

**Describe the solution you'd like**
Ability to disable auto correct functionality.

**Additional context**
n/a

**Comment by astarq** [comment]
I think this is what you're after - Settings > Docs Preferences > Spell-Checker

**Comment by johnozbay** [comment]
Thanks a lot @astarq! 🙏🏻

Hi there @BasilTomato, like @astarq pointed out, you can disable spell checker in Docs Preferences here : 

https://crypt.ee/account?action=preferences-docs

If you're looking for a way to disable Markdown shortcuts like ( - ) creating a bullet list item etc.
At the moment this isn't possible due to how tightly markdown shortcuts are integrated into the editor. However, you can cheat these by first typing a space, then typing " - 12345" etc. 

We're working on a new version of the editor, and this feature is already on our to-do list, to allow users the option to disable some keyboard shortcut modules to gain performance. 

Let me know if you're looking for something else, and I'll re-open the issue ✌🏻

Best,
J

**Comment by BasilTomato** [comment]
Thank you, this "cheat" is fine for me.

**Comment by johnozbay** [comment]
You're very welcome! If this doesn't work (on some devices, OS / autocorrect adds spaces automatically, so Cryptee tries to compensate for these to make sure Markdown works as expected) try something like " -12345" then later add the space between "-" and "12345". 

It's a constant struggle to make sure things work across OSes, and browsers, and make sure it works on all types of different auto-correctors. (especially on android, because text-selection & input is handled differently in different versions of android customized different by different vendors)

**Comment by BasilTomato** [comment]
Thank you for the additional info, I have already disabled each and every auto correction function on Android also.
Simply I don't like this function, there are always shortcomings.
