### ISSUE TITLE
[Feature Request] option to set the line spacing

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#89]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Option to set the line spacing beside the font size setting.
The current default spacing is fine for a laptop screen, but on mobile phone (eg. 6'' screen, 1080x2160 resolution) a more dense line spacing would be more comfortable for me.
I am not quite sure what the current spacing is, but for example: if the current is 8 points, then options may be: 0pt, 2pt, 4pt, etc.

**Additional context**
n/a

**Comment by johnozbay** [comment]
Hello there! 👋🏻 

We're making steady progress towards making this happen. In v3 we've shipped some code that will very soon enable print-layout / continuous layout, and we will introduce line-spacing with this as well.

You can track the progress for the print layout in #58 – once that's out of the way, we will ship line spacing! 🎉

Thanks a lot for your patience!

**Comment by BasilTomato** [comment]
Thank you for the update!

**Comment by johnozbay** [comment]
Hi there! 
We're almost ready to release line spacing, and pushed it to beta to test it out en-masse. 

Fire up [beta.crypt.ee](https://beta.crypt.ee), and make sure the app's version is `8165beb` 
(you can see this on the top right under account settings) If you don't see this version yet, try giving it a reload / clear caches etc (might take another hour or so for caches to bust otherwise) 

Then launch Docs, and enjoy! 🎉

We need to test out a few specific things before we can release this, so if you wouldn't mind try : 

- Undo / Redo on a paragraph with custom line spacing.
- Cut / Copy / Paste some text with custom line spacing.
- In a table cell
- In all lists
- With attachments & links
- With headings

Needless to say it should all work 😅
Anyhow – let me know what you think 🎉

p.s. – 
On other rich document editors (i.e. Word, Google Docs etc) line spacing is a block-level setting. 
Meaning that even if you select a single word, the whole paragraph's line spacing will be adjusted.

# Screenshots

&nbsp;

![cryptee-line-height](https://user-images.githubusercontent.com/611338/117978226-53c7a500-b33a-11eb-8544-5325c21939c2.jpg)

![cryptee-line-height-tables](https://user-images.githubusercontent.com/611338/117978260-5b874980-b33a-11eb-80c0-fb9d0cc1d4e6.jpg)

![cryptee-line-height-attachments](https://user-images.githubusercontent.com/611338/117978271-5de9a380-b33a-11eb-9801-21fb2e77fb9b.jpg)

![cryptee-line-height-lists](https://user-images.githubusercontent.com/611338/117978240-57f3c280-b33a-11eb-9750-37ffc1b86d28.jpg)

**Comment by johnozbay** [comment]
9187bc88d94e42c37edcf7bc27175243a0bd3f89 adds this functionality! Let me know if you run into any bugs! 🎉
